[package]
name = "dlserver"
version = "0.1.0"
authors = ["Johan Planchon <joxcat@planchon.xyz>"]
edition = "2018"

[dependencies]
nickel = "0.11.0"
reqwest = "0.9.8"
serde = {version = "1.0.85", features = ["derive"]}
serde_json = "1.0.36"
chrono = "0.4.6"
clap = "2.32.0"