/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c -w -O3 -fno-strict-aliasing  -I/home/kuro/.choosenim/toolchains/nim-0.18.0/lib -o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/conf.o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/conf.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_AsyncHttpServercolonObjectType__9blhbIPPCWUB8g9b1PZ6GMnw tyObject_AsyncHttpServercolonObjectType__9blhbIPPCWUB8g9b1PZ6GMnw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg;
typedef struct tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ;
typedef struct tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w;
typedef struct RootObj RootObj;
typedef struct tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg;
typedef struct tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA;
typedef struct tyTuple_kN8up2W6YKc5YA9avn5mV5w tyTuple_kN8up2W6YKc5YA9avn5mV5w;
typedef struct tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ;
typedef struct tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg;
typedef struct tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg;
typedef struct tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q;
typedef struct tyTuple_jq7X5k7hWG0tdTZTDkiyGQ tyTuple_jq7X5k7hWG0tdTZTDkiyGQ;
typedef struct Exception Exception;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ;
typedef struct tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw;
typedef struct tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w;
typedef struct tyObject_Table_LLQadDAXEvd71UDdEc3lDA tyObject_Table_LLQadDAXEvd71UDdEc3lDA;
typedef struct tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw;
typedef struct tySequence_MlAD6nAPq9bHKla9cWiIZP0g tySequence_MlAD6nAPq9bHKla9cWiIZP0g;
typedef struct tySequence_oLpBKXzW3hF9aCVMo5EymfQ tySequence_oLpBKXzW3hF9aCVMo5EymfQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ;
typedef struct tySequence_8Np6tlClE5az1CyqZdN19bQ tySequence_8Np6tlClE5az1CyqZdN19bQ;
typedef struct tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw;
typedef struct tySequence_JiteSJxrvz63iP2o9bcn2Sg tySequence_JiteSJxrvz63iP2o9bcn2Sg;
typedef struct tyTuple_awOivLjlO76sGdHY7nQUjQ tyTuple_awOivLjlO76sGdHY7nQUjQ;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct tyTuple_g1w83cyyBYiVU9c8WEJWnjQ tyTuple_g1w83cyyBYiVU9c8WEJWnjQ;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, ClP_0) (tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ* request, void* ClE_0);
void* ClE_0;
} tyProc_9cYHoVsKEcSHuZkNJna2Tvg;
struct RootObj {
TNimType* m_type;
};
typedef NU8 tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA;
struct tyTuple_kN8up2W6YKc5YA9avn5mV5w {
NimStringDesc* Field0;
NI Field1;
NI Field2;
};
struct tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ {
NimStringDesc* scheme;
NimStringDesc* username;
NimStringDesc* password;
NimStringDesc* hostname;
NimStringDesc* port;
NimStringDesc* path;
NimStringDesc* query;
NimStringDesc* anchor;
NIM_BOOL opaque;
};
struct tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ {
tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg* client;
tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA reqMethod;
tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers;
tyTuple_kN8up2W6YKc5YA9avn5mV5w protocol;
tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ url;
NimStringDesc* hostname;
NimStringDesc* body;
};
typedef struct {
N_NIMCALL_PTR(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_3cmVDZYspcmD9a16VGUFJoA;
struct tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w {
  RootObj Sup;
NI colonstate_;
tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ req1;
tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* retFuture2;
tyProc_3cmVDZYspcmD9a16VGUFJoA nameIterVar3;
};
struct tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg {
  RootObj Sup;
NI colonstate_;
tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w* colonup_;
tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future2;
tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future3;
tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* json4;
tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future5;
tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future6;
};
struct tyTuple_jq7X5k7hWG0tdTZTDkiyGQ {
NimStringDesc* Field0;
tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* Field1;
};
typedef tyTuple_jq7X5k7hWG0tdTZTDkiyGQ tyArray_nFPyKpuH1zPi4VuXhWbFAg[1];
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef long tyArray_TcvIiMAJvcwzNLsZkfnFnQ[25];
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef N_CLOSURE_PTR(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, TM_ePTWny02hxrh8o3cJG7UaA_15) (void);
typedef N_CLOSURE_PTR(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, TM_ePTWny02hxrh8o3cJG7UaA_16) (void);
struct tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA {
  Exception Sup;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
typedef N_CLOSURE_PTR(void, TM_ePTWny02hxrh8o3cJG7UaA_18) (void);
typedef N_CLOSURE_PTR(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, TM_ePTWny02hxrh8o3cJG7UaA_19) (tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ* request, void* ClE_0);
struct tyObject_AsyncHttpServercolonObjectType__9blhbIPPCWUB8g9b1PZ6GMnw {
tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg* socket;
NIM_BOOL reuseAddr;
NIM_BOOL reusePort;
NI maxBody;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ {
tyProc_IIomJ6ptE6vfJ5zRbATgkQ function;
tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ* next;
};
struct tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg {
  RootObj Sup;
tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ callbacks;
NIM_BOOL finished;
Exception* error;
NimStringDesc* errorStackTrace;
};
struct tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
};
typedef NIM_CHAR tyArray_QQGLPNVVwLhYjkngqAxXQQ[4001];
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg;
struct tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg {
int fd;
NIM_BOOL closed;
NIM_BOOL isBuffered;
union{
struct {tyArray_QQGLPNVVwLhYjkngqAxXQQ buffer;
NI currPos;
NI bufLen;
} S1;
} isBufferedU;
NIM_BOOL isSsl;
union{
struct {tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* sslHandle;
tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w* sslContext;
tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* bioIn;
tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* bioOut;
} S1;
} isSslU;
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain;
tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType;
tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol;
};
struct tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA {
tyObject_Table_LLQadDAXEvd71UDdEc3lDA* table;
};
typedef NU8 tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg;
struct tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw {
tySequence_MlAD6nAPq9bHKla9cWiIZP0g* data;
NI counter;
NI first;
NI last;
};
struct tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q {
tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg kind;
union{
struct {NimStringDesc* str;
} S1;
struct {NI64 num;
} S2;
struct {NF fnum;
} S3;
struct {NIM_BOOL bval;
} S4;
struct {tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw fields;
} S6;
struct {tySequence_oLpBKXzW3hF9aCVMo5EymfQ* elems;
} S7;
} kindU;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw {
char dummy;
};
struct tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ {
tySequence_8Np6tlClE5az1CyqZdN19bQ* data;
NI counter;
};
struct tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w {
tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* context;
tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ referencedData;
tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw* extraInternal;
};
struct tyObject_Table_LLQadDAXEvd71UDdEc3lDA {
tySequence_JiteSJxrvz63iP2o9bcn2Sg* data;
NI counter;
};
struct tyTuple_awOivLjlO76sGdHY7nQUjQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* Field3;
};
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef struct {
N_NIMCALL_PTR(NimStringDesc*, ClP_0) (NimStringDesc* identity, void* ClE_0);
void* ClE_0;
} tyProc_lRW9cfxqfm1ql4gkxfLReYg;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NimStringDesc* hint, tyTuple_UV3llMMYFckfui8YMBuUZA* Result, void* ClE_0);
void* ClE_0;
} tyProc_nzIUHFubO43GG203VFo9b7A;
struct tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw {
  RootObj Sup;
tyProc_lRW9cfxqfm1ql4gkxfLReYg serverGetPskFunc;
tyProc_nzIUHFubO43GG203VFo9b7A clientGetPskFunc;
};
struct tyTuple_g1w83cyyBYiVU9c8WEJWnjQ {
NI Field0;
NimStringDesc* Field1;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* Field2;
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence_MlAD6nAPq9bHKla9cWiIZP0g {
  TGenericSeq Sup;
  tyTuple_awOivLjlO76sGdHY7nQUjQ data[SEQ_DECL_SIZE];
};
struct tySequence_oLpBKXzW3hF9aCVMo5EymfQ {
  TGenericSeq Sup;
  tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* data[SEQ_DECL_SIZE];
};
struct tySequence_8Np6tlClE5az1CyqZdN19bQ {
  TGenericSeq Sup;
  tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_JiteSJxrvz63iP2o9bcn2Sg {
  TGenericSeq Sup;
  tyTuple_g1w83cyyBYiVU9c8WEJWnjQ data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_ePTWny02hxrh8o3cJG7UaA_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(tyObject_AsyncHttpServercolonObjectType__9blhbIPPCWUB8g9b1PZ6GMnw*, newAsyncHttpServer_8E3hcKWR9bMseKjk69aa6Aqw)(NIM_BOOL reuseAddr, NIM_BOOL reusePort, NI maxBody);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, openDefaultBrowser_PpG1KNVRhDoDXOHUl4nBBA)(NimStringDesc* url);
N_LIB_PRIVATE N_NIMCALL(void, waitFor_VIKMhEBTNLqEA2ZGnacjrw)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* fut);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, serve_4qUYuAmkUBQy1ChRq42g5Q)(tyObject_AsyncHttpServercolonObjectType__9blhbIPPCWUB8g9b1PZ6GMnw* server, NU16 port, tyProc_9cYHoVsKEcSHuZkNJna2Tvg callback, NimStringDesc* address);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, main_j7F9b9aLZwXb4IG63WlqFcgQ)(tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ* req);
static N_NIMCALL(void, Marker_tyRef_UKvDH8c5AgJpuQy1KoUugg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, newFuture_1afITAy9cOOiZDRZUZbFt0w)(NimStringDesc* fromProc);
static N_NIMCALL(void, Marker_tyRef_rfDuZwtXENcc9ahTQY9bFxAQ)(void* p, NI op);
N_LIB_PRIVATE N_CLOSURE(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, mainIter_ndmONCqrNN0ArfCRFmWSSA)(void* ClE_0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQasyncnet)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, respond_F4lmxjjqUOo55CrHJJWOJw)(tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ* req, NI code, NimStringDesc* content, tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers);
N_LIB_PRIVATE N_NIMCALL(void, read_EYgDXwwneJeAEUfXLUHmhg_2)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__9bR9b9aepApwIZEZZtX9cb7RFA)(tyTuple_jq7X5k7hWG0tdTZTDkiyGQ* keyVals, NI keyValsLen_0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__8iXO9aRAijCPe58pujCBbuQ)(NimStringDesc* s);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, pretty_jL9c59bDERe59bOWSHweWzoBQ)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NI indent);
N_LIB_PRIVATE N_NIMCALL(void, complete_mvHczm6KlNpTkVsXGCEbgg)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future);
N_LIB_PRIVATE N_CLOSURE(void, main_continue_I8OQ7oYoLhO7T5r19cRKPnQ)(void* ClE_0);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(NIM_BOOL, finished_lnX3UZC8cmCUb7BzjNqokQasyncnet)(tyProc_3cmVDZYspcmD9a16VGUFJoA x);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_ZDnEFECD9b9aKFsuVLxFyzkA_2)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_jn4eVK3zFIl4kShRnlTsCg)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(void, callbackeq__9c5z7ouO5bUylgKxaZoIuVg)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future, tyProc_IIomJ6ptE6vfJ5zRbATgkQ cb);
static N_INLINE(void, popSafePoint)(void);
N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(void, fail_8buDkIPh9aRg7WBcB15eisA)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future, Exception* error);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_heapqueueInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_heapqueueDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_listsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_listsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_typetraitsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_typetraitsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_optionsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_optionsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dequesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dequesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cstrutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cstrutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncfuturesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncfuturesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncstreamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncstreamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_opensslInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_opensslDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_epollInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_epollDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_uriInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_uriDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_httpcoreInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_httpcoreDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asynchttpserverInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asynchttpserverDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_linuxInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_linuxDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_browsersInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_browsersDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, confDatInit000)(void);
tyObject_AsyncHttpServercolonObjectType__9blhbIPPCWUB8g9b1PZ6GMnw* server_9acamu2ghB6gPWVei3kcE9bA;
extern TNimType NTI_WZMf6vpVUHkZoBQM9bgqK9aQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_v1MfaYlSBTTzwzfB0NW14w_;
extern TNimType NTI_xHTZrq9aYs6boc9bCba0JbpQ_;
extern TNimType NTI_1Wfxxtqzahm0R6lueM9aQmQ_;
extern TNimType NTI_zXD0JrbeCNyAaW4E6fB9aqg_;
extern TNimType NTI_3cmVDZYspcmD9a16VGUFJoA_;
TNimType NTI_UKvDH8c5AgJpuQy1KoUugg_;
TNimType NTI_lADKcJjPcIxxRUyWT3Tvgg_;
extern TNimType NTI_P6gYL22cCr5PoMFeuBNXwA_;
extern TNimType NTI_zfzzuQ8txrdZAYK0WGWpHg_;
TNimType NTI_rfDuZwtXENcc9ahTQY9bFxAQ_;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern TNimType NTI_TmgWlPUbRr7iGD2UE1cu6A_;
extern TNimType NTI_8FC9arcap3s5ZtfMs75krtA_;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
STRING_LITERAL(TM_ePTWny02hxrh8o3cJG7UaA_3, "http://0.0.0.0:4242", 19);
STRING_LITERAL(TM_ePTWny02hxrh8o3cJG7UaA_5, "main", 4);
STRING_LITERAL(TM_ePTWny02hxrh8o3cJG7UaA_7, "/", 1);
STRING_LITERAL(TM_ePTWny02hxrh8o3cJG7UaA_8, "Hello World!", 12);
STRING_LITERAL(TM_ePTWny02hxrh8o3cJG7UaA_9, "<!DOCTYPE html><html><head><meta http-equiv=\"refresh\" content=\""
"0; url=http://0.0.0.0:4242/\"/></head></html>>", 108);
STRING_LITERAL(TM_ePTWny02hxrh8o3cJG7UaA_10, "/validate", 9);
STRING_LITERAL(TM_ePTWny02hxrh8o3cJG7UaA_11, "res", 3);
STRING_LITERAL(TM_ePTWny02hxrh8o3cJG7UaA_12, "it work", 7);
STRING_LITERAL(TM_ePTWny02hxrh8o3cJG7UaA_13, "Access Denied!", 14);
STRING_LITERAL(TM_ePTWny02hxrh8o3cJG7UaA_17, "Async procedure ($1) yielded `nil`, are you await\'ing a `nil` F"
"uture\?", 69);
STRING_LITERAL(TM_ePTWny02hxrh8o3cJG7UaA_20, "", 0);
static N_NIMCALL(void, TM_ePTWny02hxrh8o3cJG7UaA_2)(void) {
	nimGCvisit((void*)server_9acamu2ghB6gPWVei3kcE9bA, 0);
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
static N_NIMCALL(void, Marker_tyRef_UKvDH8c5AgJpuQy1KoUugg)(void* p, NI op) {
	tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w* a;
	a = (tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w*)p;
	nimGCvisit((void*)(*a).req1.client, op);
	nimGCvisit((void*)(*a).req1.headers, op);
	nimGCvisit((void*)(*a).req1.protocol.Field0, op);
	nimGCvisit((void*)(*a).req1.url.scheme, op);
	nimGCvisit((void*)(*a).req1.url.username, op);
	nimGCvisit((void*)(*a).req1.url.password, op);
	nimGCvisit((void*)(*a).req1.url.hostname, op);
	nimGCvisit((void*)(*a).req1.url.port, op);
	nimGCvisit((void*)(*a).req1.url.path, op);
	nimGCvisit((void*)(*a).req1.url.query, op);
	nimGCvisit((void*)(*a).req1.url.anchor, op);
	nimGCvisit((void*)(*a).req1.hostname, op);
	nimGCvisit((void*)(*a).req1.body, op);
	nimGCvisit((void*)(*a).retFuture2, op);
	nimGCvisit((void*)(*a).nameIterVar3.ClE_0, op);
}
static N_NIMCALL(void, Marker_tyRef_rfDuZwtXENcc9ahTQY9bFxAQ)(void* p, NI op) {
	tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg* a;
	a = (tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg*)p;
	nimGCvisit((void*)(*a).colonup_, op);
	nimGCvisit((void*)(*a).future2, op);
	nimGCvisit((void*)(*a).future3, op);
	nimGCvisit((void*)(*a).json4, op);
	nimGCvisit((void*)(*a).future5, op);
	nimGCvisit((void*)(*a).future6, op);
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQasyncnet)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQasyncnet(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		if (!!((src == NIM_NIL))) goto LA3_;
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_CLOSURE(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, mainIter_ndmONCqrNN0ArfCRFmWSSA)(void* ClE_0) {
	tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* result;
	tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg* colonenvP_;
{	result = (tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*)0;
	colonenvP_ = (tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg*) ClE_0;
	switch ((*colonenvP_).colonstate_) {
	case -1: goto BeforeRet_;
	case 0: goto STATE0;
	case 1: goto STATE1;
	case 2: goto STATE2;
	case 3: goto STATE3;
	case 4: goto STATE4;
	}
	STATE0: ;
	switch ((*(*colonenvP_).colonup_).req1.reqMethod) {
	case ((tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA) 1):
	{
		if (eqStrings((*(*colonenvP_).colonup_).req1.url.path, ((NimStringDesc*) &TM_ePTWny02hxrh8o3cJG7UaA_7))) goto LA2_;
		goto LA3_;
		LA2_: ;
		{
			asgnRef((void**) (&(*colonenvP_).future2), respond_F4lmxjjqUOo55CrHJJWOJw((&(*(*colonenvP_).colonup_).req1), ((NI) 200), ((NimStringDesc*) &TM_ePTWny02hxrh8o3cJG7UaA_8), NIM_NIL));
			(*colonenvP_).colonstate_ = ((NI) 1);
			result = &(*colonenvP_).future2->Sup;
			goto BeforeRet_;
			STATE1: ;
			read_EYgDXwwneJeAEUfXLUHmhg_2((*colonenvP_).future2);
		}
		goto LA4_;
		LA3_: ;
		{
			asgnRef((void**) (&(*colonenvP_).future3), respond_F4lmxjjqUOo55CrHJJWOJw((&(*(*colonenvP_).colonup_).req1), ((NI) 300), ((NimStringDesc*) &TM_ePTWny02hxrh8o3cJG7UaA_9), NIM_NIL));
			(*colonenvP_).colonstate_ = ((NI) 2);
			result = &(*colonenvP_).future3->Sup;
			goto BeforeRet_;
			STATE2: ;
			read_EYgDXwwneJeAEUfXLUHmhg_2((*colonenvP_).future3);
		}
		LA4_: ;
	}
	break;
	case ((tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA) 2):
	{
		if (eqStrings((*(*colonenvP_).colonup_).req1.url.path, ((NimStringDesc*) &TM_ePTWny02hxrh8o3cJG7UaA_10))) goto LA8_;
		goto LA9_;
		LA8_: ;
		{
			tyArray_nFPyKpuH1zPi4VuXhWbFAg T12_;
			NimStringDesc* T13_;
			memset((void*)T12_, 0, sizeof(T12_));
			T12_[0].Field0 = copyString(((NimStringDesc*) &TM_ePTWny02hxrh8o3cJG7UaA_11));
			T12_[0].Field1 = percent__8iXO9aRAijCPe58pujCBbuQ(((NimStringDesc*) &TM_ePTWny02hxrh8o3cJG7UaA_12));
			asgnRefNoCycle((void**) (&(*colonenvP_).json4), percent__9bR9b9aepApwIZEZZtX9cb7RFA(T12_, 1));
			T13_ = (NimStringDesc*)0;
			T13_ = pretty_jL9c59bDERe59bOWSHweWzoBQ((*colonenvP_).json4, ((NI) 2));
			asgnRef((void**) (&(*colonenvP_).future5), respond_F4lmxjjqUOo55CrHJJWOJw((&(*(*colonenvP_).colonup_).req1), ((NI) 200), T13_, NIM_NIL));
			(*colonenvP_).colonstate_ = ((NI) 3);
			result = &(*colonenvP_).future5->Sup;
			goto BeforeRet_;
			STATE3: ;
			read_EYgDXwwneJeAEUfXLUHmhg_2((*colonenvP_).future5);
		}
		goto LA10_;
		LA9_: ;
		{
		}
		LA10_: ;
	}
	break;
	default:
	{
		asgnRef((void**) (&(*colonenvP_).future6), respond_F4lmxjjqUOo55CrHJJWOJw((&(*(*colonenvP_).colonup_).req1), ((NI) 403), ((NimStringDesc*) &TM_ePTWny02hxrh8o3cJG7UaA_13), NIM_NIL));
		(*colonenvP_).colonstate_ = ((NI) 4);
		result = &(*colonenvP_).future6->Sup;
		goto BeforeRet_;
		STATE4: ;
		read_EYgDXwwneJeAEUfXLUHmhg_2((*colonenvP_).future6);
	}
	break;
	}
	complete_mvHczm6KlNpTkVsXGCEbgg((*(*colonenvP_).colonup_).retFuture2);
	(*colonenvP_).colonstate_ = ((NI) -1);
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(NIM_BOOL, finished_lnX3UZC8cmCUb7BzjNqokQasyncnet)(tyProc_3cmVDZYspcmD9a16VGUFJoA x) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	      result = ((NI*) x.ClE_0)[1] < 0;
      
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	result = (Exception*)0;
	result = currException_9bVPeDJlYTi9bQApZpfH8wjg;
	return result;
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException_9bVPeDJlYTi9bQApZpfH8wjg), (*currException_9bVPeDJlYTi9bQApZpfH8wjg).up);
}

N_LIB_PRIVATE N_CLOSURE(void, main_continue_I8OQ7oYoLhO7T5r19cRKPnQ)(void* ClE_0) {
	tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w* colonenvP_;
	TSafePoint TM_ePTWny02hxrh8o3cJG7UaA_14;
	colonenvP_ = (tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w*) ClE_0;
	pushSafePoint(&TM_ePTWny02hxrh8o3cJG7UaA_14);
	TM_ePTWny02hxrh8o3cJG7UaA_14.status = setjmp(TM_ePTWny02hxrh8o3cJG7UaA_14.context);
	if (TM_ePTWny02hxrh8o3cJG7UaA_14.status == 0) {
		{
			NIM_BOOL T4_;
			tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* volatile next;
			T4_ = (NIM_BOOL)0;
			T4_ = finished_lnX3UZC8cmCUb7BzjNqokQasyncnet((*colonenvP_).nameIterVar3);
			if (!!(T4_)) goto LA5_;
			next = (*colonenvP_).nameIterVar3.ClP_0((*colonenvP_).nameIterVar3.ClE_0);
			{
				while (1) {
					NIM_BOOL T9_;
					T9_ = (NIM_BOOL)0;
					T9_ = !((next == 0));
					if (!(T9_)) goto LA10_;
					T9_ = finished_ZDnEFECD9b9aKFsuVLxFyzkA_2(next);
					LA10_: ;
					if (!T9_) goto LA8;
					next = (*colonenvP_).nameIterVar3.ClP_0((*colonenvP_).nameIterVar3.ClE_0);
					{
						NIM_BOOL T13_;
						T13_ = (NIM_BOOL)0;
						T13_ = finished_lnX3UZC8cmCUb7BzjNqokQasyncnet((*colonenvP_).nameIterVar3);
						if (!T13_) goto LA14_;
						goto LA7;
					}
					LA14_: ;
				} LA8: ;
			} LA7: ;
			{
				if (!(next == NIM_NIL)) goto LA18_;
				{
					NIM_BOOL T22_;
					NimStringDesc* msg;
					tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA* volatile e;
					T22_ = (NIM_BOOL)0;
					T22_ = finished_jn4eVK3zFIl4kShRnlTsCg((*colonenvP_).retFuture2);
					if (!!(T22_)) goto LA23_;
					msg = copyString(((NimStringDesc*) &TM_ePTWny02hxrh8o3cJG7UaA_17));
					e = (tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA*)0;
					e = (tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA*) newObj((&NTI_TmgWlPUbRr7iGD2UE1cu6A_), sizeof(tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA));
					(*e).Sup.Sup.m_type = (&NTI_8FC9arcap3s5ZtfMs75krtA_);
					asgnRefNoCycle((void**) (&(*e).Sup.message), nsuFormatSingleElem(msg, ((NimStringDesc*) &TM_ePTWny02hxrh8o3cJG7UaA_5)));
					asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
					raiseException((Exception*)e, "AssertionError");
				}
				LA23_: ;
			}
			goto LA16_;
			LA18_: ;
			{
				tyProc_IIomJ6ptE6vfJ5zRbATgkQ T26_;
				memset((void*)(&T26_), 0, sizeof(T26_));
				T26_.ClP_0 = main_continue_I8OQ7oYoLhO7T5r19cRKPnQ; T26_.ClE_0 = colonenvP_;
				callbackeq__9c5z7ouO5bUylgKxaZoIuVg(next, T26_);
			}
			LA16_: ;
		}
		LA5_: ;
		popSafePoint();
	}
	else {
		popSafePoint();
		{
			TM_ePTWny02hxrh8o3cJG7UaA_14.status = 0;
			{
				NIM_BOOL T31_;
				T31_ = (NIM_BOOL)0;
				T31_ = finished_jn4eVK3zFIl4kShRnlTsCg((*colonenvP_).retFuture2);
				if (!T31_) goto LA32_;
				reraiseException();
			}
			goto LA29_;
			LA32_: ;
			{
				Exception* T35_;
				T35_ = (Exception*)0;
				T35_ = getCurrentException();
				fail_8buDkIPh9aRg7WBcB15eisA((*colonenvP_).retFuture2, T35_);
			}
			LA29_: ;
			popCurrentException();
		}
	}
	if (TM_ePTWny02hxrh8o3cJG7UaA_14.status != 0) reraiseException();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, main_j7F9b9aLZwXb4IG63WlqFcgQ)(tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ* req) {
	tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* result;
	tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w* colonenv_;
	tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg* colonenv__2;
	tyProc_3cmVDZYspcmD9a16VGUFJoA T1_;
	tyProc_IIomJ6ptE6vfJ5zRbATgkQ T2_;
{	result = (tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*)0;
	colonenv_ = (tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w*)0;
	colonenv_ = (tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w*) newObj((&NTI_UKvDH8c5AgJpuQy1KoUugg_), sizeof(tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w));
	(*colonenv_).Sup.m_type = (&NTI_v1MfaYlSBTTzwzfB0NW14w_);
	genericAssign((void*)(&(*colonenv_).req1), (void*)req, (&NTI_1Wfxxtqzahm0R6lueM9aQmQ_));
	asgnRef((void**) (&(*colonenv_).retFuture2), newFuture_1afITAy9cOOiZDRZUZbFt0w(((NimStringDesc*) &TM_ePTWny02hxrh8o3cJG7UaA_5)));
	colonenv__2 = (tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg*)0;
	colonenv__2 = (tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg*) newObj((&NTI_rfDuZwtXENcc9ahTQY9bFxAQ_), sizeof(tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg));
	(*colonenv__2).Sup.m_type = (&NTI_lADKcJjPcIxxRUyWT3Tvgg_);
	asgnRef((void**) (&(*colonenv__2).colonup_), colonenv_);
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.ClP_0 = mainIter_ndmONCqrNN0ArfCRFmWSSA; T1_.ClE_0 = colonenv__2;
	asgnRef((void**) (&(*colonenv_).nameIterVar3.ClE_0), T1_.ClE_0);
	(*colonenv_).nameIterVar3.ClP_0 = T1_.ClP_0;
	memset((void*)(&T2_), 0, sizeof(T2_));
	T2_.ClP_0 = main_continue_I8OQ7oYoLhO7T5r19cRKPnQ; T2_.ClE_0 = colonenv_;
	T2_.ClE_0? T2_.ClP_0(T2_.ClE_0):((TM_ePTWny02hxrh8o3cJG7UaA_18)(T2_.ClP_0))();
	result = (*colonenv_).retFuture2;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_heapqueueDatInit000();
	stdlib_listsDatInit000();
	stdlib_typetraitsDatInit000();
	stdlib_optionsDatInit000();
	stdlib_dequesDatInit000();
	stdlib_cstrutilsDatInit000();
	stdlib_asyncfuturesDatInit000();
	stdlib_asyncstreamsDatInit000();
	stdlib_nativesocketsDatInit000();
	stdlib_setsDatInit000();
	stdlib_dynlibDatInit000();
	stdlib_opensslDatInit000();
	stdlib_netDatInit000();
	stdlib_epollDatInit000();
	stdlib_selectorsDatInit000();
	stdlib_macrosDatInit000();
	stdlib_asyncdispatchDatInit000();
	stdlib_asyncnetDatInit000();
	stdlib_uriDatInit000();
	stdlib_httpcoreDatInit000();
	stdlib_asynchttpserverDatInit000();
	stdlib_streamsDatInit000();
	stdlib_lexbaseDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_jsonDatInit000();
	stdlib_strtabsDatInit000();
	stdlib_linuxDatInit000();
	stdlib_cpuinfoDatInit000();
	stdlib_osprocDatInit000();
	stdlib_browsersDatInit000();
	confDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_heapqueueInit000();
	stdlib_listsInit000();
	stdlib_typetraitsInit000();
	stdlib_optionsInit000();
	stdlib_dequesInit000();
	stdlib_cstrutilsInit000();
	stdlib_asyncfuturesInit000();
	stdlib_asyncstreamsInit000();
	stdlib_nativesocketsInit000();
	stdlib_setsInit000();
	stdlib_dynlibInit000();
	stdlib_opensslInit000();
	stdlib_netInit000();
	stdlib_epollInit000();
	stdlib_selectorsInit000();
	stdlib_macrosInit000();
	stdlib_asyncdispatchInit000();
	stdlib_asyncnetInit000();
	stdlib_uriInit000();
	stdlib_httpcoreInit000();
	stdlib_asynchttpserverInit000();
	stdlib_streamsInit000();
	stdlib_lexbaseInit000();
	stdlib_unicodeInit000();
	stdlib_jsonInit000();
	stdlib_strtabsInit000();
	stdlib_linuxInit000();
	stdlib_cpuinfoInit000();
	stdlib_osprocInit000();
	stdlib_browsersInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyProc_9cYHoVsKEcSHuZkNJna2Tvg T1_;
	tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* T2_;
nimRegisterGlobalMarker(TM_ePTWny02hxrh8o3cJG7UaA_2);
	asgnRef((void**) (&server_9acamu2ghB6gPWVei3kcE9bA), newAsyncHttpServer_8E3hcKWR9bMseKjk69aa6Aqw(NIM_TRUE, NIM_FALSE, ((NI) 8388608)));
	openDefaultBrowser_PpG1KNVRhDoDXOHUl4nBBA(((NimStringDesc*) &TM_ePTWny02hxrh8o3cJG7UaA_3));
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.ClP_0 = ((TM_ePTWny02hxrh8o3cJG7UaA_19) (main_j7F9b9aLZwXb4IG63WlqFcgQ)); T1_.ClE_0 = NIM_NIL;
	T2_ = (tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*)0;
	T2_ = serve_4qUYuAmkUBQy1ChRq42g5Q(server_9acamu2ghB6gPWVei3kcE9bA, ((NU16) 4242), T1_, ((NimStringDesc*) &TM_ePTWny02hxrh8o3cJG7UaA_20));
	waitFor_VIKMhEBTNLqEA2ZGnacjrw(T2_);
}

NIM_EXTERNC N_NOINLINE(void, confDatInit000)(void) {
static TNimNode* TM_ePTWny02hxrh8o3cJG7UaA_4[4];
static TNimNode* TM_ePTWny02hxrh8o3cJG7UaA_6[7];
static TNimNode TM_ePTWny02hxrh8o3cJG7UaA_0[13];
NTI_v1MfaYlSBTTzwzfB0NW14w_.size = sizeof(tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w);
NTI_v1MfaYlSBTTzwzfB0NW14w_.kind = 17;
NTI_v1MfaYlSBTTzwzfB0NW14w_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_ePTWny02hxrh8o3cJG7UaA_4[0] = &TM_ePTWny02hxrh8o3cJG7UaA_0[1];
TM_ePTWny02hxrh8o3cJG7UaA_0[1].kind = 1;
TM_ePTWny02hxrh8o3cJG7UaA_0[1].offset = offsetof(tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w, colonstate_);
TM_ePTWny02hxrh8o3cJG7UaA_0[1].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ_);
TM_ePTWny02hxrh8o3cJG7UaA_0[1].name = ":state";
TM_ePTWny02hxrh8o3cJG7UaA_4[1] = &TM_ePTWny02hxrh8o3cJG7UaA_0[2];
TM_ePTWny02hxrh8o3cJG7UaA_0[2].kind = 1;
TM_ePTWny02hxrh8o3cJG7UaA_0[2].offset = offsetof(tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w, req1);
TM_ePTWny02hxrh8o3cJG7UaA_0[2].typ = (&NTI_1Wfxxtqzahm0R6lueM9aQmQ_);
TM_ePTWny02hxrh8o3cJG7UaA_0[2].name = "req1";
TM_ePTWny02hxrh8o3cJG7UaA_4[2] = &TM_ePTWny02hxrh8o3cJG7UaA_0[3];
TM_ePTWny02hxrh8o3cJG7UaA_0[3].kind = 1;
TM_ePTWny02hxrh8o3cJG7UaA_0[3].offset = offsetof(tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w, retFuture2);
TM_ePTWny02hxrh8o3cJG7UaA_0[3].typ = (&NTI_zXD0JrbeCNyAaW4E6fB9aqg_);
TM_ePTWny02hxrh8o3cJG7UaA_0[3].name = "retFuture2";
TM_ePTWny02hxrh8o3cJG7UaA_4[3] = &TM_ePTWny02hxrh8o3cJG7UaA_0[4];
TM_ePTWny02hxrh8o3cJG7UaA_0[4].kind = 1;
TM_ePTWny02hxrh8o3cJG7UaA_0[4].offset = offsetof(tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w, nameIterVar3);
TM_ePTWny02hxrh8o3cJG7UaA_0[4].typ = (&NTI_3cmVDZYspcmD9a16VGUFJoA_);
TM_ePTWny02hxrh8o3cJG7UaA_0[4].name = "nameIterVar3";
TM_ePTWny02hxrh8o3cJG7UaA_0[0].len = 4; TM_ePTWny02hxrh8o3cJG7UaA_0[0].kind = 2; TM_ePTWny02hxrh8o3cJG7UaA_0[0].sons = &TM_ePTWny02hxrh8o3cJG7UaA_4[0];
NTI_v1MfaYlSBTTzwzfB0NW14w_.node = &TM_ePTWny02hxrh8o3cJG7UaA_0[0];
NTI_UKvDH8c5AgJpuQy1KoUugg_.size = sizeof(tyObject_Env_confdotnim__v1MfaYlSBTTzwzfB0NW14w*);
NTI_UKvDH8c5AgJpuQy1KoUugg_.kind = 22;
NTI_UKvDH8c5AgJpuQy1KoUugg_.base = (&NTI_v1MfaYlSBTTzwzfB0NW14w_);
NTI_UKvDH8c5AgJpuQy1KoUugg_.marker = Marker_tyRef_UKvDH8c5AgJpuQy1KoUugg;
NTI_lADKcJjPcIxxRUyWT3Tvgg_.size = sizeof(tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg);
NTI_lADKcJjPcIxxRUyWT3Tvgg_.kind = 17;
NTI_lADKcJjPcIxxRUyWT3Tvgg_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_ePTWny02hxrh8o3cJG7UaA_6[0] = &TM_ePTWny02hxrh8o3cJG7UaA_0[6];
TM_ePTWny02hxrh8o3cJG7UaA_0[6].kind = 1;
TM_ePTWny02hxrh8o3cJG7UaA_0[6].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg, colonstate_);
TM_ePTWny02hxrh8o3cJG7UaA_0[6].typ = (&NTI_P6gYL22cCr5PoMFeuBNXwA_);
TM_ePTWny02hxrh8o3cJG7UaA_0[6].name = ":state";
TM_ePTWny02hxrh8o3cJG7UaA_6[1] = &TM_ePTWny02hxrh8o3cJG7UaA_0[7];
TM_ePTWny02hxrh8o3cJG7UaA_0[7].kind = 1;
TM_ePTWny02hxrh8o3cJG7UaA_0[7].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg, colonup_);
TM_ePTWny02hxrh8o3cJG7UaA_0[7].typ = (&NTI_UKvDH8c5AgJpuQy1KoUugg_);
TM_ePTWny02hxrh8o3cJG7UaA_0[7].name = ":up";
TM_ePTWny02hxrh8o3cJG7UaA_6[2] = &TM_ePTWny02hxrh8o3cJG7UaA_0[8];
TM_ePTWny02hxrh8o3cJG7UaA_0[8].kind = 1;
TM_ePTWny02hxrh8o3cJG7UaA_0[8].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg, future2);
TM_ePTWny02hxrh8o3cJG7UaA_0[8].typ = (&NTI_zXD0JrbeCNyAaW4E6fB9aqg_);
TM_ePTWny02hxrh8o3cJG7UaA_0[8].name = "future2";
TM_ePTWny02hxrh8o3cJG7UaA_6[3] = &TM_ePTWny02hxrh8o3cJG7UaA_0[9];
TM_ePTWny02hxrh8o3cJG7UaA_0[9].kind = 1;
TM_ePTWny02hxrh8o3cJG7UaA_0[9].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg, future3);
TM_ePTWny02hxrh8o3cJG7UaA_0[9].typ = (&NTI_zXD0JrbeCNyAaW4E6fB9aqg_);
TM_ePTWny02hxrh8o3cJG7UaA_0[9].name = "future3";
TM_ePTWny02hxrh8o3cJG7UaA_6[4] = &TM_ePTWny02hxrh8o3cJG7UaA_0[10];
TM_ePTWny02hxrh8o3cJG7UaA_0[10].kind = 1;
TM_ePTWny02hxrh8o3cJG7UaA_0[10].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg, json4);
TM_ePTWny02hxrh8o3cJG7UaA_0[10].typ = (&NTI_zfzzuQ8txrdZAYK0WGWpHg_);
TM_ePTWny02hxrh8o3cJG7UaA_0[10].name = "json4";
TM_ePTWny02hxrh8o3cJG7UaA_6[5] = &TM_ePTWny02hxrh8o3cJG7UaA_0[11];
TM_ePTWny02hxrh8o3cJG7UaA_0[11].kind = 1;
TM_ePTWny02hxrh8o3cJG7UaA_0[11].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg, future5);
TM_ePTWny02hxrh8o3cJG7UaA_0[11].typ = (&NTI_zXD0JrbeCNyAaW4E6fB9aqg_);
TM_ePTWny02hxrh8o3cJG7UaA_0[11].name = "future5";
TM_ePTWny02hxrh8o3cJG7UaA_6[6] = &TM_ePTWny02hxrh8o3cJG7UaA_0[12];
TM_ePTWny02hxrh8o3cJG7UaA_0[12].kind = 1;
TM_ePTWny02hxrh8o3cJG7UaA_0[12].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg, future6);
TM_ePTWny02hxrh8o3cJG7UaA_0[12].typ = (&NTI_zXD0JrbeCNyAaW4E6fB9aqg_);
TM_ePTWny02hxrh8o3cJG7UaA_0[12].name = "future6";
TM_ePTWny02hxrh8o3cJG7UaA_0[5].len = 7; TM_ePTWny02hxrh8o3cJG7UaA_0[5].kind = 2; TM_ePTWny02hxrh8o3cJG7UaA_0[5].sons = &TM_ePTWny02hxrh8o3cJG7UaA_6[0];
NTI_lADKcJjPcIxxRUyWT3Tvgg_.node = &TM_ePTWny02hxrh8o3cJG7UaA_0[5];
NTI_rfDuZwtXENcc9ahTQY9bFxAQ_.size = sizeof(tyObject_Env_libslashpureslashasyncmacrodotnim__lADKcJjPcIxxRUyWT3Tvgg*);
NTI_rfDuZwtXENcc9ahTQY9bFxAQ_.kind = 22;
NTI_rfDuZwtXENcc9ahTQY9bFxAQ_.base = (&NTI_lADKcJjPcIxxRUyWT3Tvgg_);
NTI_rfDuZwtXENcc9ahTQY9bFxAQ_.marker = Marker_tyRef_rfDuZwtXENcc9ahTQY9bFxAQ;
}

