/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c -w -O3 -fno-strict-aliasing  -I/home/kuro/.choosenim/toolchains/nim-0.18.0/lib -o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_httpcore.o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_httpcore.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA;
typedef struct tyObject_Table_LLQadDAXEvd71UDdEc3lDA tyObject_Table_LLQadDAXEvd71UDdEc3lDA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple_wOvXi5VibnCNgN9buQRQD4A tyTuple_wOvXi5VibnCNgN9buQRQD4A;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyTuple_kN8up2W6YKc5YA9avn5mV5w tyTuple_kN8up2W6YKc5YA9avn5mV5w;
typedef struct tySequence_JiteSJxrvz63iP2o9bcn2Sg tySequence_JiteSJxrvz63iP2o9bcn2Sg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyTuple_g1w83cyyBYiVU9c8WEJWnjQ tyTuple_g1w83cyyBYiVU9c8WEJWnjQ;
typedef NU8 tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA {
tyObject_Table_LLQadDAXEvd71UDdEc3lDA* table;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_wOvXi5VibnCNgN9buQRQD4A {
NimStringDesc* Field0;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* Field1;
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
struct tyTuple_kN8up2W6YKc5YA9avn5mV5w {
NimStringDesc* Field0;
NI Field1;
NI Field2;
};
typedef NU8 tyEnum_HttpVersion_QPubEzrnvJXtiz9alIdNQeA;
struct tyObject_Table_LLQadDAXEvd71UDdEc3lDA {
tySequence_JiteSJxrvz63iP2o9bcn2Sg* data;
NI counter;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyTuple_g1w83cyyBYiVU9c8WEJWnjQ {
NI Field0;
NimStringDesc* Field1;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* Field2;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_JiteSJxrvz63iP2o9bcn2Sg {
  TGenericSeq Sup;
  tyTuple_g1w83cyyBYiVU9c8WEJWnjQ data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_FbZeO4trJhT2CCJ9aLxejqw)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table_LLQadDAXEvd71UDdEc3lDA*, newTable_CI6CAcgU9cmDZWyfVHj8z4g)(NI initialSize);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, clear_axjU83goYo2deNG5N5zCTA)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NI, parseUntil_NGJAHkdW7mFJbCRar9a8aQwhttpcore)(NimStringDesc* s, NimStringDesc** token, NIM_CHAR until, NI start);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_LIB_PRIVATE N_NIMCALL(NI, parseList_ezobL19b9cekPtKoupwBaGvA)(NimStringDesc* line, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** list, NI start);
static N_INLINE(NI, skipWhitespace_eRDxv9ah1K9c5mDt1GmbdF9aghttpcore)(NimStringDesc* s, NI start);
static N_INLINE(NI, parseUntil_zSglkPmqQkVaLkVSiDuiCguri)(NimStringDesc* s, NimStringDesc** token, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw until, NI start);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__Hk6a82dIBZqReb79aiZ9czeQ)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, NimStringDesc* key, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* val);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuToLowerAsciiStr)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NI, len_gPutmFMjF2dpNdfOqcokuQ)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_dVPEHWNM9ac65s5ksvHbOhg)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, NimStringDesc* key);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQasyncnet)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ**, X5BX5D__Q3d9cok5U8i0JCsF7VnnIJw)(tyObject_Table_LLQadDAXEvd71UDdEc3lDA* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_T0KkqFbqlm8065Ws4h4NSg)(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, X5BX5D__2I7W00Lgs3jqrdJTli4b9cA)(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers, NimStringDesc* key);
TNimType NTI_wfZHspwVKQPl9aWhkIcMrAA_;
TNimType NTI_GM611pWlOrQ7hvMPcuAACA_;
extern TNimType NTI_Exo1CrLCLUIZQ4IUZ9aXEGg_;
TNimType NTI_FbZeO4trJhT2CCJ9aLxejqw_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_wOvXi5VibnCNgN9buQRQD4A_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_5, "100 Continue", 12);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_6, "101 Switching Protocols", 23);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_7, "200 OK", 6);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_8, "201 Created", 11);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_9, "202 Accepted", 12);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_10, "203 Non-Authoritative Information", 33);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_11, "204 No Content", 14);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_12, "205 Reset Content", 17);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_13, "206 Partial Content", 19);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_14, "300 Multiple Choices", 20);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_15, "301 Moved Permanently", 21);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_16, "302 Found", 9);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_17, "303 See Other", 13);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_18, "304 Not Modified", 16);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_19, "305 Use Proxy", 13);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_20, "307 Temporary Redirect", 22);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_21, "400 Bad Request", 15);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_22, "401 Unauthorized", 16);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_23, "403 Forbidden", 13);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_24, "404 Not Found", 13);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_25, "405 Method Not Allowed", 22);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_26, "406 Not Acceptable", 18);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_27, "407 Proxy Authentication Required", 33);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_28, "408 Request Timeout", 19);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_29, "409 Conflict", 12);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_30, "410 Gone", 8);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_31, "411 Length Required", 19);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_32, "412 Precondition Failed", 23);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_33, "413 Request Entity Too Large", 28);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_34, "414 Request-URI Too Long", 24);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_35, "415 Unsupported Media Type", 26);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_36, "416 Requested Range Not Satisfiable", 35);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_37, "417 Expectation Failed", 22);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_38, "418 I\'m a teapot", 16);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_39, "421 Misdirected Request", 23);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_40, "422 Unprocessable Entity", 24);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_41, "426 Upgrade Required", 20);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_42, "428 Precondition Required", 25);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_43, "429 Too Many Requests", 21);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_44, "431 Request Header Fields Too Large", 35);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_45, "451 Unavailable For Legal Reasons", 33);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_46, "500 Internal Server Error", 25);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_47, "501 Not Implemented", 19);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_48, "502 Bad Gateway", 15);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_49, "503 Service Unavailable", 23);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_50, "504 Gateway Timeout", 19);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_51, "505 HTTP Version Not Supported", 30);
STRING_LITERAL(TM_Evu9b2R1utZubyCikahWx1g_53, "", 0);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_Evu9b2R1utZubyCikahWx1g_54 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[1];
} TM_Evu9b2R1utZubyCikahWx1g_56 = {{1, 1}, {((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_53)}};
NIM_CONST tySequence_sM4lkSb7zS6F7OVMvW9cffQ* TM_Evu9b2R1utZubyCikahWx1g_55 = ((tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)&TM_Evu9b2R1utZubyCikahWx1g_56);
static N_NIMCALL(void, Marker_tyRef_FbZeO4trJhT2CCJ9aLxejqw)(void* p, NI op) {
	tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* a;
	a = (tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA*)p;
	nimGCvisit((void*)(*a).table, op);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		if (!!((src == NIM_NIL))) goto LA3_;
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA*, newHttpHeaders_6szM8dtom9bIqki4DkcPGmg)(void) {
	tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* result;
	result = (tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA*)0;
	result = (tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA*) newObj((&NTI_FbZeO4trJhT2CCJ9aLxejqw_), sizeof(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA));
	asgnRefNoCycle((void**) (&(*result).table), newTable_CI6CAcgU9cmDZWyfVHj8z4g(((NI) 64)));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, clear_OorRT6sittWQ6hHggIcv7A)(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers) {
	clear_axjU83goYo2deNG5N5zCTA((*headers).table);
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__9cVsFvz7mEtKMww1u8rPboA)(NI code) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	switch (((NI) (code))) {
	case ((NI) 100):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_5));
	}
	break;
	case ((NI) 101):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_6));
	}
	break;
	case ((NI) 200):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_7));
	}
	break;
	case ((NI) 201):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_8));
	}
	break;
	case ((NI) 202):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_9));
	}
	break;
	case ((NI) 203):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_10));
	}
	break;
	case ((NI) 204):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_11));
	}
	break;
	case ((NI) 205):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_12));
	}
	break;
	case ((NI) 206):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_13));
	}
	break;
	case ((NI) 300):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_14));
	}
	break;
	case ((NI) 301):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_15));
	}
	break;
	case ((NI) 302):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_16));
	}
	break;
	case ((NI) 303):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_17));
	}
	break;
	case ((NI) 304):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_18));
	}
	break;
	case ((NI) 305):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_19));
	}
	break;
	case ((NI) 307):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_20));
	}
	break;
	case ((NI) 400):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_21));
	}
	break;
	case ((NI) 401):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_22));
	}
	break;
	case ((NI) 403):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_23));
	}
	break;
	case ((NI) 404):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_24));
	}
	break;
	case ((NI) 405):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_25));
	}
	break;
	case ((NI) 406):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_26));
	}
	break;
	case ((NI) 407):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_27));
	}
	break;
	case ((NI) 408):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_28));
	}
	break;
	case ((NI) 409):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_29));
	}
	break;
	case ((NI) 410):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_30));
	}
	break;
	case ((NI) 411):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_31));
	}
	break;
	case ((NI) 412):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_32));
	}
	break;
	case ((NI) 413):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_33));
	}
	break;
	case ((NI) 414):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_34));
	}
	break;
	case ((NI) 415):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_35));
	}
	break;
	case ((NI) 416):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_36));
	}
	break;
	case ((NI) 417):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_37));
	}
	break;
	case ((NI) 418):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_38));
	}
	break;
	case ((NI) 421):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_39));
	}
	break;
	case ((NI) 422):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_40));
	}
	break;
	case ((NI) 426):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_41));
	}
	break;
	case ((NI) 428):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_42));
	}
	break;
	case ((NI) 429):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_43));
	}
	break;
	case ((NI) 431):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_44));
	}
	break;
	case ((NI) 451):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_45));
	}
	break;
	case ((NI) 500):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_46));
	}
	break;
	case ((NI) 501):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_47));
	}
	break;
	case ((NI) 502):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_48));
	}
	break;
	case ((NI) 503):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_49));
	}
	break;
	case ((NI) 504):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_50));
	}
	break;
	case ((NI) 505):
	{
		result = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_51));
	}
	break;
	default:
	{
		result = nimIntToStr(((NI) (code)));
	}
	break;
	}
	return result;
}

static N_INLINE(NI, parseUntil_NGJAHkdW7mFJbCRar9a8aQwhttpcore)(NimStringDesc* s, NimStringDesc** token, NIM_CHAR until, NI start) {
	NI result;
	NI i;
	result = (NI)0;
	i = start;
	{
		while (1) {
			NIM_BOOL T3_;
			T3_ = (NIM_BOOL)0;
			T3_ = (i < (s ? s->Sup.len : 0));
			if (!(T3_)) goto LA4_;
			T3_ = !(((NU8)(s->data[i]) == (NU8)(until)));
			LA4_: ;
			if (!T3_) goto LA2;
			i += ((NI) 1);
		} LA2: ;
	}
	result = (NI)(i - start);
	unsureAsgnRef((void**) (&(*token)), copyStrLast(s, start, (NI)(i - ((NI) 1))));
	return result;
}

static N_INLINE(NI, skipWhitespace_eRDxv9ah1K9c5mDt1GmbdF9aghttpcore)(NimStringDesc* s, NI start) {
	NI result;
	result = (NI)0;
	{
		while (1) {
			if (!(((NU8)(s->data[(NI)(start + result)])) == ((NU8)(32)) || ((NU8)(s->data[(NI)(start + result)])) == ((NU8)(9)) || ((NU8)(s->data[(NI)(start + result)])) == ((NU8)(11)) || ((NU8)(s->data[(NI)(start + result)])) == ((NU8)(13)) || ((NU8)(s->data[(NI)(start + result)])) == ((NU8)(10)) || ((NU8)(s->data[(NI)(start + result)])) == ((NU8)(12)))) goto LA2;
			result += ((NI) 1);
		} LA2: ;
	}
	return result;
}

static N_INLINE(NI, parseUntil_zSglkPmqQkVaLkVSiDuiCguri)(NimStringDesc* s, NimStringDesc** token, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw until, NI start) {
	NI result;
	NI i;
	result = (NI)0;
	i = start;
	{
		while (1) {
			NIM_BOOL T3_;
			T3_ = (NIM_BOOL)0;
			T3_ = (i < (s ? s->Sup.len : 0));
			if (!(T3_)) goto LA4_;
			T3_ = !(((until[(NU)(((NU8)(s->data[i])))>>3] &(1U<<((NU)(((NU8)(s->data[i])))&7U)))!=0));
			LA4_: ;
			if (!T3_) goto LA2;
			i += ((NI) 1);
		} LA2: ;
	}
	result = (NI)(i - start);
	unsureAsgnRef((void**) (&(*token)), copyStrLast(s, start, (NI)(i - ((NI) 1))));
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(NI, parseList_ezobL19b9cekPtKoupwBaGvA)(NimStringDesc* line, tySequence_sM4lkSb7zS6F7OVMvW9cffQ** list, NI start) {
	NI result;
	NI i;
	NimStringDesc* current;
	result = (NI)0;
	i = ((NI) 0);
	current = copyString(((NimStringDesc*) &TM_Evu9b2R1utZubyCikahWx1g_53));
	{
		while (1) {
			NI T3_;
			NI T4_;
			NI T5_;
			NimStringDesc* T6_;
			if (!!((((NU8)(line->data[(NI)(start + i)])) == ((NU8)(13)) || ((NU8)(line->data[(NI)(start + i)])) == ((NU8)(10)) || ((NU8)(line->data[(NI)(start + i)])) == ((NU8)(0))))) goto LA2;
			T3_ = (NI)0;
			T3_ = skipWhitespace_eRDxv9ah1K9c5mDt1GmbdF9aghttpcore(line, (NI)(start + i));
			i += T3_;
			T4_ = (NI)0;
			T4_ = parseUntil_zSglkPmqQkVaLkVSiDuiCguri(line, (&current), TM_Evu9b2R1utZubyCikahWx1g_54, (NI)(start + i));
			i += T4_;
			(*list) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*list))->Sup, sizeof(NimStringDesc*));
			T5_ = (*list)->Sup.len++;
			T6_ = (NimStringDesc*)0;
			T6_ = (*list)->data[T5_]; (*list)->data[T5_] = copyStringRC1(current);
			if (T6_) nimGCunrefNoCycle(T6_);
			{
				if (!((NU8)(line->data[(NI)(start + i)]) == (NU8)(44))) goto LA9_;
				i += ((NI) 1);
			}
			LA9_: ;
			current = setLengthStr(current, ((NI) 0));
		} LA2: ;
	}
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, parseHeader_dvVA44pq54kR8iSXiF0Nzw)(NimStringDesc* line, tyTuple_wOvXi5VibnCNgN9buQRQD4A* Result) {
	NI i;
	genericReset((void*)Result, (&NTI_wOvXi5VibnCNgN9buQRQD4A_));
	unsureAsgnRef((void**) (&(*Result).Field1), (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0));
	i = ((NI) 0);
	i = parseUntil_NGJAHkdW7mFJbCRar9a8aQwhttpcore(line, (&(*Result).Field0), 58, ((NI) 0));
	i += ((NI) 1);
	{
		NI T5_;
		if (!(i < (line ? line->Sup.len : 0))) goto LA3_;
		T5_ = (NI)0;
		T5_ = parseList_ezobL19b9cekPtKoupwBaGvA(line, (&(*Result).Field1), i);
		i += T5_;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(((NI) 0) < ((*Result).Field0 ? (*Result).Field0->Sup.len : 0))) goto LA7_;
		genericSeqAssign((&(*Result).Field1), TM_Evu9b2R1utZubyCikahWx1g_55, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
	}
	goto LA1_;
	LA7_: ;
	{
		unsureAsgnRef((void**) (&(*Result).Field1), (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0));
	}
	LA1_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__TqzBU8hdRGHa9aQu0RrPqCw)(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers, NimStringDesc* key, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* value) {
	NimStringDesc* T1_;
	T1_ = (NimStringDesc*)0;
	T1_ = nsuToLowerAsciiStr(key);
	X5BX5Deq__Hk6a82dIBZqReb79aiZ9czeQ((*headers).table, T1_, value);
}

N_LIB_PRIVATE N_NIMCALL(NI, len_KJLsaxEBMwC7Zow21T6yQA)(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers) {
	NI result;
{	result = (NI)0;
	result = len_gPutmFMjF2dpNdfOqcokuQ((*headers).table);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_T0KkqFbqlm8065Ws4h4NSg)(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers, NimStringDesc* key) {
	NIM_BOOL result;
	NimStringDesc* T1_;
{	result = (NIM_BOOL)0;
	T1_ = (NimStringDesc*)0;
	T1_ = nsuToLowerAsciiStr(key);
	result = hasKey_dVPEHWNM9ac65s5ksvHbOhg((*headers).table, T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQasyncnet)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQasyncnet(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_oFJPRbcAHZLz4RVXeZruJw)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* values, NimStringDesc* value) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		NimStringDesc* val;
		tySequence_sM4lkSb7zS6F7OVMvW9cffQ* colontmp_;
		NI i;
		NI L;
		NI T2_;
		val = (NimStringDesc*)0;
		colontmp_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
		colontmp_ = values;
		i = ((NI) 0);
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			while (1) {
				if (!(i < L)) goto LA4;
				val = colontmp_->data[i];
				{
					NimStringDesc* T7_;
					NimStringDesc* T8_;
					T7_ = (NimStringDesc*)0;
					T7_ = nsuToLowerAsciiStr(val);
					T8_ = (NimStringDesc*)0;
					T8_ = nsuToLowerAsciiStr(value);
					if (!eqStrings(T7_, T8_)) goto LA9_;
					result = NIM_TRUE;
					goto BeforeRet_;
				}
				LA9_: ;
				i += ((NI) 1);
			} LA4: ;
		}
	}
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, X5BX5D__2I7W00Lgs3jqrdJTli4b9cA)(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers, NimStringDesc* key) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* result;
	NimStringDesc* T1_;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ** T2_;
{	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T1_ = (NimStringDesc*)0;
	T1_ = nsuToLowerAsciiStr(key);
	T2_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ**)0;
	T2_ = X5BX5D__Q3d9cok5U8i0JCsF7VnnIJw((*headers).table, T1_);
	genericSeqAssign((&result), (*T2_), (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, toString_lBEoN6A9bKNublZsSxuhYeA)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* values) {
	NimStringDesc* result;
{	result = (NimStringDesc*)0;
	result = copyString(values->data[((NI) 0)]);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, getOrDefault_iYU3axHYDC9bL2abC1Ss5fw)(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers, NimStringDesc* key, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* default_0) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* result;
{	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = hasKey_T0KkqFbqlm8065Ws4h4NSg(headers, key);
		if (!T3_) goto LA4_;
		result = X5BX5D__2I7W00Lgs3jqrdJTli4b9cA(headers, key);
		goto BeforeRet_;
	}
	goto LA1_;
	LA4_: ;
	{
		genericSeqAssign((&result), default_0, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__UuvD8G9cNX019aF41qsh5CHQ)(tyTuple_kN8up2W6YKc5YA9avn5mV5w protocol, tyEnum_HttpVersion_QPubEzrnvJXtiz9alIdNQeA ver) {
	NIM_BOOL result;
	NI major;
	NI minor;
	NIM_BOOL T4_;
	result = (NIM_BOOL)0;
	switch (ver) {
	case ((tyEnum_HttpVersion_QPubEzrnvJXtiz9alIdNQeA) 0):
	case ((tyEnum_HttpVersion_QPubEzrnvJXtiz9alIdNQeA) 1):
	{
		major = ((NI) 1);
	}
	break;
	}
	switch (ver) {
	case ((tyEnum_HttpVersion_QPubEzrnvJXtiz9alIdNQeA) 0):
	{
		minor = ((NI) 1);
	}
	break;
	case ((tyEnum_HttpVersion_QPubEzrnvJXtiz9alIdNQeA) 1):
	{
		minor = ((NI) 0);
	}
	break;
	}
	T4_ = (NIM_BOOL)0;
	T4_ = (protocol.Field1 == major);
	if (!(T4_)) goto LA5_;
	T4_ = (protocol.Field2 == minor);
	LA5_: ;
	result = T4_;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_httpcoreInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_httpcoreDatInit000)(void) {
static TNimNode* TM_Evu9b2R1utZubyCikahWx1g_2[9];
NI TM_Evu9b2R1utZubyCikahWx1g_4;
static char* NIM_CONST TM_Evu9b2R1utZubyCikahWx1g_3[9] = {
"HttpHead", 
"HttpGet", 
"HttpPost", 
"HttpPut", 
"HttpDelete", 
"HttpTrace", 
"HttpOptions", 
"HttpConnect", 
"HttpPatch"};
static TNimNode* TM_Evu9b2R1utZubyCikahWx1g_52[2];
static TNimNode TM_Evu9b2R1utZubyCikahWx1g_0[14];
NTI_wfZHspwVKQPl9aWhkIcMrAA_.size = sizeof(tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA);
NTI_wfZHspwVKQPl9aWhkIcMrAA_.kind = 14;
NTI_wfZHspwVKQPl9aWhkIcMrAA_.base = 0;
NTI_wfZHspwVKQPl9aWhkIcMrAA_.flags = 3;
for (TM_Evu9b2R1utZubyCikahWx1g_4 = 0; TM_Evu9b2R1utZubyCikahWx1g_4 < 9; TM_Evu9b2R1utZubyCikahWx1g_4++) {
TM_Evu9b2R1utZubyCikahWx1g_0[TM_Evu9b2R1utZubyCikahWx1g_4+0].kind = 1;
TM_Evu9b2R1utZubyCikahWx1g_0[TM_Evu9b2R1utZubyCikahWx1g_4+0].offset = TM_Evu9b2R1utZubyCikahWx1g_4;
TM_Evu9b2R1utZubyCikahWx1g_0[TM_Evu9b2R1utZubyCikahWx1g_4+0].name = TM_Evu9b2R1utZubyCikahWx1g_3[TM_Evu9b2R1utZubyCikahWx1g_4];
TM_Evu9b2R1utZubyCikahWx1g_2[TM_Evu9b2R1utZubyCikahWx1g_4] = &TM_Evu9b2R1utZubyCikahWx1g_0[TM_Evu9b2R1utZubyCikahWx1g_4+0];
}
TM_Evu9b2R1utZubyCikahWx1g_0[9].len = 9; TM_Evu9b2R1utZubyCikahWx1g_0[9].kind = 2; TM_Evu9b2R1utZubyCikahWx1g_0[9].sons = &TM_Evu9b2R1utZubyCikahWx1g_2[0];
NTI_wfZHspwVKQPl9aWhkIcMrAA_.node = &TM_Evu9b2R1utZubyCikahWx1g_0[9];
NTI_GM611pWlOrQ7hvMPcuAACA_.size = sizeof(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA);
NTI_GM611pWlOrQ7hvMPcuAACA_.kind = 18;
NTI_GM611pWlOrQ7hvMPcuAACA_.base = 0;
NTI_GM611pWlOrQ7hvMPcuAACA_.flags = 2;
TM_Evu9b2R1utZubyCikahWx1g_0[10].kind = 1;
TM_Evu9b2R1utZubyCikahWx1g_0[10].offset = offsetof(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA, table);
TM_Evu9b2R1utZubyCikahWx1g_0[10].typ = (&NTI_Exo1CrLCLUIZQ4IUZ9aXEGg_);
TM_Evu9b2R1utZubyCikahWx1g_0[10].name = "table";
NTI_GM611pWlOrQ7hvMPcuAACA_.node = &TM_Evu9b2R1utZubyCikahWx1g_0[10];
NTI_FbZeO4trJhT2CCJ9aLxejqw_.size = sizeof(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA*);
NTI_FbZeO4trJhT2CCJ9aLxejqw_.kind = 22;
NTI_FbZeO4trJhT2CCJ9aLxejqw_.base = (&NTI_GM611pWlOrQ7hvMPcuAACA_);
NTI_FbZeO4trJhT2CCJ9aLxejqw_.flags = 2;
NTI_FbZeO4trJhT2CCJ9aLxejqw_.marker = Marker_tyRef_FbZeO4trJhT2CCJ9aLxejqw;
NTI_wOvXi5VibnCNgN9buQRQD4A_.size = sizeof(tyTuple_wOvXi5VibnCNgN9buQRQD4A);
NTI_wOvXi5VibnCNgN9buQRQD4A_.kind = 18;
NTI_wOvXi5VibnCNgN9buQRQD4A_.base = 0;
NTI_wOvXi5VibnCNgN9buQRQD4A_.flags = 2;
TM_Evu9b2R1utZubyCikahWx1g_52[0] = &TM_Evu9b2R1utZubyCikahWx1g_0[12];
TM_Evu9b2R1utZubyCikahWx1g_0[12].kind = 1;
TM_Evu9b2R1utZubyCikahWx1g_0[12].offset = offsetof(tyTuple_wOvXi5VibnCNgN9buQRQD4A, Field0);
TM_Evu9b2R1utZubyCikahWx1g_0[12].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Evu9b2R1utZubyCikahWx1g_0[12].name = "Field0";
TM_Evu9b2R1utZubyCikahWx1g_52[1] = &TM_Evu9b2R1utZubyCikahWx1g_0[13];
TM_Evu9b2R1utZubyCikahWx1g_0[13].kind = 1;
TM_Evu9b2R1utZubyCikahWx1g_0[13].offset = offsetof(tyTuple_wOvXi5VibnCNgN9buQRQD4A, Field1);
TM_Evu9b2R1utZubyCikahWx1g_0[13].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_Evu9b2R1utZubyCikahWx1g_0[13].name = "Field1";
TM_Evu9b2R1utZubyCikahWx1g_0[11].len = 2; TM_Evu9b2R1utZubyCikahWx1g_0[11].kind = 2; TM_Evu9b2R1utZubyCikahWx1g_0[11].sons = &TM_Evu9b2R1utZubyCikahWx1g_52[0];
NTI_wOvXi5VibnCNgN9buQRQD4A_.node = &TM_Evu9b2R1utZubyCikahWx1g_0[11];
}

