/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c -w -O3 -fno-strict-aliasing  -I/home/kuro/.choosenim/toolchains/nim-0.18.0/lib -o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_asyncfutures.o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_asyncfutures.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_2uzTbg8jwom7zHhmM2RgHg tyTuple_2uzTbg8jwom7zHhmM2RgHg;
typedef struct tyObject_Env_libslashpureslashasyncfuturesdotnim__sO5O0Qy9bzKs0atwA6HUBAw tyObject_Env_libslashpureslashasyncfuturesdotnim__sO5O0Qy9bzKs0atwA6HUBAw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct RootObj RootObj;
typedef struct tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg;
typedef struct tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ;
typedef struct Exception Exception;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag;
typedef struct tyTuple_O5pdIMCwdzZuqrzSnslnMg tyTuple_O5pdIMCwdzZuqrzSnslnMg;
typedef struct tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg;
typedef struct tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ;
typedef struct tyTuple_kGbLvpoD3zbaTmjDA6JF6g tyTuple_kGbLvpoD3zbaTmjDA6JF6g;
typedef struct tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg;
typedef struct tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ;
typedef struct tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A;
typedef struct tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ;
typedef struct tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA;
typedef struct tyTuple_kN8up2W6YKc5YA9avn5mV5w tyTuple_kN8up2W6YKc5YA9avn5mV5w;
typedef struct tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ;
typedef struct tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw;
typedef struct tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A;
typedef struct tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw;
typedef struct tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w;
typedef struct tyObject_Table_LLQadDAXEvd71UDdEc3lDA tyObject_Table_LLQadDAXEvd71UDdEc3lDA;
typedef struct tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ;
typedef struct tySequence_8Np6tlClE5az1CyqZdN19bQ tySequence_8Np6tlClE5az1CyqZdN19bQ;
typedef struct tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw;
typedef struct tySequence_JiteSJxrvz63iP2o9bcn2Sg tySequence_JiteSJxrvz63iP2o9bcn2Sg;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct tyTuple_g1w83cyyBYiVU9c8WEJWnjQ tyTuple_g1w83cyyBYiVU9c8WEJWnjQ;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyProc_IIomJ6ptE6vfJ5zRbATgkQ cbproc, void* ClE_0);
void* ClE_0;
} tyProc_Ig6kXMs9apW5862wHsbFhGw;
struct tyTuple_2uzTbg8jwom7zHhmM2RgHg {
void* Field0;
tyObject_Env_libslashpureslashasyncfuturesdotnim__sO5O0Qy9bzKs0atwA6HUBAw* Field1;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_Env_libslashpureslashasyncfuturesdotnim__sO5O0Qy9bzKs0atwA6HUBAw {
  RootObj Sup;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ {
tyProc_IIomJ6ptE6vfJ5zRbATgkQ function;
tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ* next;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg {
  RootObj Sup;
tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ callbacks;
NIM_BOOL finished;
Exception* error;
NimStringDesc* errorStackTrace;
};
struct tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_CLOSURE_PTR(void, TM_vnqLhdH9cCREQ2r9aXVOqbvQ_7) (void);
typedef N_CLOSURE_PTR(void, TM_vnqLhdH9cCREQ2r9aXVOqbvQ_8) (tyProc_IIomJ6ptE6vfJ5zRbATgkQ cbproc);
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyTuple_O5pdIMCwdzZuqrzSnslnMg {
NimStringDesc* Field0;
tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg* Field1;
};
struct tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
tyTuple_O5pdIMCwdzZuqrzSnslnMg value;
};
struct tyTuple_kGbLvpoD3zbaTmjDA6JF6g {
NimStringDesc* Field0;
int Field1;
};
struct tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
tyTuple_kGbLvpoD3zbaTmjDA6JF6g value;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* future, void* ClE_0);
void* ClE_0;
} tyProc_8wttzV3rzAH1IXkaO7bCyw;
struct tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg {
  RootObj Sup;
NI colonstate_;
tyProc_8wttzV3rzAH1IXkaO7bCyw cb1;
tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* future2;
};
typedef N_CLOSURE_PTR(void, TM_vnqLhdH9cCREQ2r9aXVOqbvQ_13) (tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* future);
struct tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ {
  RootObj Sup;
NI colonstate_;
tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future1;
};
typedef NU8 tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA;
struct tyTuple_kN8up2W6YKc5YA9avn5mV5w {
NimStringDesc* Field0;
NI Field1;
NI Field2;
};
struct tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ {
NimStringDesc* scheme;
NimStringDesc* username;
NimStringDesc* password;
NimStringDesc* hostname;
NimStringDesc* port;
NimStringDesc* path;
NimStringDesc* query;
NimStringDesc* anchor;
NIM_BOOL opaque;
};
struct tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ {
tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg* client;
tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA reqMethod;
tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers;
tyTuple_kN8up2W6YKc5YA9avn5mV5w protocol;
tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ url;
NimStringDesc* hostname;
NimStringDesc* body;
};
struct tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ value;
};
struct tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
NimStringDesc* value;
};
struct tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
NIM_BOOL value;
};
struct tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
NI value;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
typedef NIM_CHAR tyArray_QQGLPNVVwLhYjkngqAxXQQ[4001];
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg;
struct tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg {
int fd;
NIM_BOOL closed;
NIM_BOOL isBuffered;
union{
struct {tyArray_QQGLPNVVwLhYjkngqAxXQQ buffer;
NI currPos;
NI bufLen;
} S1;
} isBufferedU;
NIM_BOOL isSsl;
union{
struct {tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* sslHandle;
tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w* sslContext;
tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* bioIn;
tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* bioOut;
} S1;
} isSslU;
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain;
tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType;
tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol;
};
struct tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA {
tyObject_Table_LLQadDAXEvd71UDdEc3lDA* table;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw {
char dummy;
};
struct tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ {
tySequence_8Np6tlClE5az1CyqZdN19bQ* data;
NI counter;
};
struct tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w {
tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* context;
tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ referencedData;
tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw* extraInternal;
};
struct tyObject_Table_LLQadDAXEvd71UDdEc3lDA {
tySequence_JiteSJxrvz63iP2o9bcn2Sg* data;
NI counter;
};
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef struct {
N_NIMCALL_PTR(NimStringDesc*, ClP_0) (NimStringDesc* identity, void* ClE_0);
void* ClE_0;
} tyProc_lRW9cfxqfm1ql4gkxfLReYg;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NimStringDesc* hint, tyTuple_UV3llMMYFckfui8YMBuUZA* Result, void* ClE_0);
void* ClE_0;
} tyProc_nzIUHFubO43GG203VFo9b7A;
struct tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw {
  RootObj Sup;
tyProc_lRW9cfxqfm1ql4gkxfLReYg serverGetPskFunc;
tyProc_nzIUHFubO43GG203VFo9b7A clientGetPskFunc;
};
struct tyTuple_g1w83cyyBYiVU9c8WEJWnjQ {
NI Field0;
NimStringDesc* Field1;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* Field2;
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence_8Np6tlClE5az1CyqZdN19bQ {
  TGenericSeq Sup;
  tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_JiteSJxrvz63iP2o9bcn2Sg {
  TGenericSeq Sup;
  tyTuple_g1w83cyyBYiVU9c8WEJWnjQ data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tyRef_58EFneeS9at7cA541QCoGAw)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_vnqLhdH9cCREQ2r9aXVOqbvQ_3)(void);
N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_NIMCALL(void, Marker_tyRef_gcUT3qWwCET3KjsqW7m5vQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_zXD0JrbeCNyAaW4E6fB9aqg)(void* p, NI op);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, checkFinished_EYgDXwwneJeAEUfXLUHmhg)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future);
N_LIB_PRIVATE N_NIMCALL(void, call_Fn9a5LxW5RtXmTFhp4FWrXA)(tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ* callbacks);
N_LIB_PRIVATE N_NIMCALL(void, callSoon_QRqbRWvB9aOehus0Vh9a8KSg)(tyProc_IIomJ6ptE6vfJ5zRbATgkQ cbproc);
N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace_EYgDXwwneJeAEUfXLUHmhg_3)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_NIMCALL(void, Marker_tyRef_QiRyy9aiJcSFRns0QePOMuA)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_AfWQ0kHnrE0Z8Fcs059bTew)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, checkFinished_FNPCCSEfnj6nNINZs7LuPg)(tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* future);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA)(Exception* e);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStackTrace_ivElcGv1RQQWHS87N1tZ8Q)(void);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_NIMCALL(void, Marker_tyRef_mwHddAmnKJ7dYAg59auCvrA)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, callbackeq__9c5z7ouO5bUylgKxaZoIuVg)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future, tyProc_IIomJ6ptE6vfJ5zRbATgkQ cb);
N_LIB_PRIVATE N_NIMCALL(void, clearCallbacks_TnbZti5bi9asqRLLM7X9cvjQ)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future);
N_LIB_PRIVATE N_NIMCALL(void, addCallback_9c5z7ouO5bUylgKxaZoIuVg_2)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future, tyProc_IIomJ6ptE6vfJ5zRbATgkQ cb);
N_LIB_PRIVATE N_NIMCALL(void, add_vMmlZbSeohzLjOahIqjRrg)(tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ* callbacks, tyProc_IIomJ6ptE6vfJ5zRbATgkQ function);
N_LIB_PRIVATE N_NIMCALL(tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ*, new_FQx28IJiFqPBF29c5ZyixRQ)(void);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__9a8Pr5agMU3isnBa4tGw6OA)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, checkFinished_jSQOqwfMx17tAhrlGQ6OvA)(tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag* future);
N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace_FNPCCSEfnj6nNINZs7LuPg_2)(tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* future);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace_jSQOqwfMx17tAhrlGQ6OvA_2)(tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag* future);
static N_NIMCALL(void, Marker_tyRef_BIMSEViDEmmSlRRPmCHvhA)(void* p, NI op);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__9a8Pr5agMU3isnBa4tGw6OA_2)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, failed_ZDnEFECD9b9aKFsuVLxFyzkA)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future);
static N_NIMCALL(void, Marker_tyRef_LfThFRgN4RNCjdx5FyKokA)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_IPdYES9cLWlRlcD0lECASkA)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A*, newFuture_rKo5SK9cDnnCFQYX8RgYLmg)(NimStringDesc* fromProc);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw*, newFuture_XK0oPeyNeCEbWe8WPuCbyA)(NimStringDesc* fromProc);
static N_NIMCALL(void, Marker_tyRef_mO0oVXyu0e0fi1I49aYToDg)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_fS34nJaWsnEzVF1r1vjUzw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, checkFinished_bcojm5j7VL1Elkboo9cPN2A)(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* future);
N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace_bcojm5j7VL1Elkboo9cPN2A_2)(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* future);
N_LIB_PRIVATE N_NIMCALL(void, checkFinished_RdmPOyPwbBvDPzZVjkDhkg)(tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A* future);
N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace_RdmPOyPwbBvDPzZVjkDhkg_2)(tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A* future);
N_LIB_PRIVATE N_NIMCALL(void, checkFinished_DFFruFX8VfzZKt1pjlpVBg)(tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ* future);
N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace_DFFruFX8VfzZKt1pjlpVBg_2)(tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ* future);
N_LIB_PRIVATE N_NIMCALL(void, checkFinished_OTFrALKjyNsZ6wzqd22kQQ)(tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A* future);
tyProc_Ig6kXMs9apW5862wHsbFhGw callSoonProc_9b9b4iUSd60RO2UqC52ifJ6A;
TNimType NTI_Ig6kXMs9apW5862wHsbFhGw_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_sO5O0Qy9bzKs0atwA6HUBAw_;
TNimType NTI_58EFneeS9at7cA541QCoGAw_;
TNimType NTI_cnXnCCtV9cjKaEq9alHheOFg_;
TNimType NTI_tKSBWiaJMWD3JZxwqg7UFQ_;
TNimType NTI_IIomJ6ptE6vfJ5zRbATgkQ_;
TNimType NTI_gcUT3qWwCET3KjsqW7m5vQ_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI_oUKtBcKRdK6usj8RWrlp6A_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_SmxCgsot45ayPNDBegkWAg_;
TNimType NTI_zXD0JrbeCNyAaW4E6fB9aqg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_yCEN9anxCD6mzBxGjuaRBdg_;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
TNimType NTI_tsPdh8RQR6qNUGxaRKf3ag_;
extern TNimType NTI_O5pdIMCwdzZuqrzSnslnMg_;
TNimType NTI_QiRyy9aiJcSFRns0QePOMuA_;
TNimType NTI_4aKPZ9bIsx13R9cJcNxCeWmQ_;
extern TNimType NTI_kGbLvpoD3zbaTmjDA6JF6g_;
TNimType NTI_AfWQ0kHnrE0Z8Fcs059bTew_;
TNimType NTI_ZDLd9bMvg7fd2amVY4Hp9bWg_;
extern TNimType NTI_xHTZrq9aYs6boc9bCba0JbpQ_;
TNimType NTI_8wttzV3rzAH1IXkaO7bCyw_;
TNimType NTI_mwHddAmnKJ7dYAg59auCvrA_;
TNimType NTI_W9ac4kEPq6nRQuOCYEsC6nQ_;
TNimType NTI_BIMSEViDEmmSlRRPmCHvhA_;
TNimType NTI_xfdVCtBDWltkbfIr9bhAe7A_;
extern TNimType NTI_1Wfxxtqzahm0R6lueM9aQmQ_;
TNimType NTI_LfThFRgN4RNCjdx5FyKokA_;
TNimType NTI_80u9bn9aLY6K9bjx4fUTV9axAw_;
TNimType NTI_IPdYES9cLWlRlcD0lECASkA_;
TNimType NTI_NsWcx0WwTBxL9ciLNz9c2y3A_;
TNimType NTI_mO0oVXyu0e0fi1I49aYToDg_;
TNimType NTI_KNdXp3d84rAXqWxjhTR9aFQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_fS34nJaWsnEzVF1r1vjUzw_;
static NIM_CONST tyProc_IIomJ6ptE6vfJ5zRbATgkQ TM_vnqLhdH9cCREQ2r9aXVOqbvQ_9 = {NIM_NIL,NIM_NIL};
STRING_LITERAL(TM_vnqLhdH9cCREQ2r9aXVOqbvQ_10, "Future still in progress.", 25);
STRING_LITERAL(TM_vnqLhdH9cCREQ2r9aXVOqbvQ_14, "No error in future.", 19);
static N_NIMCALL(void, Marker_tyRef_58EFneeS9at7cA541QCoGAw)(void* p, NI op) {
	tyObject_Env_libslashpureslashasyncfuturesdotnim__sO5O0Qy9bzKs0atwA6HUBAw* a;
	a = (tyObject_Env_libslashpureslashasyncfuturesdotnim__sO5O0Qy9bzKs0atwA6HUBAw*)p;
}
static N_NIMCALL(void, TM_vnqLhdH9cCREQ2r9aXVOqbvQ_3)(void) {
	nimGCvisit((void*)callSoonProc_9b9b4iUSd60RO2UqC52ifJ6A.ClE_0, 0);
}
static N_NIMCALL(void, Marker_tyRef_gcUT3qWwCET3KjsqW7m5vQ)(void* p, NI op) {
	tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ* a;
	a = (tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ*)p;
	nimGCvisit((void*)(*a).function.ClE_0, op);
	nimGCvisit((void*)(*a).next, op);
}
static N_NIMCALL(void, Marker_tyRef_zXD0JrbeCNyAaW4E6fB9aqg)(void* p, NI op) {
	tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* a;
	a = (tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*)p;
	nimGCvisit((void*)(*a).Sup.callbacks.function.ClE_0, op);
	nimGCvisit((void*)(*a).Sup.callbacks.next, op);
	nimGCvisit((void*)(*a).Sup.error, op);
	nimGCvisit((void*)(*a).Sup.errorStackTrace, op);
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_jn4eVK3zFIl4kShRnlTsCg)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (*future).Sup.finished;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, getCallSoonProc_EMWMqpRRzDYLwdGrzAQBuA)(tyProc_Ig6kXMs9apW5862wHsbFhGw* Result) {
{	genericReset((void*)Result, (&NTI_Ig6kXMs9apW5862wHsbFhGw_));
	unsureAsgnRef((void**) (&(*Result).ClE_0), callSoonProc_9b9b4iUSd60RO2UqC52ifJ6A.ClE_0);
	(*Result).ClP_0 = callSoonProc_9b9b4iUSd60RO2UqC52ifJ6A.ClP_0;
	goto BeforeRet_;
	}BeforeRet_: ;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(void, setCallSoonProc_tp3fL2WDe4gS3fslj7T9aRQ)(tyProc_Ig6kXMs9apW5862wHsbFhGw p) {
	asgnRef((void**) (&callSoonProc_9b9b4iUSd60RO2UqC52ifJ6A.ClE_0), p.ClE_0);
	callSoonProc_9b9b4iUSd60RO2UqC52ifJ6A.ClP_0 = p.ClP_0;
}

N_LIB_PRIVATE N_NIMCALL(void, checkFinished_EYgDXwwneJeAEUfXLUHmhg)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future) {
}

N_LIB_PRIVATE N_NIMCALL(void, callSoon_QRqbRWvB9aOehus0Vh9a8KSg)(tyProc_IIomJ6ptE6vfJ5zRbATgkQ cbproc) {
	{
		if (!(callSoonProc_9b9b4iUSd60RO2UqC52ifJ6A.ClP_0 == 0)) goto LA3_;
		cbproc.ClE_0? cbproc.ClP_0(cbproc.ClE_0):((TM_vnqLhdH9cCREQ2r9aXVOqbvQ_7)(cbproc.ClP_0))();
	}
	goto LA1_;
	LA3_: ;
	{
		callSoonProc_9b9b4iUSd60RO2UqC52ifJ6A.ClE_0? callSoonProc_9b9b4iUSd60RO2UqC52ifJ6A.ClP_0(cbproc, callSoonProc_9b9b4iUSd60RO2UqC52ifJ6A.ClE_0):((TM_vnqLhdH9cCREQ2r9aXVOqbvQ_8)(callSoonProc_9b9b4iUSd60RO2UqC52ifJ6A.ClP_0))(cbproc);
	}
	LA1_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, call_Fn9a5LxW5RtXmTFhp4FWrXA)(tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ* callbacks) {
	tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ current;
	memset((void*)(&current), 0, sizeof(current));
	current.function.ClE_0 = (*callbacks).function.ClE_0;
	current.function.ClP_0 = (*callbacks).function.ClP_0;
	current.next = (*callbacks).next;
	{
		while (1) {
			{
				if (!!((current.function.ClP_0 == 0))) goto LA5_;
				callSoon_QRqbRWvB9aOehus0Vh9a8KSg(current.function);
			}
			LA5_: ;
			{
				if (!(current.next == 0)) goto LA9_;
				goto LA1;
			}
			goto LA7_;
			LA9_: ;
			{
				current.function.ClE_0 = (*current.next).function.ClE_0;
				current.function.ClP_0 = (*current.next).function.ClP_0;
				current.next = (*current.next).next;
			}
			LA7_: ;
		}
	} LA1: ;
	unsureAsgnRef((void**) (&(*callbacks).next), NIM_NIL);
	unsureAsgnRef((void**) (&(*callbacks).function.ClE_0), TM_vnqLhdH9cCREQ2r9aXVOqbvQ_9.ClE_0);
	(*callbacks).function.ClP_0 = TM_vnqLhdH9cCREQ2r9aXVOqbvQ_9.ClP_0;
}

N_LIB_PRIVATE N_NIMCALL(void, complete_mvHczm6KlNpTkVsXGCEbgg)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future) {
	checkFinished_EYgDXwwneJeAEUfXLUHmhg(future);
	(*future).Sup.finished = NIM_TRUE;
	call_Fn9a5LxW5RtXmTFhp4FWrXA((&(*future).Sup.callbacks));
}

N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace_EYgDXwwneJeAEUfXLUHmhg_3)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future) {
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, read_EYgDXwwneJeAEUfXLUHmhg_2)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future) {
	tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* fut;
	fut = future;
	{
		if (!(*fut).Sup.finished) goto LA3_;
		{
			if (!!(((*fut).Sup.error == NIM_NIL))) goto LA7_;
			injectStacktrace_EYgDXwwneJeAEUfXLUHmhg_3(fut);
			raiseException((Exception*)(*fut).Sup.error, "Exception");
		}
		LA7_: ;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T10_;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		T10_ = (NimStringDesc*)0;
		T10_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_10));
		if (T10_) nimGCunrefNoCycle(T10_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "ValueError");
	}
	LA1_: ;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, newFuture_1afITAy9cOOiZDRZUZbFt0w)(NimStringDesc* fromProc) {
	tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* result;
	result = (tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*)0;
	result = (tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*) newObj((&NTI_zXD0JrbeCNyAaW4E6fB9aqg_), sizeof(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg));
	(*result).Sup.Sup.m_type = (&NTI_SmxCgsot45ayPNDBegkWAg_);
	(*result).Sup.finished = NIM_FALSE;
	return result;
}
static N_NIMCALL(void, Marker_tyRef_QiRyy9aiJcSFRns0QePOMuA)(void* p, NI op) {
	tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag* a;
	a = (tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag*)p;
	nimGCvisit((void*)(*a).Sup.callbacks.function.ClE_0, op);
	nimGCvisit((void*)(*a).Sup.callbacks.next, op);
	nimGCvisit((void*)(*a).Sup.error, op);
	nimGCvisit((void*)(*a).Sup.errorStackTrace, op);
	nimGCvisit((void*)(*a).value.Field0, op);
	nimGCvisit((void*)(*a).value.Field1, op);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag*, newFuture_vjH9aNWQwHX1q6okaCIKikg)(NimStringDesc* fromProc) {
	tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag* result;
	result = (tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag*)0;
	result = (tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag*) newObj((&NTI_QiRyy9aiJcSFRns0QePOMuA_), sizeof(tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag));
	(*result).Sup.Sup.m_type = (&NTI_tsPdh8RQR6qNUGxaRKf3ag_);
	(*result).Sup.finished = NIM_FALSE;
	return result;
}
static N_NIMCALL(void, Marker_tyRef_AfWQ0kHnrE0Z8Fcs059bTew)(void* p, NI op) {
	tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* a;
	a = (tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ*)p;
	nimGCvisit((void*)(*a).Sup.callbacks.function.ClE_0, op);
	nimGCvisit((void*)(*a).Sup.callbacks.next, op);
	nimGCvisit((void*)(*a).Sup.error, op);
	nimGCvisit((void*)(*a).Sup.errorStackTrace, op);
	nimGCvisit((void*)(*a).value.Field0, op);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ*, newFuture_ekN9a48CH9bw1ENmyzWl89aCA)(NimStringDesc* fromProc) {
	tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* result;
	result = (tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ*)0;
	result = (tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ*) newObj((&NTI_AfWQ0kHnrE0Z8Fcs059bTew_), sizeof(tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ));
	(*result).Sup.Sup.m_type = (&NTI_4aKPZ9bIsx13R9cJcNxCeWmQ_);
	(*result).Sup.finished = NIM_FALSE;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, checkFinished_FNPCCSEfnj6nNINZs7LuPg)(tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* future) {
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		if (!!((src == NIM_NIL))) goto LA3_;
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(void, fail_aSCFtPi6uIjCaspt8KIluQ)(tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* future, Exception* error) {
	checkFinished_FNPCCSEfnj6nNINZs7LuPg(future);
	(*future).Sup.finished = NIM_TRUE;
	asgnRef((void**) (&(*future).Sup.error), error);
	{
		NimStringDesc* T3_;
		T3_ = (NimStringDesc*)0;
		T3_ = getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(error);
		if (!((T3_) && (T3_)->Sup.len == 0)) goto LA4_;
		asgnRefNoCycle((void**) (&(*future).Sup.errorStackTrace), getStackTrace_ivElcGv1RQQWHS87N1tZ8Q());
	}
	goto LA1_;
	LA4_: ;
	{
		asgnRefNoCycle((void**) (&(*future).Sup.errorStackTrace), getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(error));
	}
	LA1_: ;
	call_Fn9a5LxW5RtXmTFhp4FWrXA((&(*future).Sup.callbacks));
}

N_LIB_PRIVATE N_NIMCALL(void, complete_aUbDodMDoslH1P4naG9c3IA)(tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* future, tyTuple_kGbLvpoD3zbaTmjDA6JF6g val) {
	NimStringDesc* T1_;
	checkFinished_FNPCCSEfnj6nNINZs7LuPg(future);
	T1_ = (NimStringDesc*)0;
	T1_ = (*future).value.Field0; (*future).value.Field0 = copyStringRC1(val.Field0);
	if (T1_) nimGCunrefNoCycle(T1_);
	(*future).value.Field1 = val.Field1;
	(*future).Sup.finished = NIM_TRUE;
	call_Fn9a5LxW5RtXmTFhp4FWrXA((&(*future).Sup.callbacks));
}
static N_NIMCALL(void, Marker_tyRef_mwHddAmnKJ7dYAg59auCvrA)(void* p, NI op) {
	tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg* a;
	a = (tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg*)p;
	nimGCvisit((void*)(*a).cb1.ClE_0, op);
	nimGCvisit((void*)(*a).future2, op);
}

N_LIB_PRIVATE N_NIMCALL(void, clearCallbacks_TnbZti5bi9asqRLLM7X9cvjQ)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future) {
	asgnRef((void**) (&(*future).callbacks.function.ClE_0), TM_vnqLhdH9cCREQ2r9aXVOqbvQ_9.ClE_0);
	(*future).callbacks.function.ClP_0 = TM_vnqLhdH9cCREQ2r9aXVOqbvQ_9.ClP_0;
	asgnRef((void**) (&(*future).callbacks.next), NIM_NIL);
}

N_LIB_PRIVATE N_NIMCALL(void, add_vMmlZbSeohzLjOahIqjRrg)(tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ* callbacks, tyProc_IIomJ6ptE6vfJ5zRbATgkQ function) {
	{
		if (!((*callbacks).function.ClP_0 == 0)) goto LA3_;
		unsureAsgnRef((void**) (&(*callbacks).function.ClE_0), function.ClE_0);
		(*callbacks).function.ClP_0 = function.ClP_0;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ* newNext;
		newNext = new_FQx28IJiFqPBF29c5ZyixRQ();
		asgnRef((void**) (&(*newNext).function.ClE_0), (*callbacks).function.ClE_0);
		(*newNext).function.ClP_0 = (*callbacks).function.ClP_0;
		asgnRef((void**) (&(*newNext).next), (*callbacks).next);
		unsureAsgnRef((void**) (&(*callbacks).next), newNext);
		unsureAsgnRef((void**) (&(*callbacks).function.ClE_0), function.ClE_0);
		(*callbacks).function.ClP_0 = function.ClP_0;
	}
	LA1_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, addCallback_9c5z7ouO5bUylgKxaZoIuVg_2)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future, tyProc_IIomJ6ptE6vfJ5zRbATgkQ cb) {
	{
		if (!(*future).finished) goto LA3_;
		callSoon_QRqbRWvB9aOehus0Vh9a8KSg(cb);
	}
	goto LA1_;
	LA3_: ;
	{
		add_vMmlZbSeohzLjOahIqjRrg((&(*future).callbacks), cb);
	}
	LA1_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, callbackeq__9c5z7ouO5bUylgKxaZoIuVg)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future, tyProc_IIomJ6ptE6vfJ5zRbATgkQ cb) {
	clearCallbacks_TnbZti5bi9asqRLLM7X9cvjQ(future);
	addCallback_9c5z7ouO5bUylgKxaZoIuVg_2(future, cb);
}

N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__9a8Pr5agMU3isnBa4tGw6OA)(void* ClE_0) {
	tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg* colonenvP_;
	colonenvP_ = (tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg*) ClE_0;
	(*colonenvP_).cb1.ClE_0? (*colonenvP_).cb1.ClP_0((*colonenvP_).future2, (*colonenvP_).cb1.ClE_0):((TM_vnqLhdH9cCREQ2r9aXVOqbvQ_13)((*colonenvP_).cb1.ClP_0))((*colonenvP_).future2);
}

N_LIB_PRIVATE N_NIMCALL(void, callbackeq__kLGzIimG1KWH9bVvCYHsFqw)(tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* future, tyProc_8wttzV3rzAH1IXkaO7bCyw cb) {
	tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg* colonenv_;
	tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* T1_;
	tyProc_IIomJ6ptE6vfJ5zRbATgkQ T2_;
	colonenv_ = (tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg*)0;
	colonenv_ = (tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg*) newObj((&NTI_mwHddAmnKJ7dYAg59auCvrA_), sizeof(tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg));
	(*colonenv_).Sup.m_type = (&NTI_ZDLd9bMvg7fd2amVY4Hp9bWg_);
	asgnRef((void**) (&(*colonenv_).future2), future);
	asgnRef((void**) (&(*colonenv_).cb1.ClE_0), cb.ClE_0);
	(*colonenv_).cb1.ClP_0 = cb.ClP_0;
	T1_ = (tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*)0;
	T1_ = &(*colonenv_).future2->Sup;
	memset((void*)(&T2_), 0, sizeof(T2_));
	T2_.ClP_0 = colonanonymous__9a8Pr5agMU3isnBa4tGw6OA; T2_.ClE_0 = colonenv_;
	callbackeq__9c5z7ouO5bUylgKxaZoIuVg(T1_, T2_);
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, failed_ZDnEFECD9b9aKFsuVLxFyzkA)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	result = !(((*future).error == NIM_NIL));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, checkFinished_jSQOqwfMx17tAhrlGQ6OvA)(tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag* future) {
}

N_LIB_PRIVATE N_NIMCALL(void, fail_7l9bPap9cgVFv6cQSCjJjv3Q)(tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag* future, Exception* error) {
	checkFinished_jSQOqwfMx17tAhrlGQ6OvA(future);
	(*future).Sup.finished = NIM_TRUE;
	asgnRef((void**) (&(*future).Sup.error), error);
	{
		NimStringDesc* T3_;
		T3_ = (NimStringDesc*)0;
		T3_ = getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(error);
		if (!((T3_) && (T3_)->Sup.len == 0)) goto LA4_;
		asgnRefNoCycle((void**) (&(*future).Sup.errorStackTrace), getStackTrace_ivElcGv1RQQWHS87N1tZ8Q());
	}
	goto LA1_;
	LA4_: ;
	{
		asgnRefNoCycle((void**) (&(*future).Sup.errorStackTrace), getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(error));
	}
	LA1_: ;
	call_Fn9a5LxW5RtXmTFhp4FWrXA((&(*future).Sup.callbacks));
}

N_LIB_PRIVATE N_NIMCALL(Exception*, readError_11aHiItaN2U3XKLeUCKetw)(tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* future) {
	Exception* result;
{	result = (Exception*)0;
	{
		if (!!(((*future).Sup.error == NIM_NIL))) goto LA3_;
		result = (*future).Sup.error;
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T6_;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		T6_ = (NimStringDesc*)0;
		T6_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_14));
		if (T6_) nimGCunrefNoCycle(T6_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "ValueError");
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace_FNPCCSEfnj6nNINZs7LuPg_2)(tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* future) {
}

N_LIB_PRIVATE N_NIMCALL(void, read_ZoVle12AE9bZ80PVQby9cZeg)(tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* future, tyTuple_kGbLvpoD3zbaTmjDA6JF6g* Result) {
	tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ* fut;
{	genericReset((void*)Result, (&NTI_kGbLvpoD3zbaTmjDA6JF6g_));
	fut = future;
	{
		if (!(*fut).Sup.finished) goto LA3_;
		{
			if (!!(((*fut).Sup.error == NIM_NIL))) goto LA7_;
			injectStacktrace_FNPCCSEfnj6nNINZs7LuPg_2(fut);
			raiseException((Exception*)(*fut).Sup.error, "Exception");
		}
		LA7_: ;
		unsureAsgnRef((void**) (&(*Result).Field0), copyString((*fut).value.Field0));
		(*Result).Field1 = (*fut).value.Field1;
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T10_;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		T10_ = (NimStringDesc*)0;
		T10_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_10));
		if (T10_) nimGCunrefNoCycle(T10_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "ValueError");
	}
	LA1_: ;
	}BeforeRet_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, complete_NYLm0K1puNxkuuquRLysYg)(tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag* future, tyTuple_O5pdIMCwdzZuqrzSnslnMg val) {
	NimStringDesc* T1_;
	checkFinished_jSQOqwfMx17tAhrlGQ6OvA(future);
	T1_ = (NimStringDesc*)0;
	T1_ = (*future).value.Field0; (*future).value.Field0 = copyStringRC1(val.Field0);
	if (T1_) nimGCunrefNoCycle(T1_);
	asgnRef((void**) (&(*future).value.Field1), val.Field1);
	(*future).Sup.finished = NIM_TRUE;
	call_Fn9a5LxW5RtXmTFhp4FWrXA((&(*future).Sup.callbacks));
}

N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace_jSQOqwfMx17tAhrlGQ6OvA_2)(tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag* future) {
}

N_LIB_PRIVATE N_NIMCALL(void, read_IePteNZ9bk2hguPYXuU4SZg)(tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag* future, tyTuple_O5pdIMCwdzZuqrzSnslnMg* Result) {
	tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag* fut;
{	genericReset((void*)Result, (&NTI_O5pdIMCwdzZuqrzSnslnMg_));
	fut = future;
	{
		if (!(*fut).Sup.finished) goto LA3_;
		{
			if (!!(((*fut).Sup.error == NIM_NIL))) goto LA7_;
			injectStacktrace_jSQOqwfMx17tAhrlGQ6OvA_2(fut);
			raiseException((Exception*)(*fut).Sup.error, "Exception");
		}
		LA7_: ;
		unsureAsgnRef((void**) (&(*Result).Field0), copyString((*fut).value.Field0));
		unsureAsgnRef((void**) (&(*Result).Field1), (*fut).value.Field1);
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T10_;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		T10_ = (NimStringDesc*)0;
		T10_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_10));
		if (T10_) nimGCunrefNoCycle(T10_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "ValueError");
	}
	LA1_: ;
	}BeforeRet_: ;
}
static N_NIMCALL(void, Marker_tyRef_BIMSEViDEmmSlRRPmCHvhA)(void* p, NI op) {
	tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ* a;
	a = (tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ*)p;
	nimGCvisit((void*)(*a).future1, op);
}

N_LIB_PRIVATE N_CLOSURE(void, colonanonymous__9a8Pr5agMU3isnBa4tGw6OA_2)(void* ClE_0) {
	tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ* colonenvP_;
	colonenvP_ = (tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ*) ClE_0;
	{
		tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* T3_;
		NIM_BOOL T4_;
		T3_ = (tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*)0;
		T3_ = &(*colonenvP_).future1->Sup;
		T4_ = (NIM_BOOL)0;
		T4_ = failed_ZDnEFECD9b9aKFsuVLxFyzkA(T3_);
		if (!T4_) goto LA5_;
		injectStacktrace_EYgDXwwneJeAEUfXLUHmhg_3((*colonenvP_).future1);
		raiseException((Exception*)(*(*colonenvP_).future1).Sup.error, "Exception");
	}
	LA5_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, asyncCheck_mvHczm6KlNpTkVsXGCEbgg_2)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future) {
	tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ* colonenv_;
	tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* T1_;
	tyProc_IIomJ6ptE6vfJ5zRbATgkQ T2_;
	colonenv_ = (tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ*)0;
	colonenv_ = (tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ*) newObj((&NTI_BIMSEViDEmmSlRRPmCHvhA_), sizeof(tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ));
	(*colonenv_).Sup.m_type = (&NTI_W9ac4kEPq6nRQuOCYEsC6nQ_);
	asgnRef((void**) (&(*colonenv_).future1), future);
	T1_ = (tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*)0;
	T1_ = &(*colonenv_).future1->Sup;
	memset((void*)(&T2_), 0, sizeof(T2_));
	T2_.ClP_0 = colonanonymous__9a8Pr5agMU3isnBa4tGw6OA_2; T2_.ClE_0 = colonenv_;
	callbackeq__9c5z7ouO5bUylgKxaZoIuVg(T1_, T2_);
}
static N_NIMCALL(void, Marker_tyRef_LfThFRgN4RNCjdx5FyKokA)(void* p, NI op) {
	tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A* a;
	a = (tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A*)p;
	nimGCvisit((void*)(*a).Sup.callbacks.function.ClE_0, op);
	nimGCvisit((void*)(*a).Sup.callbacks.next, op);
	nimGCvisit((void*)(*a).Sup.error, op);
	nimGCvisit((void*)(*a).Sup.errorStackTrace, op);
	nimGCvisit((void*)(*a).value.client, op);
	nimGCvisit((void*)(*a).value.headers, op);
	nimGCvisit((void*)(*a).value.protocol.Field0, op);
	nimGCvisit((void*)(*a).value.url.scheme, op);
	nimGCvisit((void*)(*a).value.url.username, op);
	nimGCvisit((void*)(*a).value.url.password, op);
	nimGCvisit((void*)(*a).value.url.hostname, op);
	nimGCvisit((void*)(*a).value.url.port, op);
	nimGCvisit((void*)(*a).value.url.path, op);
	nimGCvisit((void*)(*a).value.url.query, op);
	nimGCvisit((void*)(*a).value.url.anchor, op);
	nimGCvisit((void*)(*a).value.hostname, op);
	nimGCvisit((void*)(*a).value.body, op);
}
static N_NIMCALL(void, Marker_tyRef_IPdYES9cLWlRlcD0lECASkA)(void* p, NI op) {
	tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* a;
	a = (tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw*)p;
	nimGCvisit((void*)(*a).Sup.callbacks.function.ClE_0, op);
	nimGCvisit((void*)(*a).Sup.callbacks.next, op);
	nimGCvisit((void*)(*a).Sup.error, op);
	nimGCvisit((void*)(*a).Sup.errorStackTrace, op);
	nimGCvisit((void*)(*a).value, op);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A*, newFuture_rKo5SK9cDnnCFQYX8RgYLmg)(NimStringDesc* fromProc) {
	tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A* result;
	result = (tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A*)0;
	result = (tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A*) newObj((&NTI_LfThFRgN4RNCjdx5FyKokA_), sizeof(tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A));
	(*result).Sup.Sup.m_type = (&NTI_xfdVCtBDWltkbfIr9bhAe7A_);
	(*result).Sup.finished = NIM_FALSE;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A*, newFutureVar_OIujpTFKoAz9aqrml6OY9aLA)(NimStringDesc* fromProc) {
	tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A* result;
	result = (tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A*)0;
	result = newFuture_rKo5SK9cDnnCFQYX8RgYLmg(fromProc);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ*, mget_kUh9bpxVGEvOnKXazacz0ug)(tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A* future) {
	tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ* result;
	result = (tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ*)0;
	result = (&(*future).value);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw*, newFuture_XK0oPeyNeCEbWe8WPuCbyA)(NimStringDesc* fromProc) {
	tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* result;
	result = (tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw*)0;
	result = (tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw*) newObj((&NTI_IPdYES9cLWlRlcD0lECASkA_), sizeof(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw));
	(*result).Sup.Sup.m_type = (&NTI_80u9bn9aLY6K9bjx4fUTV9axAw_);
	(*result).Sup.finished = NIM_FALSE;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw*, newFutureVar_OIujpTFKoAz9aqrml6OY9aLA_2)(NimStringDesc* fromProc) {
	tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* result;
	result = (tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw*)0;
	result = newFuture_XK0oPeyNeCEbWe8WPuCbyA(fromProc);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc**, mget_5B9c9ck9bvt5oYiBDyY2WNPrQ)(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* future) {
	NimStringDesc** result;
	result = (NimStringDesc**)0;
	result = (&(*future).value);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, clean_G8M9a65bGRiXS27G0iMKntg)(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* future) {
	(*future).Sup.finished = NIM_FALSE;
	asgnRef((void**) (&(*future).Sup.error), NIM_NIL);
}
static N_NIMCALL(void, Marker_tyRef_mO0oVXyu0e0fi1I49aYToDg)(void* p, NI op) {
	tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A* a;
	a = (tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A*)p;
	nimGCvisit((void*)(*a).Sup.callbacks.function.ClE_0, op);
	nimGCvisit((void*)(*a).Sup.callbacks.next, op);
	nimGCvisit((void*)(*a).Sup.error, op);
	nimGCvisit((void*)(*a).Sup.errorStackTrace, op);
}
static N_NIMCALL(void, Marker_tyRef_fS34nJaWsnEzVF1r1vjUzw)(void* p, NI op) {
	tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ* a;
	a = (tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ*)p;
	nimGCvisit((void*)(*a).Sup.callbacks.function.ClE_0, op);
	nimGCvisit((void*)(*a).Sup.callbacks.next, op);
	nimGCvisit((void*)(*a).Sup.error, op);
	nimGCvisit((void*)(*a).Sup.errorStackTrace, op);
}

N_LIB_PRIVATE N_NIMCALL(void, fail_8buDkIPh9aRg7WBcB15eisA)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future, Exception* error) {
	checkFinished_EYgDXwwneJeAEUfXLUHmhg(future);
	(*future).Sup.finished = NIM_TRUE;
	asgnRef((void**) (&(*future).Sup.error), error);
	{
		NimStringDesc* T3_;
		T3_ = (NimStringDesc*)0;
		T3_ = getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(error);
		if (!((T3_) && (T3_)->Sup.len == 0)) goto LA4_;
		asgnRefNoCycle((void**) (&(*future).Sup.errorStackTrace), getStackTrace_ivElcGv1RQQWHS87N1tZ8Q());
	}
	goto LA1_;
	LA4_: ;
	{
		asgnRefNoCycle((void**) (&(*future).Sup.errorStackTrace), getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(error));
	}
	LA1_: ;
	call_Fn9a5LxW5RtXmTFhp4FWrXA((&(*future).Sup.callbacks));
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_ZDnEFECD9b9aKFsuVLxFyzkA_2)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (*future).finished;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A*, newFuture_DEyrm8S1UVT6DvzzxK4dog)(NimStringDesc* fromProc) {
	tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A* result;
	result = (tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A*)0;
	result = (tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A*) newObj((&NTI_mO0oVXyu0e0fi1I49aYToDg_), sizeof(tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A));
	(*result).Sup.Sup.m_type = (&NTI_NsWcx0WwTBxL9ciLNz9c2y3A_);
	(*result).Sup.finished = NIM_FALSE;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, checkFinished_bcojm5j7VL1Elkboo9cPN2A)(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* future) {
}

N_LIB_PRIVATE N_NIMCALL(void, complete_zoYd5H9a5MAQC8SjSmWl9bPw)(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* future, NimStringDesc* val) {
	NimStringDesc* T1_;
	checkFinished_bcojm5j7VL1Elkboo9cPN2A(future);
	T1_ = (NimStringDesc*)0;
	T1_ = (*future).value; (*future).value = copyStringRC1(val);
	if (T1_) nimGCunrefNoCycle(T1_);
	(*future).Sup.finished = NIM_TRUE;
	call_Fn9a5LxW5RtXmTFhp4FWrXA((&(*future).Sup.callbacks));
}

N_LIB_PRIVATE N_NIMCALL(void, fail_hAtKtNFNWBzp4m9cfjyrR5A)(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* future, Exception* error) {
	checkFinished_bcojm5j7VL1Elkboo9cPN2A(future);
	(*future).Sup.finished = NIM_TRUE;
	asgnRef((void**) (&(*future).Sup.error), error);
	{
		NimStringDesc* T3_;
		T3_ = (NimStringDesc*)0;
		T3_ = getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(error);
		if (!((T3_) && (T3_)->Sup.len == 0)) goto LA4_;
		asgnRefNoCycle((void**) (&(*future).Sup.errorStackTrace), getStackTrace_ivElcGv1RQQWHS87N1tZ8Q());
	}
	goto LA1_;
	LA4_: ;
	{
		asgnRefNoCycle((void**) (&(*future).Sup.errorStackTrace), getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(error));
	}
	LA1_: ;
	call_Fn9a5LxW5RtXmTFhp4FWrXA((&(*future).Sup.callbacks));
}

N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace_bcojm5j7VL1Elkboo9cPN2A_2)(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* future) {
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, read_j9cbdpE8x9bVebNlOUd9ae5qA)(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* future) {
	NimStringDesc* result;
	tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* fut;
{	result = (NimStringDesc*)0;
	fut = future;
	{
		if (!(*fut).Sup.finished) goto LA3_;
		{
			if (!!(((*fut).Sup.error == NIM_NIL))) goto LA7_;
			injectStacktrace_bcojm5j7VL1Elkboo9cPN2A_2(fut);
			raiseException((Exception*)(*fut).Sup.error, "Exception");
		}
		LA7_: ;
		result = copyString((*fut).value);
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T10_;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		T10_ = (NimStringDesc*)0;
		T10_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_10));
		if (T10_) nimGCunrefNoCycle(T10_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "ValueError");
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, checkFinished_RdmPOyPwbBvDPzZVjkDhkg)(tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A* future) {
}

N_LIB_PRIVATE N_NIMCALL(void, complete_emI57nQu9cMz39bXe7NOXsog)(tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A* future, NIM_BOOL val) {
	checkFinished_RdmPOyPwbBvDPzZVjkDhkg(future);
	(*future).value = val;
	(*future).Sup.finished = NIM_TRUE;
	call_Fn9a5LxW5RtXmTFhp4FWrXA((&(*future).Sup.callbacks));
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_X3gbiY6whgIbIDdmnek1IA)(tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A* future) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (*future).Sup.finished;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, fail_duDZ5lVhPags9bN9bnzUvMaw)(tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A* future, Exception* error) {
	checkFinished_RdmPOyPwbBvDPzZVjkDhkg(future);
	(*future).Sup.finished = NIM_TRUE;
	asgnRef((void**) (&(*future).Sup.error), error);
	{
		NimStringDesc* T3_;
		T3_ = (NimStringDesc*)0;
		T3_ = getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(error);
		if (!((T3_) && (T3_)->Sup.len == 0)) goto LA4_;
		asgnRefNoCycle((void**) (&(*future).Sup.errorStackTrace), getStackTrace_ivElcGv1RQQWHS87N1tZ8Q());
	}
	goto LA1_;
	LA4_: ;
	{
		asgnRefNoCycle((void**) (&(*future).Sup.errorStackTrace), getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(error));
	}
	LA1_: ;
	call_Fn9a5LxW5RtXmTFhp4FWrXA((&(*future).Sup.callbacks));
}

N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace_RdmPOyPwbBvDPzZVjkDhkg_2)(tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A* future) {
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, read_X3gbiY6whgIbIDdmnek1IA_2)(tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A* future) {
	NIM_BOOL result;
	tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A* fut;
{	result = (NIM_BOOL)0;
	fut = future;
	{
		if (!(*fut).Sup.finished) goto LA3_;
		{
			if (!!(((*fut).Sup.error == NIM_NIL))) goto LA7_;
			injectStacktrace_RdmPOyPwbBvDPzZVjkDhkg_2(fut);
			raiseException((Exception*)(*fut).Sup.error, "Exception");
		}
		LA7_: ;
		result = (*fut).value;
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T10_;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		T10_ = (NimStringDesc*)0;
		T10_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_10));
		if (T10_) nimGCunrefNoCycle(T10_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "ValueError");
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ*, newFuture_5ixOajxj8YN5jAxeXZzGTw)(NimStringDesc* fromProc) {
	tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ* result;
	result = (tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ*)0;
	result = (tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ*) newObj((&NTI_fS34nJaWsnEzVF1r1vjUzw_), sizeof(tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ));
	(*result).Sup.Sup.m_type = (&NTI_KNdXp3d84rAXqWxjhTR9aFQ_);
	(*result).Sup.finished = NIM_FALSE;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, checkFinished_DFFruFX8VfzZKt1pjlpVBg)(tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ* future) {
}

N_LIB_PRIVATE N_NIMCALL(void, complete_rqmfICbsG8zaMmva4T4xIg)(tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ* future, NI val) {
	checkFinished_DFFruFX8VfzZKt1pjlpVBg(future);
	(*future).value = val;
	(*future).Sup.finished = NIM_TRUE;
	call_Fn9a5LxW5RtXmTFhp4FWrXA((&(*future).Sup.callbacks));
}

N_LIB_PRIVATE N_NIMCALL(void, fail_g08I18yZcN6gyflQeirf0w)(tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ* future, Exception* error) {
	checkFinished_DFFruFX8VfzZKt1pjlpVBg(future);
	(*future).Sup.finished = NIM_TRUE;
	asgnRef((void**) (&(*future).Sup.error), error);
	{
		NimStringDesc* T3_;
		T3_ = (NimStringDesc*)0;
		T3_ = getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(error);
		if (!((T3_) && (T3_)->Sup.len == 0)) goto LA4_;
		asgnRefNoCycle((void**) (&(*future).Sup.errorStackTrace), getStackTrace_ivElcGv1RQQWHS87N1tZ8Q());
	}
	goto LA1_;
	LA4_: ;
	{
		asgnRefNoCycle((void**) (&(*future).Sup.errorStackTrace), getStackTrace_OenGRUrwbq9c3AFUxAFv9cuA(error));
	}
	LA1_: ;
	call_Fn9a5LxW5RtXmTFhp4FWrXA((&(*future).Sup.callbacks));
}

N_LIB_PRIVATE N_NIMCALL(void, injectStacktrace_DFFruFX8VfzZKt1pjlpVBg_2)(tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ* future) {
}

N_LIB_PRIVATE N_NIMCALL(NI, read_4NOxxpXfTo1DJap5zqepHw)(tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ* future) {
	NI result;
	tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ* fut;
{	result = (NI)0;
	fut = future;
	{
		if (!(*fut).Sup.finished) goto LA3_;
		{
			if (!!(((*fut).Sup.error == NIM_NIL))) goto LA7_;
			injectStacktrace_DFFruFX8VfzZKt1pjlpVBg_2(fut);
			raiseException((Exception*)(*fut).Sup.error, "Exception");
		}
		LA7_: ;
		result = (*fut).value;
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T10_;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		T10_ = (NimStringDesc*)0;
		T10_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_10));
		if (T10_) nimGCunrefNoCycle(T10_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "ValueError");
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, complete_IYlv1isxd9cipNbn0G89cn6A)(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* future) {
	checkFinished_bcojm5j7VL1Elkboo9cPN2A(future);
	(*future).Sup.finished = NIM_TRUE;
	call_Fn9a5LxW5RtXmTFhp4FWrXA((&(*future).Sup.callbacks));
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_HXF0V9abgdXSOs9c5xdew5UA)(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* future) {
	NIM_BOOL result;
	tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* T1_;
	result = (NIM_BOOL)0;
	T1_ = (tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*)0;
	T1_ = &future->Sup;
	result = (*T1_).finished;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_sh9bNYcdijGaymAEZhFGMSg)(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw* future) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (*future).Sup.finished;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_HXF0V9abgdXSOs9c5xdew5UA_2)(tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A* future) {
	NIM_BOOL result;
	tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* T1_;
	result = (NIM_BOOL)0;
	T1_ = (tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*)0;
	T1_ = &future->Sup;
	result = (*T1_).finished;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, checkFinished_OTFrALKjyNsZ6wzqd22kQQ)(tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A* future) {
}

N_LIB_PRIVATE N_NIMCALL(void, complete_IYlv1isxd9cipNbn0G89cn6A_2)(tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A* future) {
	checkFinished_OTFrALKjyNsZ6wzqd22kQQ(future);
	(*future).Sup.finished = NIM_TRUE;
	call_Fn9a5LxW5RtXmTFhp4FWrXA((&(*future).Sup.callbacks));
}
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncfuturesInit000)(void) {
nimRegisterThreadLocalMarker(TM_vnqLhdH9cCREQ2r9aXVOqbvQ_3);
}

NIM_EXTERNC N_NOINLINE(void, stdlib_asyncfuturesDatInit000)(void) {
static TNimNode* TM_vnqLhdH9cCREQ2r9aXVOqbvQ_2[2];
static TNimNode* TM_vnqLhdH9cCREQ2r9aXVOqbvQ_4[4];
static TNimNode* TM_vnqLhdH9cCREQ2r9aXVOqbvQ_5[2];
static TNimNode* TM_vnqLhdH9cCREQ2r9aXVOqbvQ_6[2];
static TNimNode* TM_vnqLhdH9cCREQ2r9aXVOqbvQ_11[3];
static TNimNode* TM_vnqLhdH9cCREQ2r9aXVOqbvQ_12[2];
static TNimNode* TM_vnqLhdH9cCREQ2r9aXVOqbvQ_15[2];
static TNimNode TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[32];
NTI_Ig6kXMs9apW5862wHsbFhGw_.size = sizeof(tyTuple_2uzTbg8jwom7zHhmM2RgHg);
NTI_Ig6kXMs9apW5862wHsbFhGw_.kind = 18;
NTI_Ig6kXMs9apW5862wHsbFhGw_.base = 0;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_2[0] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[1];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[1].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[1].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field0);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[1].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[1].name = "Field0";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_2[1] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[2];
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.size = sizeof(tyObject_Env_libslashpureslashasyncfuturesdotnim__sO5O0Qy9bzKs0atwA6HUBAw);
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.kind = 17;
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.flags = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[3].len = 0; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[3].kind = 2;
NTI_sO5O0Qy9bzKs0atwA6HUBAw_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[3];
NTI_58EFneeS9at7cA541QCoGAw_.size = sizeof(tyObject_Env_libslashpureslashasyncfuturesdotnim__sO5O0Qy9bzKs0atwA6HUBAw*);
NTI_58EFneeS9at7cA541QCoGAw_.kind = 22;
NTI_58EFneeS9at7cA541QCoGAw_.base = (&NTI_sO5O0Qy9bzKs0atwA6HUBAw_);
NTI_58EFneeS9at7cA541QCoGAw_.marker = Marker_tyRef_58EFneeS9at7cA541QCoGAw;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[2].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[2].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field1);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[2].typ = (&NTI_58EFneeS9at7cA541QCoGAw_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[2].name = "Field1";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[0].len = 2; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[0].kind = 2; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[0].sons = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_2[0];
NTI_Ig6kXMs9apW5862wHsbFhGw_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[0];
NTI_cnXnCCtV9cjKaEq9alHheOFg_.size = sizeof(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg);
NTI_cnXnCCtV9cjKaEq9alHheOFg_.kind = 17;
NTI_cnXnCCtV9cjKaEq9alHheOFg_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_4[0] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[5];
NTI_tKSBWiaJMWD3JZxwqg7UFQ_.size = sizeof(tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ);
NTI_tKSBWiaJMWD3JZxwqg7UFQ_.kind = 18;
NTI_tKSBWiaJMWD3JZxwqg7UFQ_.base = 0;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_5[0] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[7];
NTI_IIomJ6ptE6vfJ5zRbATgkQ_.size = sizeof(tyTuple_2uzTbg8jwom7zHhmM2RgHg);
NTI_IIomJ6ptE6vfJ5zRbATgkQ_.kind = 18;
NTI_IIomJ6ptE6vfJ5zRbATgkQ_.base = 0;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_6[0] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[9];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[9].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[9].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field0);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[9].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[9].name = "Field0";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_6[1] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[10];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[10].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[10].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field1);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[10].typ = (&NTI_58EFneeS9at7cA541QCoGAw_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[10].name = "Field1";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[8].len = 2; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[8].kind = 2; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[8].sons = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_6[0];
NTI_IIomJ6ptE6vfJ5zRbATgkQ_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[8];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[7].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[7].offset = offsetof(tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ, function);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[7].typ = (&NTI_IIomJ6ptE6vfJ5zRbATgkQ_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[7].name = "function";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_5[1] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[11];
NTI_gcUT3qWwCET3KjsqW7m5vQ_.size = sizeof(tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ*);
NTI_gcUT3qWwCET3KjsqW7m5vQ_.kind = 22;
NTI_gcUT3qWwCET3KjsqW7m5vQ_.base = (&NTI_tKSBWiaJMWD3JZxwqg7UFQ_);
NTI_gcUT3qWwCET3KjsqW7m5vQ_.marker = Marker_tyRef_gcUT3qWwCET3KjsqW7m5vQ;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[11].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[11].offset = offsetof(tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ, next);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[11].typ = (&NTI_gcUT3qWwCET3KjsqW7m5vQ_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[11].name = "next";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[6].len = 2; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[6].kind = 2; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[6].sons = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_5[0];
NTI_tKSBWiaJMWD3JZxwqg7UFQ_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[6];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[5].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[5].offset = offsetof(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg, callbacks);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[5].typ = (&NTI_tKSBWiaJMWD3JZxwqg7UFQ_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[5].name = "callbacks";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_4[1] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[12];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[12].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[12].offset = offsetof(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg, finished);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[12].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[12].name = "finished";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_4[2] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[13];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[13].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[13].offset = offsetof(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg, error);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[13].typ = (&NTI_oUKtBcKRdK6usj8RWrlp6A_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[13].name = "error";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_4[3] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[14];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[14].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[14].offset = offsetof(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg, errorStackTrace);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[14].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[14].name = "errorStackTrace";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[4].len = 4; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[4].kind = 2; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[4].sons = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_4[0];
NTI_cnXnCCtV9cjKaEq9alHheOFg_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[4];
NTI_SmxCgsot45ayPNDBegkWAg_.size = sizeof(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg);
NTI_SmxCgsot45ayPNDBegkWAg_.kind = 17;
NTI_SmxCgsot45ayPNDBegkWAg_.base = (&NTI_cnXnCCtV9cjKaEq9alHheOFg_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[15].len = 0; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[15].kind = 2;
NTI_SmxCgsot45ayPNDBegkWAg_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[15];
NTI_zXD0JrbeCNyAaW4E6fB9aqg_.size = sizeof(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*);
NTI_zXD0JrbeCNyAaW4E6fB9aqg_.kind = 22;
NTI_zXD0JrbeCNyAaW4E6fB9aqg_.base = (&NTI_SmxCgsot45ayPNDBegkWAg_);
NTI_zXD0JrbeCNyAaW4E6fB9aqg_.marker = Marker_tyRef_zXD0JrbeCNyAaW4E6fB9aqg;
NTI_tsPdh8RQR6qNUGxaRKf3ag_.size = sizeof(tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag);
NTI_tsPdh8RQR6qNUGxaRKf3ag_.kind = 17;
NTI_tsPdh8RQR6qNUGxaRKf3ag_.base = (&NTI_cnXnCCtV9cjKaEq9alHheOFg_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[16].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[16].offset = offsetof(tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag, value);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[16].typ = (&NTI_O5pdIMCwdzZuqrzSnslnMg_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[16].name = "value";
NTI_tsPdh8RQR6qNUGxaRKf3ag_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[16];
NTI_QiRyy9aiJcSFRns0QePOMuA_.size = sizeof(tyObject_FuturecolonObjectType__tsPdh8RQR6qNUGxaRKf3ag*);
NTI_QiRyy9aiJcSFRns0QePOMuA_.kind = 22;
NTI_QiRyy9aiJcSFRns0QePOMuA_.base = (&NTI_tsPdh8RQR6qNUGxaRKf3ag_);
NTI_QiRyy9aiJcSFRns0QePOMuA_.marker = Marker_tyRef_QiRyy9aiJcSFRns0QePOMuA;
NTI_4aKPZ9bIsx13R9cJcNxCeWmQ_.size = sizeof(tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ);
NTI_4aKPZ9bIsx13R9cJcNxCeWmQ_.kind = 17;
NTI_4aKPZ9bIsx13R9cJcNxCeWmQ_.base = (&NTI_cnXnCCtV9cjKaEq9alHheOFg_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[17].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[17].offset = offsetof(tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ, value);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[17].typ = (&NTI_kGbLvpoD3zbaTmjDA6JF6g_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[17].name = "value";
NTI_4aKPZ9bIsx13R9cJcNxCeWmQ_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[17];
NTI_AfWQ0kHnrE0Z8Fcs059bTew_.size = sizeof(tyObject_FuturecolonObjectType__4aKPZ9bIsx13R9cJcNxCeWmQ*);
NTI_AfWQ0kHnrE0Z8Fcs059bTew_.kind = 22;
NTI_AfWQ0kHnrE0Z8Fcs059bTew_.base = (&NTI_4aKPZ9bIsx13R9cJcNxCeWmQ_);
NTI_AfWQ0kHnrE0Z8Fcs059bTew_.marker = Marker_tyRef_AfWQ0kHnrE0Z8Fcs059bTew;
NTI_ZDLd9bMvg7fd2amVY4Hp9bWg_.size = sizeof(tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg);
NTI_ZDLd9bMvg7fd2amVY4Hp9bWg_.kind = 17;
NTI_ZDLd9bMvg7fd2amVY4Hp9bWg_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_11[0] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[19];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[19].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[19].offset = offsetof(tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg, colonstate_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[19].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[19].name = ":state";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_11[1] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[20];
NTI_8wttzV3rzAH1IXkaO7bCyw_.size = sizeof(tyTuple_2uzTbg8jwom7zHhmM2RgHg);
NTI_8wttzV3rzAH1IXkaO7bCyw_.kind = 18;
NTI_8wttzV3rzAH1IXkaO7bCyw_.base = 0;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_12[0] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[22];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[22].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[22].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field0);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[22].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[22].name = "Field0";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_12[1] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[23];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[23].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[23].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field1);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[23].typ = (&NTI_58EFneeS9at7cA541QCoGAw_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[23].name = "Field1";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[21].len = 2; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[21].kind = 2; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[21].sons = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_12[0];
NTI_8wttzV3rzAH1IXkaO7bCyw_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[21];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[20].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[20].offset = offsetof(tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg, cb1);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[20].typ = (&NTI_8wttzV3rzAH1IXkaO7bCyw_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[20].name = "cb1";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_11[2] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[24];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[24].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[24].offset = offsetof(tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg, future2);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[24].typ = (&NTI_AfWQ0kHnrE0Z8Fcs059bTew_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[24].name = "future2";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[18].len = 3; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[18].kind = 2; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[18].sons = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_11[0];
NTI_ZDLd9bMvg7fd2amVY4Hp9bWg_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[18];
NTI_mwHddAmnKJ7dYAg59auCvrA_.size = sizeof(tyObject_Env_libslashpureslashasyncfuturesdotnim__ZDLd9bMvg7fd2amVY4Hp9bWg*);
NTI_mwHddAmnKJ7dYAg59auCvrA_.kind = 22;
NTI_mwHddAmnKJ7dYAg59auCvrA_.base = (&NTI_ZDLd9bMvg7fd2amVY4Hp9bWg_);
NTI_mwHddAmnKJ7dYAg59auCvrA_.marker = Marker_tyRef_mwHddAmnKJ7dYAg59auCvrA;
NTI_W9ac4kEPq6nRQuOCYEsC6nQ_.size = sizeof(tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ);
NTI_W9ac4kEPq6nRQuOCYEsC6nQ_.kind = 17;
NTI_W9ac4kEPq6nRQuOCYEsC6nQ_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_15[0] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[26];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[26].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[26].offset = offsetof(tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ, colonstate_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[26].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[26].name = ":state";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_15[1] = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[27];
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[27].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[27].offset = offsetof(tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ, future1);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[27].typ = (&NTI_zXD0JrbeCNyAaW4E6fB9aqg_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[27].name = "future1";
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[25].len = 2; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[25].kind = 2; TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[25].sons = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_15[0];
NTI_W9ac4kEPq6nRQuOCYEsC6nQ_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[25];
NTI_BIMSEViDEmmSlRRPmCHvhA_.size = sizeof(tyObject_Env_libslashpureslashasyncfuturesdotnim__W9ac4kEPq6nRQuOCYEsC6nQ*);
NTI_BIMSEViDEmmSlRRPmCHvhA_.kind = 22;
NTI_BIMSEViDEmmSlRRPmCHvhA_.base = (&NTI_W9ac4kEPq6nRQuOCYEsC6nQ_);
NTI_BIMSEViDEmmSlRRPmCHvhA_.marker = Marker_tyRef_BIMSEViDEmmSlRRPmCHvhA;
NTI_xfdVCtBDWltkbfIr9bhAe7A_.size = sizeof(tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A);
NTI_xfdVCtBDWltkbfIr9bhAe7A_.kind = 17;
NTI_xfdVCtBDWltkbfIr9bhAe7A_.base = (&NTI_cnXnCCtV9cjKaEq9alHheOFg_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[28].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[28].offset = offsetof(tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A, value);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[28].typ = (&NTI_1Wfxxtqzahm0R6lueM9aQmQ_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[28].name = "value";
NTI_xfdVCtBDWltkbfIr9bhAe7A_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[28];
NTI_LfThFRgN4RNCjdx5FyKokA_.size = sizeof(tyObject_FuturecolonObjectType__xfdVCtBDWltkbfIr9bhAe7A*);
NTI_LfThFRgN4RNCjdx5FyKokA_.kind = 22;
NTI_LfThFRgN4RNCjdx5FyKokA_.base = (&NTI_xfdVCtBDWltkbfIr9bhAe7A_);
NTI_LfThFRgN4RNCjdx5FyKokA_.marker = Marker_tyRef_LfThFRgN4RNCjdx5FyKokA;
NTI_80u9bn9aLY6K9bjx4fUTV9axAw_.size = sizeof(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw);
NTI_80u9bn9aLY6K9bjx4fUTV9axAw_.kind = 17;
NTI_80u9bn9aLY6K9bjx4fUTV9axAw_.base = (&NTI_cnXnCCtV9cjKaEq9alHheOFg_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[29].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[29].offset = offsetof(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw, value);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[29].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[29].name = "value";
NTI_80u9bn9aLY6K9bjx4fUTV9axAw_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[29];
NTI_IPdYES9cLWlRlcD0lECASkA_.size = sizeof(tyObject_FuturecolonObjectType__80u9bn9aLY6K9bjx4fUTV9axAw*);
NTI_IPdYES9cLWlRlcD0lECASkA_.kind = 22;
NTI_IPdYES9cLWlRlcD0lECASkA_.base = (&NTI_80u9bn9aLY6K9bjx4fUTV9axAw_);
NTI_IPdYES9cLWlRlcD0lECASkA_.marker = Marker_tyRef_IPdYES9cLWlRlcD0lECASkA;
NTI_NsWcx0WwTBxL9ciLNz9c2y3A_.size = sizeof(tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A);
NTI_NsWcx0WwTBxL9ciLNz9c2y3A_.kind = 17;
NTI_NsWcx0WwTBxL9ciLNz9c2y3A_.base = (&NTI_cnXnCCtV9cjKaEq9alHheOFg_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[30].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[30].offset = offsetof(tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A, value);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[30].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[30].name = "value";
NTI_NsWcx0WwTBxL9ciLNz9c2y3A_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[30];
NTI_mO0oVXyu0e0fi1I49aYToDg_.size = sizeof(tyObject_FuturecolonObjectType__NsWcx0WwTBxL9ciLNz9c2y3A*);
NTI_mO0oVXyu0e0fi1I49aYToDg_.kind = 22;
NTI_mO0oVXyu0e0fi1I49aYToDg_.base = (&NTI_NsWcx0WwTBxL9ciLNz9c2y3A_);
NTI_mO0oVXyu0e0fi1I49aYToDg_.marker = Marker_tyRef_mO0oVXyu0e0fi1I49aYToDg;
NTI_KNdXp3d84rAXqWxjhTR9aFQ_.size = sizeof(tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ);
NTI_KNdXp3d84rAXqWxjhTR9aFQ_.kind = 17;
NTI_KNdXp3d84rAXqWxjhTR9aFQ_.base = (&NTI_cnXnCCtV9cjKaEq9alHheOFg_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[31].kind = 1;
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[31].offset = offsetof(tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ, value);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[31].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[31].name = "value";
NTI_KNdXp3d84rAXqWxjhTR9aFQ_.node = &TM_vnqLhdH9cCREQ2r9aXVOqbvQ_0[31];
NTI_fS34nJaWsnEzVF1r1vjUzw_.size = sizeof(tyObject_FuturecolonObjectType__KNdXp3d84rAXqWxjhTR9aFQ*);
NTI_fS34nJaWsnEzVF1r1vjUzw_.kind = 22;
NTI_fS34nJaWsnEzVF1r1vjUzw_.base = (&NTI_KNdXp3d84rAXqWxjhTR9aFQ_);
NTI_fS34nJaWsnEzVF1r1vjUzw_.marker = Marker_tyRef_fS34nJaWsnEzVF1r1vjUzw;
}

