/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c -w -O3 -fno-strict-aliasing  -I/home/kuro/.choosenim/toolchains/nim-0.18.0/lib -o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_uri.o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_uri.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ {
NimStringDesc* scheme;
NimStringDesc* username;
NimStringDesc* password;
NimStringDesc* hostname;
NimStringDesc* port;
NimStringDesc* path;
NimStringDesc* query;
NimStringDesc* anchor;
NIM_BOOL opaque;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, resetUri_p9buM2dTitsqXTMz6vOVUyQ)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* uri);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, parsePath_Kk9czUCtpspxIGySYVuPs9bQ)(NimStringDesc* uri, NI* i, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* result);
static N_INLINE(NI, parseUntil_zSglkPmqQkVaLkVSiDuiCguri)(NimStringDesc* s, NimStringDesc** token, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw until, NI start);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_LIB_PRIVATE N_NIMCALL(void, parseAuthority_MuG6s2bAvx9cZweCqxUbCdw)(NimStringDesc* authority, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* result);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(NI, parseWhile_nRS4GqEDZ9ccEUkAA5bRWgwuri)(NimStringDesc* s, NimStringDesc** token, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw validChars, NI start);
TNimType NTI_j49bukNPrq747O1GRd4Ng9bQ_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
STRING_LITERAL(TM_VzbRQH9cb1xm1tSKH4PwBSw_3, "", 0);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_VzbRQH9cb1xm1tSKH4PwBSw_4 = {
0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x80,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_VzbRQH9cb1xm1tSKH4PwBSw_5, "mailto", 6);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_VzbRQH9cb1xm1tSKH4PwBSw_6 = {
0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_VzbRQH9cb1xm1tSKH4PwBSw_7 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_VzbRQH9cb1xm1tSKH4PwBSw_8 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x68, 0xFF, 0x03,
0xFE, 0xFF, 0xFF, 0x07, 0xFE, 0xFF, 0xFF, 0x07,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_VzbRQH9cb1xm1tSKH4PwBSw_9 = {
0x00, 0x00, 0x00, 0x00, 0x08, 0x80, 0x00, 0x80,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;

N_LIB_PRIVATE N_NIMCALL(void, initUri_KjX0htiF0llidA9bDLRUx0g)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* Result) {
	genericReset((void*)Result, (&NTI_j49bukNPrq747O1GRd4Ng9bQ_));
	genericReset((void*)Result, (&NTI_j49bukNPrq747O1GRd4Ng9bQ_));
	unsureAsgnRef((void**) (&(*Result).scheme), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_3)));
	unsureAsgnRef((void**) (&(*Result).username), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_3)));
	unsureAsgnRef((void**) (&(*Result).password), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_3)));
	unsureAsgnRef((void**) (&(*Result).hostname), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_3)));
	unsureAsgnRef((void**) (&(*Result).port), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_3)));
	unsureAsgnRef((void**) (&(*Result).path), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_3)));
	unsureAsgnRef((void**) (&(*Result).query), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_3)));
	unsureAsgnRef((void**) (&(*Result).anchor), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_3)));
}

N_LIB_PRIVATE N_NIMCALL(void, resetUri_p9buM2dTitsqXTMz6vOVUyQ)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* uri) {
	(*uri).scheme = setLengthStr((*uri).scheme, ((NI) 0));
	(*uri).username = setLengthStr((*uri).username, ((NI) 0));
	(*uri).password = setLengthStr((*uri).password, ((NI) 0));
	(*uri).hostname = setLengthStr((*uri).hostname, ((NI) 0));
	(*uri).port = setLengthStr((*uri).port, ((NI) 0));
	(*uri).path = setLengthStr((*uri).path, ((NI) 0));
	(*uri).query = setLengthStr((*uri).query, ((NI) 0));
	(*uri).anchor = setLengthStr((*uri).anchor, ((NI) 0));
	(*uri).opaque = NIM_FALSE;
}

static N_INLINE(NI, parseUntil_zSglkPmqQkVaLkVSiDuiCguri)(NimStringDesc* s, NimStringDesc** token, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw until, NI start) {
	NI result;
	NI i;
	result = (NI)0;
	i = start;
	{
		while (1) {
			NIM_BOOL T3_;
			T3_ = (NIM_BOOL)0;
			T3_ = (i < (s ? s->Sup.len : 0));
			if (!(T3_)) goto LA4_;
			T3_ = !(((until[(NU)(((NU8)(s->data[i])))>>3] &(1U<<((NU)(((NU8)(s->data[i])))&7U)))!=0));
			LA4_: ;
			if (!T3_) goto LA2;
			i += ((NI) 1);
		} LA2: ;
	}
	result = (NI)(i - start);
	unsureAsgnRef((void**) (&(*token)), copyStrLast(s, start, (NI)(i - ((NI) 1))));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, parseAuthority_MuG6s2bAvx9cZweCqxUbCdw)(NimStringDesc* authority, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* result) {
	NI i;
	NIM_BOOL inPort;
	NIM_BOOL inIPv6;
	i = ((NI) 0);
	inPort = NIM_FALSE;
	inIPv6 = NIM_FALSE;
	{
		while (1) {
			switch (((NU8)(authority->data[i]))) {
			case 64:
			{
				NimStringDesc* T4_;
				NimStringDesc* T5_;
				T4_ = (NimStringDesc*)0;
				T4_ = (*result).password;
				unsureAsgnRef((void**) (&(*result).password), (*result).port);
				unsureAsgnRef((void**) (&(*result).port), T4_);
				(*result).port = setLengthStr((*result).port, ((NI) 0));
				T5_ = (NimStringDesc*)0;
				T5_ = (*result).username;
				unsureAsgnRef((void**) (&(*result).username), (*result).hostname);
				unsureAsgnRef((void**) (&(*result).hostname), T5_);
				(*result).hostname = setLengthStr((*result).hostname, ((NI) 0));
				inPort = NIM_FALSE;
			}
			break;
			case 58:
			{
				{
					if (!inIPv6) goto LA9_;
					(*result).hostname = addChar((*result).hostname, authority->data[i]);
				}
				goto LA7_;
				LA9_: ;
				{
					inPort = NIM_TRUE;
				}
				LA7_: ;
			}
			break;
			case 91:
			{
				inIPv6 = NIM_TRUE;
			}
			break;
			case 93:
			{
				inIPv6 = NIM_FALSE;
			}
			break;
			case 0:
			{
				goto LA1;
			}
			break;
			default:
			{
				{
					if (!inPort) goto LA18_;
					(*result).port = addChar((*result).port, authority->data[i]);
				}
				goto LA16_;
				LA18_: ;
				{
					(*result).hostname = addChar((*result).hostname, authority->data[i]);
				}
				LA16_: ;
			}
			break;
			}
			i += ((NI) 1);
		}
	} LA1: ;
}

N_LIB_PRIVATE N_NIMCALL(void, parsePath_Kk9czUCtpspxIGySYVuPs9bQ)(NimStringDesc* uri, NI* i, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* result) {
	NI T1_;
	T1_ = (NI)0;
	T1_ = parseUntil_zSglkPmqQkVaLkVSiDuiCguri(uri, (&(*result).path), TM_VzbRQH9cb1xm1tSKH4PwBSw_4, (*i));
	(*i) += T1_;
	{
		NI T4_;
		T4_ = (NI)0;
		T4_ = nsuCmpIgnoreCase((*result).scheme, ((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_5));
		if (!(T4_ == ((NI) 0))) goto LA5_;
		parseAuthority_MuG6s2bAvx9cZweCqxUbCdw((*result).path, result);
		(*result).path = setLengthStr((*result).path, ((NI) 0));
	}
	LA5_: ;
	{
		NI T11_;
		if (!((NU8)(uri->data[(*i)]) == (NU8)(63))) goto LA9_;
		(*i) += ((NI) 1);
		T11_ = (NI)0;
		T11_ = parseUntil_zSglkPmqQkVaLkVSiDuiCguri(uri, (&(*result).query), TM_VzbRQH9cb1xm1tSKH4PwBSw_6, (*i));
		(*i) += T11_;
	}
	LA9_: ;
	{
		NI T16_;
		if (!((NU8)(uri->data[(*i)]) == (NU8)(35))) goto LA14_;
		(*i) += ((NI) 1);
		T16_ = (NI)0;
		T16_ = parseUntil_zSglkPmqQkVaLkVSiDuiCguri(uri, (&(*result).anchor), TM_VzbRQH9cb1xm1tSKH4PwBSw_7, (*i));
		(*i) += T16_;
	}
	LA14_: ;
}

static N_INLINE(NI, parseWhile_nRS4GqEDZ9ccEUkAA5bRWgwuri)(NimStringDesc* s, NimStringDesc** token, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw validChars, NI start) {
	NI result;
	NI i;
	result = (NI)0;
	i = start;
	{
		while (1) {
			if (!((validChars[(NU)(((NU8)(s->data[i])))>>3] &(1U<<((NU)(((NU8)(s->data[i])))&7U)))!=0)) goto LA2;
			i += ((NI) 1);
		} LA2: ;
	}
	result = (NI)(i - start);
	unsureAsgnRef((void**) (&(*token)), copyStrLast(s, start, (NI)(i - ((NI) 1))));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, parseUri_rSbDZf9caa6pIyn5lw5aylw)(NimStringDesc* uri, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* result) {
	NI i;
	NIM_BOOL doubleSlash;
	NIM_BOOL T1_;
	NI T11_;
{	resetUri_p9buM2dTitsqXTMz6vOVUyQ(result);
	i = ((NI) 0);
	T1_ = (NIM_BOOL)0;
	T1_ = (((NI) 1) < (uri ? uri->Sup.len : 0));
	if (!(T1_)) goto LA2_;
	T1_ = ((NU8)(uri->data[((NI) 1)]) == (NU8)(47));
	LA2_: ;
	doubleSlash = T1_;
	{
		if (!((NU8)(uri->data[i]) == (NU8)(47))) goto LA5_;
		{
			if (!!(doubleSlash)) goto LA9_;
			parsePath_Kk9czUCtpspxIGySYVuPs9bQ(uri, (&i), result);
			goto BeforeRet_;
		}
		LA9_: ;
	}
	LA5_: ;
	T11_ = (NI)0;
	T11_ = parseWhile_nRS4GqEDZ9ccEUkAA5bRWgwuri(uri, (&(*result).scheme), TM_VzbRQH9cb1xm1tSKH4PwBSw_8, i);
	i += T11_;
	{
		NIM_BOOL T14_;
		T14_ = (NIM_BOOL)0;
		T14_ = !(((NU8)(uri->data[i]) == (NU8)(58)));
		if (!(T14_)) goto LA15_;
		T14_ = !(doubleSlash);
		LA15_: ;
		if (!T14_) goto LA16_;
		i = ((NI) 0);
		(*result).scheme = setLengthStr((*result).scheme, ((NI) 0));
		parsePath_Kk9czUCtpspxIGySYVuPs9bQ(uri, (&i), result);
		goto BeforeRet_;
	}
	LA16_: ;
	{
		if (!!(doubleSlash)) goto LA20_;
		i += ((NI) 1);
	}
	LA20_: ;
	{
		NIM_BOOL T24_;
		NimStringDesc* authority;
		NI T28_;
		T24_ = (NIM_BOOL)0;
		T24_ = ((NU8)(uri->data[i]) == (NU8)(47));
		if (!(T24_)) goto LA25_;
		T24_ = ((NU8)(uri->data[(NI)(i + ((NI) 1))]) == (NU8)(47));
		LA25_: ;
		if (!T24_) goto LA26_;
		i += ((NI) 2);
		authority = copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_3));
		T28_ = (NI)0;
		T28_ = parseUntil_zSglkPmqQkVaLkVSiDuiCguri(uri, (&authority), TM_VzbRQH9cb1xm1tSKH4PwBSw_9, i);
		i += T28_;
		{
			if (!(((NI) 0) < (authority ? authority->Sup.len : 0))) goto LA31_;
			parseAuthority_MuG6s2bAvx9cZweCqxUbCdw(authority, result);
		}
		LA31_: ;
	}
	goto LA22_;
	LA26_: ;
	{
		(*result).opaque = NIM_TRUE;
	}
	LA22_: ;
	parsePath_Kk9czUCtpspxIGySYVuPs9bQ(uri, (&i), result);
	}BeforeRet_: ;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_uriInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_uriDatInit000)(void) {
static TNimNode* TM_VzbRQH9cb1xm1tSKH4PwBSw_2[9];
static TNimNode TM_VzbRQH9cb1xm1tSKH4PwBSw_0[10];
NTI_j49bukNPrq747O1GRd4Ng9bQ_.size = sizeof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ);
NTI_j49bukNPrq747O1GRd4Ng9bQ_.kind = 18;
NTI_j49bukNPrq747O1GRd4Ng9bQ_.base = 0;
NTI_j49bukNPrq747O1GRd4Ng9bQ_.flags = 2;
TM_VzbRQH9cb1xm1tSKH4PwBSw_2[0] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[1];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[1].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[1].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, scheme);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[1].name = "scheme";
TM_VzbRQH9cb1xm1tSKH4PwBSw_2[1] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[2];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[2].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[2].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, username);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[2].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[2].name = "username";
TM_VzbRQH9cb1xm1tSKH4PwBSw_2[2] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[3];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[3].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[3].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, password);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[3].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[3].name = "password";
TM_VzbRQH9cb1xm1tSKH4PwBSw_2[3] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[4];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[4].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[4].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, hostname);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[4].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[4].name = "hostname";
TM_VzbRQH9cb1xm1tSKH4PwBSw_2[4] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[5];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[5].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[5].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, port);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[5].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[5].name = "port";
TM_VzbRQH9cb1xm1tSKH4PwBSw_2[5] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[6];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[6].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[6].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, path);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[6].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[6].name = "path";
TM_VzbRQH9cb1xm1tSKH4PwBSw_2[6] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[7];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[7].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[7].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, query);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[7].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[7].name = "query";
TM_VzbRQH9cb1xm1tSKH4PwBSw_2[7] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[8];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[8].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[8].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, anchor);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[8].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[8].name = "anchor";
TM_VzbRQH9cb1xm1tSKH4PwBSw_2[8] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[9];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[9].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[9].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, opaque);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[9].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[9].name = "opaque";
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[0].len = 9; TM_VzbRQH9cb1xm1tSKH4PwBSw_0[0].kind = 2; TM_VzbRQH9cb1xm1tSKH4PwBSw_0[0].sons = &TM_VzbRQH9cb1xm1tSKH4PwBSw_2[0];
NTI_j49bukNPrq747O1GRd4Ng9bQ_.node = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[0];
}

