/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c -w -O3 -fno-strict-aliasing  -I/home/kuro/.choosenim/toolchains/nim-0.18.0/lib -o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_net.o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_net.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w;
typedef struct tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw;
typedef struct tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ;
typedef struct tySequence_8Np6tlClE5az1CyqZdN19bQ tySequence_8Np6tlClE5az1CyqZdN19bQ;
typedef struct tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct RootObj RootObj;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct tyTuple_2uzTbg8jwom7zHhmM2RgHg tyTuple_2uzTbg8jwom7zHhmM2RgHg;
typedef struct tyObject_Env_libslashpureslashnetdotnim__sO5O0Qy9bzKs0atwA6HUBAw tyObject_Env_libslashpureslashnetdotnim__sO5O0Qy9bzKs0atwA6HUBAw;
typedef struct tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg;
typedef struct Exception Exception;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
struct tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ {
tySequence_8Np6tlClE5az1CyqZdN19bQ* data;
NI counter;
};
struct tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w {
tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* context;
tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ referencedData;
tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw* extraInternal;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
typedef struct {
N_NIMCALL_PTR(NimStringDesc*, ClP_0) (NimStringDesc* identity, void* ClE_0);
void* ClE_0;
} tyProc_lRW9cfxqfm1ql4gkxfLReYg;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NimStringDesc* hint, tyTuple_UV3llMMYFckfui8YMBuUZA* Result, void* ClE_0);
void* ClE_0;
} tyProc_nzIUHFubO43GG203VFo9b7A;
struct tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw {
  RootObj Sup;
tyProc_lRW9cfxqfm1ql4gkxfLReYg serverGetPskFunc;
tyProc_nzIUHFubO43GG203VFo9b7A clientGetPskFunc;
};
struct tyTuple_2uzTbg8jwom7zHhmM2RgHg {
void* Field0;
tyObject_Env_libslashpureslashnetdotnim__sO5O0Qy9bzKs0atwA6HUBAw* Field1;
};
typedef NU8 tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ;
typedef NU8 tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg;
typedef NU8 tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg;
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg {
  Exception Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_CDECL_PTR(int, tyProc_cez8YhJI0vaCUcjGg6z4zA) (void);
typedef N_CDECL_PTR(NCSTRING, tyProc_S7DQYB5vODbZUsDBlWEW6g) (int e, NCSTRING buf);
struct tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw {
char dummy;
};
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct tyObject_Env_libslashpureslashnetdotnim__sO5O0Qy9bzKs0atwA6HUBAw {
  RootObj Sup;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_8Np6tlClE5az1CyqZdN19bQ {
  TGenericSeq Sup;
  tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, CRYPTO_malloc_init_oa7FmPCkkUY9cTkSfMQ14ww)(void);
N_LIB_PRIVATE N_NIMCALL(int, SSL_library_init_6SfBfS64wp6JZihQGGrnKg)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, SSL_load_error_strings_G2BDIxFj2W9ajANxAoi8oZA)(void);
N_LIB_PRIVATE N_NIMCALL(void, OpenSSL_add_all_algorithms_G2BDIxFj2W9ajANxAoi8oZA_2)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_QzPNq9adJR1BjBO7O1vHdPQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_LP7l6kWJNPJLySYXWH5AYA)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_P5o3rUTiL8xsonRddvENpA)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError_tNPXXFl9cb3BG0pJKzUn9bew)(void);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_194401_;
TNimType NTI_nNdejAl9bbVbX7sP6RJ4h0w_;
extern TNimType NTI_QQ33RYEe889cv60wm9bVkd8A_;
extern TNimType NTI_J1RbOJyRcRl1E5zDK6YKcQ_;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_QnsPmxexBDpqB7otv3E4Sw_;
TNimType NTI_lRW9cfxqfm1ql4gkxfLReYg_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI_58EFneeS9at7cA541QCoGAw_;
TNimType NTI_nzIUHFubO43GG203VFo9b7A_;
TNimType NTI_QzPNq9adJR1BjBO7O1vHdPQ_;
TNimType NTI_LP7l6kWJNPJLySYXWH5AYA_;
TNimType NTI_4xio0cAXR7XG4pF9bVcpxEg_;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
TNimType NTI_TVh5yj2EpJX5n2o6Cpc8Zg_;
TNimType NTI_P5o3rUTiL8xsonRddvENpA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_cez8YhJI0vaCUcjGg6z4zA Dl_194613_;
extern tyProc_S7DQYB5vODbZUsDBlWEW6g Dl_194607_;
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_2, "SSL_library_init() == 1 ", 24);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_10, "No error reported.", 18);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_11, "", 0);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_12, "Please upgrade your OpenSSL library, it does not support the ne"
"cessary protocols. OpenSSL error is: ", 100);
static N_NIMCALL(void, Marker_tyRef_QzPNq9adJR1BjBO7O1vHdPQ)(void* p, NI op) {
	tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw* a;
	a = (tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw*)p;
	nimGCvisit((void*)(*a).serverGetPskFunc.ClE_0, op);
	nimGCvisit((void*)(*a).clientGetPskFunc.ClE_0, op);
}
static N_NIMCALL(void, Marker_tyRef_LP7l6kWJNPJLySYXWH5AYA)(void* p, NI op) {
	tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w* a;
	a = (tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w*)p;
	nimGCvisit((void*)(*a).referencedData.data, op);
	nimGCvisit((void*)(*a).extraInternal, op);
}

N_LIB_PRIVATE N_NIMCALL(int, toCInt_giy119a5LXErbSf7U1OXa5w)(tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ opt) {
	int result;
	result = (int)0;
	switch (opt) {
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 0):
	{
		result = ((int) 30);
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 1):
	{
		result = ((int) 6);
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 2):
	{
		result = ((int) 1);
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 3):
	{
		result = ((int) 5);
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 4):
	{
		result = ((int) 9);
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 5):
	{
		result = ((int) 10);
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 6):
	{
		result = ((int) 2);
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 7):
	{
		result = ((int) 15);
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 8):
	{
		result = ((int) 1);
	}
	break;
	}
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isDisconnectionError_40p9aaw5rEmIprdUBGKsyYQ)(tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags, NI32 lastError) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T1_ = ((flags &(1U<<((NU)(((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 1))&7U)))!=0);
	if (!(T1_)) goto LA2_;
	T1_ = (lastError == ((NI) 104) || lastError == ((NI) 32) || lastError == ((NI) 102));
	LA2_: ;
	result = T1_;
	return result;
}
static N_NIMCALL(void, Marker_tyRef_P5o3rUTiL8xsonRddvENpA)(void* p, NI op) {
	tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg* a;
	a = (tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(void, raiseSSLError_FW3PG8mj4a3cXPA4EkRemA)(NimStringDesc* s) {
	int err;
	NimStringDesc* errStr;
	NCSTRING T16_;
	tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg* e_3;
	NimStringDesc* T20_;
	{
		tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg* e;
		NimStringDesc* T5_;
		if (!!(((s) && (s)->Sup.len == 0))) goto LA3_;
		e = (tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg*)0;
		e = (tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg*) newObj((&NTI_P5o3rUTiL8xsonRddvENpA_), sizeof(tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg));
		(*e).Sup.Sup.m_type = (&NTI_TVh5yj2EpJX5n2o6Cpc8Zg_);
		T5_ = (NimStringDesc*)0;
		T5_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(s);
		if (T5_) nimGCunrefNoCycle(T5_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "SslError");
	}
	LA3_: ;
	err = Dl_194613_();
	{
		tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg* e_2;
		NimStringDesc* T10_;
		if (!(err == ((NI32) 0))) goto LA8_;
		e_2 = (tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg*)0;
		e_2 = (tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg*) newObj((&NTI_P5o3rUTiL8xsonRddvENpA_), sizeof(tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg));
		(*e_2).Sup.Sup.m_type = (&NTI_TVh5yj2EpJX5n2o6Cpc8Zg_);
		T10_ = (NimStringDesc*)0;
		T10_ = (*e_2).Sup.message; (*e_2).Sup.message = copyStringRC1(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_10));
		if (T10_) nimGCunrefNoCycle(T10_);
		asgnRef((void**) (&(*e_2).Sup.parent), NIM_NIL);
		raiseException((Exception*)e_2, "SslError");
	}
	LA8_: ;
	{
		NI32 T15_;
		if (!(err == ((NI32) -1))) goto LA13_;
		T15_ = (NI32)0;
		T15_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T15_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_11));
	}
	LA13_: ;
	T16_ = (NCSTRING)0;
	T16_ = Dl_194607_(err, NIM_NIL);
	errStr = cstrToNimstr(T16_);
	switch (err) {
	case ((NI) 336032814):
	case ((NI) 336032784):
	{
		NimStringDesc* T18_;
		T18_ = (NimStringDesc*)0;
		T18_ = rawNewString(errStr->Sup.len + 100);
appendString(T18_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_12));
appendString(T18_, errStr);
		errStr = T18_;
	}
	break;
	default:
	{
	}
	break;
	}
	e_3 = (tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg*)0;
	e_3 = (tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg*) newObj((&NTI_P5o3rUTiL8xsonRddvENpA_), sizeof(tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg));
	(*e_3).Sup.Sup.m_type = (&NTI_TVh5yj2EpJX5n2o6Cpc8Zg_);
	T20_ = (NimStringDesc*)0;
	T20_ = (*e_3).Sup.message; (*e_3).Sup.message = copyStringRC1(errStr);
	if (T20_) nimGCunrefNoCycle(T20_);
	asgnRef((void**) (&(*e_3).Sup.parent), NIM_NIL);
	raiseException((Exception*)e_3, "SslError");
}

N_LIB_PRIVATE N_NIMCALL(int, toOSFlags_OfxuUkOMe7cgSmyynuaSLQ)(tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg socketFlags) {
	int result;
	result = (int)0;
	{
		tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg f;
		NI i;
		f = (tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg)0;
		i = ((NI) 0);
		{
			while (1) {
				if (!(i <= ((NI) 1))) goto LA3;
				{
					if (!((socketFlags &(1U<<((NU)(((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) (i)))&7U)))!=0)) goto LA6_;
					f = ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) (i));
					{
						switch (f) {
						case ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 0):
						{
							result = (NI32)(result | ((int) 2));
						}
						break;
						case ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 1):
						{
							goto LA8;
						}
						break;
						}
					} LA8: ;
				}
				LA6_: ;
				i += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void) {
	CRYPTO_malloc_init_oa7FmPCkkUY9cTkSfMQ14ww();
	{
		int T3_;
		T3_ = (int)0;
		T3_ = SSL_library_init_6SfBfS64wp6JZihQGGrnKg();
		if (!!((T3_ == ((NI32) 1)))) goto LA4_;
		raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_2));
	}
	LA4_: ;
	SSL_load_error_strings_G2BDIxFj2W9ajANxAoi8oZA();
	Dl_194401_();
	OpenSSL_add_all_algorithms_G2BDIxFj2W9ajANxAoi8oZA_2();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void) {
static TNimNode* TM_XqsrSBxhOTPgLQ9cX4MmV4A_3[3];
static TNimNode* TM_XqsrSBxhOTPgLQ9cX4MmV4A_4[2];
static TNimNode* TM_XqsrSBxhOTPgLQ9cX4MmV4A_5[2];
static TNimNode* TM_XqsrSBxhOTPgLQ9cX4MmV4A_6[2];
static TNimNode* TM_XqsrSBxhOTPgLQ9cX4MmV4A_7[2];
NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_9;
static char* NIM_CONST TM_XqsrSBxhOTPgLQ9cX4MmV4A_8[2] = {
"Peek", 
"SafeDisconn"};
static TNimNode TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[17];
NTI_nNdejAl9bbVbX7sP6RJ4h0w_.size = sizeof(tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w);
NTI_nNdejAl9bbVbX7sP6RJ4h0w_.kind = 18;
NTI_nNdejAl9bbVbX7sP6RJ4h0w_.base = 0;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_3[0] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[1];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[1].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[1].offset = offsetof(tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w, context);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[1].typ = (&NTI_QQ33RYEe889cv60wm9bVkd8A_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[1].name = "context";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_3[1] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].offset = offsetof(tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w, referencedData);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].typ = (&NTI_J1RbOJyRcRl1E5zDK6YKcQ_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].name = "referencedData";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_3[2] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[3];
NTI_QnsPmxexBDpqB7otv3E4Sw_.size = sizeof(tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw);
NTI_QnsPmxexBDpqB7otv3E4Sw_.kind = 17;
NTI_QnsPmxexBDpqB7otv3E4Sw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_4[0] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5];
NTI_lRW9cfxqfm1ql4gkxfLReYg_.size = sizeof(tyTuple_2uzTbg8jwom7zHhmM2RgHg);
NTI_lRW9cfxqfm1ql4gkxfLReYg_.kind = 18;
NTI_lRW9cfxqfm1ql4gkxfLReYg_.base = 0;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_5[0] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[7];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[7].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[7].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field0);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[7].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[7].name = "Field0";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_5[1] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field1);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8].typ = (&NTI_58EFneeS9at7cA541QCoGAw_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8].name = "Field1";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6].len = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6].kind = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6].sons = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_5[0];
NTI_lRW9cfxqfm1ql4gkxfLReYg_.node = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5].offset = offsetof(tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw, serverGetPskFunc);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5].typ = (&NTI_lRW9cfxqfm1ql4gkxfLReYg_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5].name = "serverGetPskFunc";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_4[1] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9];
NTI_nzIUHFubO43GG203VFo9b7A_.size = sizeof(tyTuple_2uzTbg8jwom7zHhmM2RgHg);
NTI_nzIUHFubO43GG203VFo9b7A_.kind = 18;
NTI_nzIUHFubO43GG203VFo9b7A_.base = 0;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_6[0] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[11];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[11].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[11].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field0);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[11].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[11].name = "Field0";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_6[1] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[12];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[12].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[12].offset = offsetof(tyTuple_2uzTbg8jwom7zHhmM2RgHg, Field1);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[12].typ = (&NTI_58EFneeS9at7cA541QCoGAw_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[12].name = "Field1";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[10].len = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[10].kind = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[10].sons = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_6[0];
NTI_nzIUHFubO43GG203VFo9b7A_.node = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[10];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9].offset = offsetof(tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw, clientGetPskFunc);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9].typ = (&NTI_nzIUHFubO43GG203VFo9b7A_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9].name = "clientGetPskFunc";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[4].len = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[4].kind = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[4].sons = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_4[0];
NTI_QnsPmxexBDpqB7otv3E4Sw_.node = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[4];
NTI_QzPNq9adJR1BjBO7O1vHdPQ_.size = sizeof(tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw*);
NTI_QzPNq9adJR1BjBO7O1vHdPQ_.kind = 22;
NTI_QzPNq9adJR1BjBO7O1vHdPQ_.base = (&NTI_QnsPmxexBDpqB7otv3E4Sw_);
NTI_QzPNq9adJR1BjBO7O1vHdPQ_.marker = Marker_tyRef_QzPNq9adJR1BjBO7O1vHdPQ;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[3].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[3].offset = offsetof(tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w, extraInternal);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[3].typ = (&NTI_QzPNq9adJR1BjBO7O1vHdPQ_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[3].name = "extraInternal";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[0].len = 3; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[0].kind = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[0].sons = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_3[0];
NTI_nNdejAl9bbVbX7sP6RJ4h0w_.node = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[0];
NTI_LP7l6kWJNPJLySYXWH5AYA_.size = sizeof(tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w*);
NTI_LP7l6kWJNPJLySYXWH5AYA_.kind = 22;
NTI_LP7l6kWJNPJLySYXWH5AYA_.base = (&NTI_nNdejAl9bbVbX7sP6RJ4h0w_);
NTI_LP7l6kWJNPJLySYXWH5AYA_.marker = Marker_tyRef_LP7l6kWJNPJLySYXWH5AYA;
NTI_4xio0cAXR7XG4pF9bVcpxEg_.size = sizeof(tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg);
NTI_4xio0cAXR7XG4pF9bVcpxEg_.kind = 14;
NTI_4xio0cAXR7XG4pF9bVcpxEg_.base = 0;
NTI_4xio0cAXR7XG4pF9bVcpxEg_.flags = 3;
for (TM_XqsrSBxhOTPgLQ9cX4MmV4A_9 = 0; TM_XqsrSBxhOTPgLQ9cX4MmV4A_9 < 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_9++) {
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[TM_XqsrSBxhOTPgLQ9cX4MmV4A_9+13].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[TM_XqsrSBxhOTPgLQ9cX4MmV4A_9+13].offset = TM_XqsrSBxhOTPgLQ9cX4MmV4A_9;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[TM_XqsrSBxhOTPgLQ9cX4MmV4A_9+13].name = TM_XqsrSBxhOTPgLQ9cX4MmV4A_8[TM_XqsrSBxhOTPgLQ9cX4MmV4A_9];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_7[TM_XqsrSBxhOTPgLQ9cX4MmV4A_9] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[TM_XqsrSBxhOTPgLQ9cX4MmV4A_9+13];
}
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[15].len = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[15].kind = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[15].sons = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7[0];
NTI_4xio0cAXR7XG4pF9bVcpxEg_.node = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[15];
NTI_TVh5yj2EpJX5n2o6Cpc8Zg_.size = sizeof(tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg);
NTI_TVh5yj2EpJX5n2o6Cpc8Zg_.kind = 17;
NTI_TVh5yj2EpJX5n2o6Cpc8Zg_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[16].len = 0; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[16].kind = 2;
NTI_TVh5yj2EpJX5n2o6Cpc8Zg_.node = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[16];
NTI_P5o3rUTiL8xsonRddvENpA_.size = sizeof(tyObject_SslError_TVh5yj2EpJX5n2o6Cpc8Zg*);
NTI_P5o3rUTiL8xsonRddvENpA_.kind = 22;
NTI_P5o3rUTiL8xsonRddvENpA_.base = (&NTI_TVh5yj2EpJX5n2o6Cpc8Zg_);
NTI_P5o3rUTiL8xsonRddvENpA_.marker = Marker_tyRef_P5o3rUTiL8xsonRddvENpA;
}

