/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c -w -O3 -fno-strict-aliasing  -I/home/kuro/.choosenim/toolchains/nim-0.18.0/lib -o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_openssl.o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_openssl.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(void, tyProc_sYEjOwC8kj9bf3dL1zf0Hrw) (void* a, void* b, void* c);
typedef N_CDECL_PTR(int, tyProc_pduP3uOMtjDyYKG6z4GVFg) (NU64 opts, NU8 settings);
typedef N_CDECL_PTR(int, tyProc_cez8YhJI0vaCUcjGg6z4zA) (void);
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
struct tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw {
char dummy;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef N_CDECL_PTR(int, tyProc_xjxKRHVZXDqdWXw9bunoZ3w) (tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* ssl, NCSTRING buf, int num);
typedef N_CDECL_PTR(int, tyProc_Vff1ipOwDPDGknaRJAdXjA) (tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* b);
typedef N_CDECL_PTR(NCSTRING, tyProc_S7DQYB5vODbZUsDBlWEW6g) (int e, NCSTRING buf);
typedef N_CDECL_PTR(int, tyProc_kxUw9cdxJbPtv0iPyoSbDBQ) (tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* s, int ret_code);
typedef N_CDECL_PTR(void, tyProc_v9chVxaoEEAWoxVjnpYxttA) (tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* ssl, int mode);
typedef N_CDECL_PTR(void, tyProc_e47RoMUolEGMiUlfiZt9abQ) (tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* ssl);
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_LIB_PRIVATE N_CDECL(void*, allocWrapper_dOCq74vif9aY9cU8NjQtl9cGA)(NI size);
N_LIB_PRIVATE N_NOCONV(void*, alloc_sVm4rDImKK2ZDdylByayiA)(NI size);
N_LIB_PRIVATE N_CDECL(void*, reallocWrapper_vx3MhIqKb9bzkva9bMFPV6ow)(void* p, NI newsize);
N_LIB_PRIVATE N_NOCONV(void, dealloc_RCjNtRnHdRYntrcE7YtwWw)(void* p);
N_LIB_PRIVATE N_NOCONV(void*, realloc_y4TzCoc3hQhz9cedxS9cbemA)(void* p, NI newSize);
N_LIB_PRIVATE N_CDECL(void, deallocWrapper_QJcbeeHqNk1bKJd6duVlkw)(void* p);
N_LIB_PRIVATE N_NIMCALL(void*, sslSym_EQ8YhAWM2PbjLxAaHlSXSA)(NimStringDesc* name);
static N_INLINE(void*, thisModule_ret9bRInJ2qEBLpX8MWNrwQopenssl)(void);
N_LIB_PRIVATE N_NIMCALL(void*, loadLib_msQDgsFjzm0yulCoM9bAllw)(void);
N_LIB_PRIVATE N_NIMCALL(void*, symAddr_NHfjIU1Uh0ju9azgMjiSkQA)(void* lib, NCSTRING name);
static N_INLINE(void*, sslModule_ret9bRInJ2qEBLpX8MWNrwQ_2openssl)(void);
N_LIB_PRIVATE N_NIMCALL(void*, loadLibPattern_WEB1hEy1GGlzZ6WVcUBFGA)(NimStringDesc* pattern, NIM_BOOL global_symbols);
static void* TM_SLGpYVEqpFQ7VaPsJH6HIA_2;
tyProc_sYEjOwC8kj9bf3dL1zf0Hrw Dl_194618_;
void* thisMod_BVflfs5GGPI4d1Lan5mHzA;
extern void* thisMod_BVflfs5GGPI4d1Lan5mHzA;
void* sslMod_jjPr6K4VwnmIfXONVVYefQ;
extern void* sslMod_jjPr6K4VwnmIfXONVVYefQ;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_194401_;
TNimType NTI_hZKic6WnTBMq6Usbg49bnhw_;
TNimType NTI_QQ33RYEe889cv60wm9bVkd8A_;
static void* TM_SLGpYVEqpFQ7VaPsJH6HIA_37;
tyProc_xjxKRHVZXDqdWXw9bunoZ3w Dl_195125_;
tyProc_Vff1ipOwDPDGknaRJAdXjA Dl_195106_;
tyProc_xjxKRHVZXDqdWXw9bunoZ3w Dl_195109_;
tyProc_cez8YhJI0vaCUcjGg6z4zA Dl_194613_;
tyProc_S7DQYB5vODbZUsDBlWEW6g Dl_194607_;
tyProc_kxUw9cdxJbPtv0iPyoSbDBQ Dl_194499_;
tyProc_xjxKRHVZXDqdWXw9bunoZ3w Dl_195114_;
tyProc_v9chVxaoEEAWoxVjnpYxttA Dl_194479_;
tyProc_Vff1ipOwDPDGknaRJAdXjA Dl_194476_;
tyProc_e47RoMUolEGMiUlfiZt9abQ Dl_194406_;
tyProc_xjxKRHVZXDqdWXw9bunoZ3w Dl_195135_;
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_4, "libcrypto.so.1.1", 16);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_6, "libcrypto.so.38", 15);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_8, "libcrypto.so.39", 15);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_10, "libcrypto.so.41", 15);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_12, "libcrypto.so.43", 15);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_14, "libcrypto.so.10", 15);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_16, "libcrypto.so.1.0.2", 18);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_18, "libcrypto.so.1.0.1", 18);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_20, "libcrypto.so.1.0.0", 18);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_22, "libcrypto.so.0.9.9", 18);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_24, "libcrypto.so.0.9.8", 18);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_26, "libcrypto.so", 12);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_27, "libcrypto.so(.1.1|.38|.39|.41|.43|.10|.1.0.2|.1.0.1|.1.0.0|.0.9"
".9|.0.9.8|)", 74);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_30, "libssl.so(.1.1|.38|.39|.41|.43|.10|.1.0.2|.1.0.1|.1.0.0|.0.9.9|"
".0.9.8|)", 71);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_31, "OPENSSL_init_ssl", 16);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_32, "SSL_library_init", 16);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_33, "SSL_load_error_strings", 22);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_36, "OPENSSL_add_all_algorithms_conf", 31);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_39, "libssl.so.1.1", 13);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_41, "libssl.so.38", 12);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_43, "libssl.so.39", 12);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_45, "libssl.so.41", 12);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_47, "libssl.so.43", 12);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_49, "libssl.so.10", 12);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_51, "libssl.so.1.0.2", 15);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_53, "libssl.so.1.0.1", 15);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_55, "libssl.so.1.0.0", 15);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_57, "libssl.so.0.9.9", 15);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_59, "libssl.so.0.9.8", 15);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_61, "libssl.so", 9);
STRING_LITERAL(TM_SLGpYVEqpFQ7VaPsJH6HIA_62, "libssl.so(.1.1|.38|.39|.41|.43|.10|.1.0.2|.1.0.1|.1.0.0|.0.9.9|"
".0.9.8|)", 71);

N_LIB_PRIVATE N_CDECL(void*, allocWrapper_dOCq74vif9aY9cU8NjQtl9cGA)(NI size) {
	void* result;
	result = (void*)0;
	result = alloc_sVm4rDImKK2ZDdylByayiA(((NI) (size)));
	return result;
}

N_LIB_PRIVATE N_CDECL(void*, reallocWrapper_vx3MhIqKb9bzkva9bMFPV6ow)(void* p, NI newsize) {
	void* result;
	result = (void*)0;
	{
		if (!(p == NIM_NIL)) goto LA3_;
		{
			if (!(((NI) 0) < newsize)) goto LA7_;
			result = alloc_sVm4rDImKK2ZDdylByayiA(((NI) (newsize)));
		}
		LA7_: ;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newsize == ((NI) 0))) goto LA10_;
		dealloc_RCjNtRnHdRYntrcE7YtwWw(p);
	}
	goto LA1_;
	LA10_: ;
	{
		result = realloc_y4TzCoc3hQhz9cedxS9cbemA(p, ((NI) (newsize)));
	}
	LA1_: ;
	return result;
}

N_LIB_PRIVATE N_CDECL(void, deallocWrapper_QJcbeeHqNk1bKJd6duVlkw)(void* p) {
	{
		if (!!((p == NIM_NIL))) goto LA3_;
		dealloc_RCjNtRnHdRYntrcE7YtwWw(p);
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, CRYPTO_malloc_init_oa7FmPCkkUY9cTkSfMQ14ww)(void) {
	Dl_194618_(allocWrapper_dOCq74vif9aY9cU8NjQtl9cGA, reallocWrapper_vx3MhIqKb9bzkva9bMFPV6ow, deallocWrapper_QJcbeeHqNk1bKJd6duVlkw);
}

static N_INLINE(void*, thisModule_ret9bRInJ2qEBLpX8MWNrwQopenssl)(void) {
	void* result;
	result = (void*)0;
	{
		if (!(thisMod_BVflfs5GGPI4d1Lan5mHzA == 0)) goto LA3_;
		thisMod_BVflfs5GGPI4d1Lan5mHzA = loadLib_msQDgsFjzm0yulCoM9bAllw();
	}
	LA3_: ;
	result = thisMod_BVflfs5GGPI4d1Lan5mHzA;
	return result;
}

static N_INLINE(void*, sslModule_ret9bRInJ2qEBLpX8MWNrwQ_2openssl)(void) {
	void* result;
	result = (void*)0;
	{
		if (!(sslMod_jjPr6K4VwnmIfXONVVYefQ == 0)) goto LA3_;
		sslMod_jjPr6K4VwnmIfXONVVYefQ = loadLibPattern_WEB1hEy1GGlzZ6WVcUBFGA(((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_30), NIM_FALSE);
	}
	LA3_: ;
	result = sslMod_jjPr6K4VwnmIfXONVVYefQ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void*, sslSym_EQ8YhAWM2PbjLxAaHlSXSA)(NimStringDesc* name) {
	void* result;
	void* dl;
	result = (void*)0;
	dl = thisModule_ret9bRInJ2qEBLpX8MWNrwQopenssl();
	{
		if (!!((dl == 0))) goto LA3_;
		result = symAddr_NHfjIU1Uh0ju9azgMjiSkQA(dl, name->data);
	}
	LA3_: ;
	{
		if (!(result == 0)) goto LA7_;
		dl = sslModule_ret9bRInJ2qEBLpX8MWNrwQ_2openssl();
		{
			if (!!((dl == 0))) goto LA11_;
			result = symAddr_NHfjIU1Uh0ju9azgMjiSkQA(dl, name->data);
		}
		LA11_: ;
	}
	LA7_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, SSL_library_init_6SfBfS64wp6JZihQGGrnKg)(void) {
	int result;
	tyProc_pduP3uOMtjDyYKG6z4GVFg theProc;
	void* T1_;
	tyProc_cez8YhJI0vaCUcjGg6z4zA olderProc;
	void* T6_;
{	result = (int)0;
	T1_ = (void*)0;
	T1_ = sslSym_EQ8YhAWM2PbjLxAaHlSXSA(((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_31));
	theProc = ((tyProc_pduP3uOMtjDyYKG6z4GVFg) (T1_));
	{
		if (!!((theProc == 0))) goto LA4_;
		result = theProc(0ULL, ((NU8) 0));
		goto BeforeRet_;
	}
	LA4_: ;
	T6_ = (void*)0;
	T6_ = sslSym_EQ8YhAWM2PbjLxAaHlSXSA(((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_32));
	olderProc = ((tyProc_cez8YhJI0vaCUcjGg6z4zA) (T6_));
	{
		if (!!((olderProc == 0))) goto LA9_;
		result = olderProc();
	}
	LA9_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, SSL_load_error_strings_G2BDIxFj2W9ajANxAoi8oZA)(void) {
	tyProc_ln4kdL5W9bbX4a1xl8nnVXQ theProc;
	void* T1_;
	T1_ = (void*)0;
	T1_ = sslSym_EQ8YhAWM2PbjLxAaHlSXSA(((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_33));
	theProc = ((tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (T1_));
	{
		if (!!((theProc == 0))) goto LA4_;
		theProc();
	}
	LA4_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, OpenSSL_add_all_algorithms_G2BDIxFj2W9ajANxAoi8oZA_2)(void) {
	tyProc_ln4kdL5W9bbX4a1xl8nnVXQ theProc;
	void* T1_;
	T1_ = (void*)0;
	T1_ = sslSym_EQ8YhAWM2PbjLxAaHlSXSA(((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_36));
	theProc = ((tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (T1_));
	{
		if (!!((theProc == 0))) goto LA4_;
		theProc();
	}
	LA4_: ;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_opensslInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_opensslDatInit000)(void) {
static TNimNode TM_SLGpYVEqpFQ7VaPsJH6HIA_0[1];
NTI_hZKic6WnTBMq6Usbg49bnhw_.size = sizeof(tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw);
NTI_hZKic6WnTBMq6Usbg49bnhw_.kind = 18;
NTI_hZKic6WnTBMq6Usbg49bnhw_.base = 0;
NTI_hZKic6WnTBMq6Usbg49bnhw_.flags = 3;
TM_SLGpYVEqpFQ7VaPsJH6HIA_0[0].len = 0; TM_SLGpYVEqpFQ7VaPsJH6HIA_0[0].kind = 2;
NTI_hZKic6WnTBMq6Usbg49bnhw_.node = &TM_SLGpYVEqpFQ7VaPsJH6HIA_0[0];
NTI_QQ33RYEe889cv60wm9bVkd8A_.size = sizeof(tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw*);
NTI_QQ33RYEe889cv60wm9bVkd8A_.kind = 21;
NTI_QQ33RYEe889cv60wm9bVkd8A_.base = (&NTI_hZKic6WnTBMq6Usbg49bnhw_);
NTI_QQ33RYEe889cv60wm9bVkd8A_.flags = 3;
if (!((TM_SLGpYVEqpFQ7VaPsJH6HIA_2 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_4))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_2 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_6))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_2 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_8))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_2 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_10))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_2 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_12))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_2 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_14))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_2 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_16))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_2 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_18))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_2 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_20))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_2 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_22))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_2 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_24))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_2 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_26))
)) nimLoadLibraryError((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_27);
	Dl_194618_ = (tyProc_sYEjOwC8kj9bf3dL1zf0Hrw) nimGetProcAddr(TM_SLGpYVEqpFQ7VaPsJH6HIA_2, "CRYPTO_set_mem_functions");
	Dl_194401_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_SLGpYVEqpFQ7VaPsJH6HIA_2, "ERR_load_BIO_strings");
if (!((TM_SLGpYVEqpFQ7VaPsJH6HIA_37 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_39))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_37 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_41))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_37 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_43))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_37 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_45))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_37 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_47))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_37 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_49))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_37 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_51))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_37 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_53))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_37 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_55))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_37 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_57))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_37 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_59))
||(TM_SLGpYVEqpFQ7VaPsJH6HIA_37 = nimLoadLibrary((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_61))
)) nimLoadLibraryError((NimStringDesc*) &TM_SLGpYVEqpFQ7VaPsJH6HIA_62);
	Dl_195125_ = (tyProc_xjxKRHVZXDqdWXw9bunoZ3w) nimGetProcAddr(TM_SLGpYVEqpFQ7VaPsJH6HIA_37, "SSL_read");
	Dl_195106_ = (tyProc_Vff1ipOwDPDGknaRJAdXjA) nimGetProcAddr(TM_SLGpYVEqpFQ7VaPsJH6HIA_2, "BIO_ctrl_pending");
	Dl_195109_ = (tyProc_xjxKRHVZXDqdWXw9bunoZ3w) nimGetProcAddr(TM_SLGpYVEqpFQ7VaPsJH6HIA_2, "BIO_read");
	Dl_194613_ = (tyProc_cez8YhJI0vaCUcjGg6z4zA) nimGetProcAddr(TM_SLGpYVEqpFQ7VaPsJH6HIA_2, "ERR_peek_last_error");
	Dl_194607_ = (tyProc_S7DQYB5vODbZUsDBlWEW6g) nimGetProcAddr(TM_SLGpYVEqpFQ7VaPsJH6HIA_2, "ERR_error_string");
	Dl_194499_ = (tyProc_kxUw9cdxJbPtv0iPyoSbDBQ) nimGetProcAddr(TM_SLGpYVEqpFQ7VaPsJH6HIA_37, "SSL_get_error");
	Dl_195114_ = (tyProc_xjxKRHVZXDqdWXw9bunoZ3w) nimGetProcAddr(TM_SLGpYVEqpFQ7VaPsJH6HIA_2, "BIO_write");
	Dl_194479_ = (tyProc_v9chVxaoEEAWoxVjnpYxttA) nimGetProcAddr(TM_SLGpYVEqpFQ7VaPsJH6HIA_37, "SSL_set_shutdown");
	Dl_194476_ = (tyProc_Vff1ipOwDPDGknaRJAdXjA) nimGetProcAddr(TM_SLGpYVEqpFQ7VaPsJH6HIA_37, "SSL_shutdown");
	Dl_194406_ = (tyProc_e47RoMUolEGMiUlfiZt9abQ) nimGetProcAddr(TM_SLGpYVEqpFQ7VaPsJH6HIA_37, "SSL_free");
	Dl_195135_ = (tyProc_xjxKRHVZXDqdWXw9bunoZ3w) nimGetProcAddr(TM_SLGpYVEqpFQ7VaPsJH6HIA_37, "SSL_write");
}

