/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c -w -O3 -fno-strict-aliasing  -I/home/kuro/.choosenim/toolchains/nim-0.18.0/lib -o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_deques.o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_deques.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg;
typedef struct tySequence_WF89a8QyKeDCh4DYWTmSiBg tySequence_WF89a8QyKeDCh4DYWTmSiBg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg {
tySequence_WF89a8QyKeDCh4DYWTmSiBg* data;
NI head;
NI tail;
NI count;
NI mask;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_WF89a8QyKeDCh4DYWTmSiBg {
  TGenericSeq Sup;
  tyProc_IIomJ6ptE6vfJ5zRbATgkQ data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_WF89a8QyKeDCh4DYWTmSiBg)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, expandIfNeeded_yUfcbmt639aJ6tr007RgLpQ)(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg* deq);
N_LIB_PRIVATE N_NIMCALL(tySequence_WF89a8QyKeDCh4DYWTmSiBg*, newSeq_FGDbRopuA4y4tNQGp9cEEsg)(NI len);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
TNimType NTI_lXZKLUMbpAcAUzeVrG09bNg_;
extern TNimType NTI_IIomJ6ptE6vfJ5zRbATgkQ_;
TNimType NTI_WF89a8QyKeDCh4DYWTmSiBg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
static N_NIMCALL(void, Marker_tySequence_WF89a8QyKeDCh4DYWTmSiBg)(void* p, NI op) {
	tySequence_WF89a8QyKeDCh4DYWTmSiBg* a;
	NI T1_;
	a = (tySequence_WF89a8QyKeDCh4DYWTmSiBg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].ClE_0, op);
	}
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(void, expandIfNeeded_yUfcbmt639aJ6tr007RgLpQ)(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg* deq) {
	NI cap;
	cap = (NI)((*deq).mask + ((NI) 1));
	{
		NIM_BOOL T3_;
		tySequence_WF89a8QyKeDCh4DYWTmSiBg* n;
		T3_ = (NIM_BOOL)0;
		T3_ = unlikely((cap <= (*deq).count));
		if (!T3_) goto LA4_;
		n = newSeq_FGDbRopuA4y4tNQGp9cEEsg(((NI) ((NI)(cap * ((NI) 2)))));
		{
			NI i;
			tyProc_IIomJ6ptE6vfJ5zRbATgkQ x;
			tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg colontmp_;
			NI i_2;
			i = (NI)0;
			memset((void*)(&x), 0, sizeof(x));
			memset((void*)(&colontmp_), 0, sizeof(colontmp_));
			memcpy((void*)(&colontmp_), (NIM_CONST void*)(&(*deq)), sizeof(colontmp_));
			i_2 = colontmp_.head;
			{
				NI c;
				NI colontmp__2;
				NI i_3;
				c = (NI)0;
				colontmp__2 = (NI)0;
				colontmp__2 = colontmp_.count;
				i_3 = ((NI) 0);
				{
					while (1) {
						if (!(i_3 < colontmp__2)) goto LA9;
						c = i_3;
						i = c;
						x.ClE_0 = colontmp_.data->data[i_2].ClE_0;
						x.ClP_0 = colontmp_.data->data[i_2].ClP_0;
						asgnRef((void**) (&n->data[i].ClE_0), x.ClE_0);
						n->data[i].ClP_0 = x.ClP_0;
						i_2 = (NI)((NI)(i_2 + ((NI) 1)) & colontmp_.mask);
						i_3 += ((NI) 1);
					} LA9: ;
				}
			}
		}
		unsureAsgnRef((void**) (&(*deq).data), n);
		(*deq).mask = (NI)((NI)(cap * ((NI) 2)) - ((NI) 1));
		(*deq).tail = (*deq).count;
		(*deq).head = ((NI) 0);
	}
	LA4_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, addLast_vqmMzAk3ZYGwAn5hysAc6w)(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg* deq, tyProc_IIomJ6ptE6vfJ5zRbATgkQ item) {
	expandIfNeeded_yUfcbmt639aJ6tr007RgLpQ(deq);
	(*deq).count += ((NI) 1);
	asgnRef((void**) (&(*deq).data->data[(*deq).tail].ClE_0), item.ClE_0);
	(*deq).data->data[(*deq).tail].ClP_0 = item.ClP_0;
	(*deq).tail = (NI)((NI)((*deq).tail + ((NI) 1)) & (*deq).mask);
}

N_LIB_PRIVATE N_NIMCALL(void, initDeque_ReEIfP39bwVCXJ79bSWPO49aw)(NI initialSize, tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg* Result) {
	genericReset((void*)Result, (&NTI_lXZKLUMbpAcAUzeVrG09bNg_));
	(*Result).mask = (NI)(initialSize - ((NI) 1));
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_WF89a8QyKeDCh4DYWTmSiBg*) newSeq((&NTI_WF89a8QyKeDCh4DYWTmSiBg_), ((NI) (initialSize))));
}
NIM_EXTERNC N_NOINLINE(void, stdlib_dequesInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_dequesDatInit000)(void) {
static TNimNode* TM_NdgYN5HU2ty0qMI5oazWyg_2[5];
static TNimNode TM_NdgYN5HU2ty0qMI5oazWyg_0[6];
NTI_lXZKLUMbpAcAUzeVrG09bNg_.size = sizeof(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg);
NTI_lXZKLUMbpAcAUzeVrG09bNg_.kind = 18;
NTI_lXZKLUMbpAcAUzeVrG09bNg_.base = 0;
TM_NdgYN5HU2ty0qMI5oazWyg_2[0] = &TM_NdgYN5HU2ty0qMI5oazWyg_0[1];
NTI_WF89a8QyKeDCh4DYWTmSiBg_.size = sizeof(tySequence_WF89a8QyKeDCh4DYWTmSiBg*);
NTI_WF89a8QyKeDCh4DYWTmSiBg_.kind = 24;
NTI_WF89a8QyKeDCh4DYWTmSiBg_.base = (&NTI_IIomJ6ptE6vfJ5zRbATgkQ_);
NTI_WF89a8QyKeDCh4DYWTmSiBg_.marker = Marker_tySequence_WF89a8QyKeDCh4DYWTmSiBg;
TM_NdgYN5HU2ty0qMI5oazWyg_0[1].kind = 1;
TM_NdgYN5HU2ty0qMI5oazWyg_0[1].offset = offsetof(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg, data);
TM_NdgYN5HU2ty0qMI5oazWyg_0[1].typ = (&NTI_WF89a8QyKeDCh4DYWTmSiBg_);
TM_NdgYN5HU2ty0qMI5oazWyg_0[1].name = "data";
TM_NdgYN5HU2ty0qMI5oazWyg_2[1] = &TM_NdgYN5HU2ty0qMI5oazWyg_0[2];
TM_NdgYN5HU2ty0qMI5oazWyg_0[2].kind = 1;
TM_NdgYN5HU2ty0qMI5oazWyg_0[2].offset = offsetof(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg, head);
TM_NdgYN5HU2ty0qMI5oazWyg_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_NdgYN5HU2ty0qMI5oazWyg_0[2].name = "head";
TM_NdgYN5HU2ty0qMI5oazWyg_2[2] = &TM_NdgYN5HU2ty0qMI5oazWyg_0[3];
TM_NdgYN5HU2ty0qMI5oazWyg_0[3].kind = 1;
TM_NdgYN5HU2ty0qMI5oazWyg_0[3].offset = offsetof(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg, tail);
TM_NdgYN5HU2ty0qMI5oazWyg_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_NdgYN5HU2ty0qMI5oazWyg_0[3].name = "tail";
TM_NdgYN5HU2ty0qMI5oazWyg_2[3] = &TM_NdgYN5HU2ty0qMI5oazWyg_0[4];
TM_NdgYN5HU2ty0qMI5oazWyg_0[4].kind = 1;
TM_NdgYN5HU2ty0qMI5oazWyg_0[4].offset = offsetof(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg, count);
TM_NdgYN5HU2ty0qMI5oazWyg_0[4].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_NdgYN5HU2ty0qMI5oazWyg_0[4].name = "count";
TM_NdgYN5HU2ty0qMI5oazWyg_2[4] = &TM_NdgYN5HU2ty0qMI5oazWyg_0[5];
TM_NdgYN5HU2ty0qMI5oazWyg_0[5].kind = 1;
TM_NdgYN5HU2ty0qMI5oazWyg_0[5].offset = offsetof(tyObject_Deque_lXZKLUMbpAcAUzeVrG09bNg, mask);
TM_NdgYN5HU2ty0qMI5oazWyg_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_NdgYN5HU2ty0qMI5oazWyg_0[5].name = "mask";
TM_NdgYN5HU2ty0qMI5oazWyg_0[0].len = 5; TM_NdgYN5HU2ty0qMI5oazWyg_0[0].kind = 2; TM_NdgYN5HU2ty0qMI5oazWyg_0[0].sons = &TM_NdgYN5HU2ty0qMI5oazWyg_2[0];
NTI_lXZKLUMbpAcAUzeVrG09bNg_.node = &TM_NdgYN5HU2ty0qMI5oazWyg_0[0];
}

