/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c -w -O3 -fno-strict-aliasing  -I/home/kuro/.choosenim/toolchains/nim-0.18.0/lib -o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_selectors.o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_selectors.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/resource.h>
#include <string.h>
#include <sys/epoll.h>
#include <sys/socket.h>
#include <unistd.h>
#include <sys/signalfd.h>
#include <signal.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA;
typedef struct tySequence_lKsVWjYqlRD7eN7MeIt2PQ tySequence_lKsVWjYqlRD7eN7MeIt2PQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ;
typedef struct tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA;
typedef struct tySequence_lBAKjtL5n9bzoWNSpC1Vu3A tySequence_lBAKjtL5n9bzoWNSpC1Vu3A;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_ReadyKey_vOvPQEijZeFv1xAgbh5rNw tyObject_ReadyKey_vOvPQEijZeFv1xAgbh5rNw;
typedef struct tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA {
int epollFD;
NI maxFD;
tySequence_lKsVWjYqlRD7eN7MeIt2PQ* fds;
NI count;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU32 tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg;
struct tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA {
tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* readList;
tySequence_lBAKjtL5n9bzoWNSpC1Vu3A* writeList;
};
struct tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ {
NI ident;
tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg events;
NI param;
tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA data;
};
typedef NU8 tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef struct epoll_event tyArray_FS3tk39b6JCJ6siEPK54vgg[64];
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg {
  Exception Sup;
};
struct tyObject_ReadyKey_vOvPQEijZeFv1xAgbh5rNw {
NI fd;
tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg events;
NI32 errorCode;
};
typedef NU8 tyArray_imubzojaOiPVfv1g8EarTA[48];
typedef unsigned long tyArray_2VPt2Ygo2bc8d9cj8iiKnSg[16];
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (int fd, void* ClE_0);
void* ClE_0;
} tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg;
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_lKsVWjYqlRD7eN7MeIt2PQ {
  TGenericSeq Sup;
  tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ data[SEQ_DECL_SIZE];
};
struct tySequence_lBAKjtL5n9bzoWNSpC1Vu3A {
  TGenericSeq Sup;
  tyProc_9cnjNsE9aOh8FkRG9ccBKTpWg data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_lKsVWjYqlRD7eN7MeIt2PQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_eV1HoGAGYVaJgQ5BCEf67g)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError_tNPXXFl9cb3BG0pJKzUn9bew)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2)(NimStringDesc* msg);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tySequence_lKsVWjYqlRD7eN7MeIt2PQ*, newSeq_ReBdb9aYcfG8RblsLwUT5zw)(NI len);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ)(NI32 message);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, osErrorMsg_yWvWz5V6Ib7QshcAbOiDeQ)(NI32 errorCode);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_NIMCALL(void, Marker_tyRef_yREHAUxoe4I2puy9cJ9cMatg)(void* p, NI op);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(void, raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA)(NimStringDesc* message);
static N_INLINE(NIM_BOOL, contains_Fq69aUQLu9cabGUhLgQogmXgasyncdispatch)(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA* s, NI fd);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
TNimType NTI_VF2QWbk9cEn13YFg9btPwWLA_;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_6oh6PoZxxmRrkez9bmwfPdQ_;
TNimType NTI_nI40bZzTyYVrl763dZ9aHDg_;
TNimType NTI_YIRsZrDT89buh37M5yeUgng_;
extern TNimType NTI_hOYUN4IOpj9adMwn6W7S2VA_;
TNimType NTI_lKsVWjYqlRD7eN7MeIt2PQ_;
TNimType NTI_eV1HoGAGYVaJgQ5BCEf67g_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
TNimType NTI_0onfiGw9bxynoOBJJC01SAg_;
TNimType NTI_yREHAUxoe4I2puy9cJ9cMatg_;
extern TNimType NTI_lBAKjtL5n9bzoWNSpC1Vu3A_;
STRING_LITERAL(TM_ln5vuDpFyDrAqQbYD2g52Q_7, "", 0);
STRING_LITERAL(TM_ln5vuDpFyDrAqQbYD2g52Q_8, "\0120 < maxFD ", 11);
STRING_LITERAL(TM_ln5vuDpFyDrAqQbYD2g52Q_9, " (code: ", 8);
STRING_LITERAL(TM_ln5vuDpFyDrAqQbYD2g52Q_10, ")", 1);
STRING_LITERAL(TM_ln5vuDpFyDrAqQbYD2g52Q_11, "\012not (pkey.ident == 0) ", 23);
STRING_LITERAL(TM_ln5vuDpFyDrAqQbYD2g52Q_12, "Maximum number of descriptors is exhausted!", 43);
STRING_LITERAL(TM_ln5vuDpFyDrAqQbYD2g52Q_13, "Descriptor $# is not registered in the selector!", 48);
STRING_LITERAL(TM_ln5vuDpFyDrAqQbYD2g52Q_14, "pkey.events * maskEvents == {} ", 31);
STRING_LITERAL(TM_ln5vuDpFyDrAqQbYD2g52Q_15, "s.fds[fdi].ident == 0 ", 22);
STRING_LITERAL(TM_ln5vuDpFyDrAqQbYD2g52Q_16, "Descriptor $# already registered", 32);
static N_NIMCALL(void, Marker_tySequence_lKsVWjYqlRD7eN7MeIt2PQ)(void* p, NI op) {
	tySequence_lKsVWjYqlRD7eN7MeIt2PQ* a;
	NI T1_;
	a = (tySequence_lKsVWjYqlRD7eN7MeIt2PQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].data.readList, op);
	nimGCvisit((void*)a->data[T1_].data.writeList, op);
	}
}
static N_NIMCALL(void, Marker_tyRef_eV1HoGAGYVaJgQ5BCEf67g)(void* p, NI op) {
	tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA* a;
	a = (tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA*)p;
	nimGCvisit((void*)(*a).fds, op);
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA*, newSelector_GQHk9ayxNeMCVhLquLKqsaw)(void) {
	tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA* result;
	struct rlimit a;
	NI maxFD;
	int epollFD;
	tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA* T16_;
	result = (tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA*)0;
	memset((void*)(&a), 0, sizeof(a));
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = getrlimit(RLIMIT_NOFILE, (&a));
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_7));
	}
	LA4_: ;
	maxFD = a.rlim_max;
	{
		if (!!((((NI) 0) < maxFD))) goto LA9_;
		raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_8));
	}
	LA9_: ;
	epollFD = epoll_create(((int) 64));
	{
		NI32 T15_;
		if (!(epollFD < ((NI32) 0))) goto LA13_;
		T15_ = (NI32)0;
		T15_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T15_, ((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_7));
	}
	LA13_: ;
	T16_ = (tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA*)0;
	T16_ = (tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA*) newObj((&NTI_eV1HoGAGYVaJgQ5BCEf67g_), sizeof(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA));
	result = T16_;
	(*result).epollFD = epollFD;
	(*result).maxFD = maxFD;
	asgnRef((void**) (&(*result).fds), newSeq_ReBdb9aYcfG8RblsLwUT5zw(((NI) (maxFD))));
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}
static N_NIMCALL(void, Marker_tyRef_yREHAUxoe4I2puy9cJ9cMatg)(void* p, NI op) {
	tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg* a;
	a = (tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ)(NI32 message) {
	NimStringDesc* msg;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg* err;
	tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg* e;
	NimStringDesc* T4_;
	msg = copyString(((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_7));
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = osErrorMsg_yWvWz5V6Ib7QshcAbOiDeQ(message);
	T3_ = (NimStringDesc*)0;
	T3_ = nimIntToStr(((NI) (message)));
	T1_ = rawNewString(T2_->Sup.len + T3_->Sup.len + 9);
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_9));
appendString(T1_, T3_);
appendString(T1_, ((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_10));
	msg = resizeString(msg, T1_->Sup.len + 0);
appendString(msg, T1_);
	e = (tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg*)0;
	e = (tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg*) newObj((&NTI_yREHAUxoe4I2puy9cJ9cMatg_), sizeof(tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg));
	(*e).Sup.Sup.m_type = (&NTI_0onfiGw9bxynoOBJJC01SAg_);
	T4_ = (NimStringDesc*)0;
	T4_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(msg);
	if (T4_) nimGCunrefNoCycle(T4_);
	asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
	err = e;
	raiseException((Exception*)err, "IOSelectorsException");
}

N_LIB_PRIVATE N_NIMCALL(NI, selectInto_u6ZS3exVT9btgsiCfyXHdYQ)(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA* s, NI timeout, tyObject_ReadyKey_vOvPQEijZeFv1xAgbh5rNw* results, NI resultsLen_0) {
	NI result;
	tyArray_FS3tk39b6JCJ6siEPK54vgg resTable;
	NI maxres;
	NI i;
	NI k;
	int count;
	result = (NI)0;
	memset((void*)resTable, 0, sizeof(resTable));
	maxres = ((NI) 64);
	i = (NI)0;
	k = (NI)0;
	{
		if (!(resultsLen_0 < maxres)) goto LA3_;
		maxres = resultsLen_0;
	}
	LA3_: ;
	count = epoll_wait((*s).epollFD, (&resTable[(((NI) 0))- 0]), ((int) (maxres)), ((int) (timeout)));
	{
		NI32 err;
		if (!(count < ((NI32) 0))) goto LA7_;
		result = ((NI) 0);
		err = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		{
			if (!!((err == ((int) 4)))) goto LA11_;
			raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(err);
		}
		LA11_: ;
	}
	goto LA5_;
	LA7_: ;
	{
		if (!(count == ((NI32) 0))) goto LA14_;
		result = ((NI) 0);
	}
	goto LA5_;
	LA14_: ;
	{
		i = ((NI) 0);
		k = ((NI) 0);
		{
			while (1) {
				if (!(i < ((NI) (count)))) goto LA18;
				{
					NI fdi;
					NU32 pevents;
					tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ* pkey;
					tyObject_ReadyKey_vOvPQEijZeFv1xAgbh5rNw rkey;
					fdi = ((NI) (resTable[(i)- 0].data.u64));
					pevents = resTable[(i)- 0].events;
					pkey = (&(*s).fds->data[fdi]);
					{
						if (!!(!(((*pkey).ident == ((NI) 0))))) goto LA22_;
						raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_11));
					}
					LA22_: ;
					memset((void*)(&rkey), 0, sizeof(rkey));
					rkey.fd = fdi;
					rkey.events = 0;
					{
						NIM_BOOL T26_;
						T26_ = (NIM_BOOL)0;
						T26_ = !(((NU32)(pevents & ((NI) 8)) == ((NI) 0)));
						if (T26_) goto LA27_;
						T26_ = !(((NU32)(pevents & ((NI) 16)) == ((NI) 0)));
						LA27_: ;
						if (!T26_) goto LA28_;
						{
							if (!!(((NU32)(pevents & ((NI) 16)) == ((NI) 0)))) goto LA32_;
							rkey.errorCode = ((NI32) 104);
						}
						goto LA30_;
						LA32_: ;
						{
							int error;
							socklen_t size;
							error = (int)0;
							size = ((socklen_t) 4);
							{
								int T37_;
								T37_ = (int)0;
								T37_ = getsockopt(((int) (fdi)), ((int) 1), ((int) 4), ((void*) ((&error))), (&size));
								if (!(T37_ == ((NI32) 0))) goto LA38_;
								rkey.errorCode = error;
							}
							LA38_: ;
						}
						LA30_: ;
						rkey.events |= ((NU32)1)<<((((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 7))%(sizeof(NU32)*8));
					}
					LA28_: ;
					{
						if (!!(((NU32)(pevents & ((NI) 4)) == ((NI) 0)))) goto LA42_;
						rkey.events |= ((NU32)1)<<((((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 1))%(sizeof(NU32)*8));
					}
					LA42_: ;
					{
						if (!!(((NU32)(pevents & ((NI) 1)) == ((NI) 0)))) goto LA46_;
						{
							if (!(((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 0))&31U)))!=0)) goto LA50_;
							rkey.events |= ((NU32)1)<<((((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 0))%(sizeof(NU32)*8));
						}
						goto LA48_;
						LA50_: ;
						{
							NU64 data;
							if (!(((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 2))&31U)))!=0)) goto LA53_;
							data = 0ULL;
							{
								NI T57_;
								NI32 T60_;
								T57_ = (NI)0;
								T57_ = read(((int) (fdi)), ((void*) ((&data))), ((NI) 8));
								if (!!((T57_ == ((NI) 8)))) goto LA58_;
								T60_ = (NI32)0;
								T60_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
								raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T60_);
							}
							LA58_: ;
							rkey.events |= ((NU32)1)<<((((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 2))%(sizeof(NU32)*8));
						}
						goto LA48_;
						LA53_: ;
						{
							struct signalfd_siginfo data_2;
							if (!(((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 3))&31U)))!=0)) goto LA62_;
							memset((void*)(&data_2), 0, sizeof(data_2));
							{
								NI T66_;
								NI32 T69_;
								T66_ = (NI)0;
								T66_ = read(((int) (fdi)), ((void*) ((&data_2))), ((NI)sizeof(struct signalfd_siginfo)));
								if (!!((T66_ == ((NI)sizeof(struct signalfd_siginfo))))) goto LA67_;
								T69_ = (NI32)0;
								T69_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
								raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T69_);
							}
							LA67_: ;
							rkey.events |= ((NU32)1)<<((((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 3))%(sizeof(NU32)*8));
						}
						goto LA48_;
						LA62_: ;
						{
							struct signalfd_siginfo data_3;
							if (!(((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 4))&31U)))!=0)) goto LA71_;
							memset((void*)(&data_3), 0, sizeof(data_3));
							{
								NI T75_;
								NI32 T78_;
								T75_ = (NI)0;
								T75_ = read(((int) (fdi)), ((void*) ((&data_3))), ((NI)sizeof(struct signalfd_siginfo)));
								if (!!((T75_ == ((NI)sizeof(struct signalfd_siginfo))))) goto LA76_;
								T78_ = (NI32)0;
								T78_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
								raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T78_);
							}
							LA76_: ;
							{
								if (!(((NI) (data_3.ssi_pid)) == (*pkey).param)) goto LA81_;
								rkey.events |= ((NU32)1)<<((((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 4))%(sizeof(NU32)*8));
							}
							goto LA79_;
							LA81_: ;
							{
								i += ((NI) 1);
								goto LA19;
							}
							LA79_: ;
						}
						goto LA48_;
						LA71_: ;
						{
							NU64 data_4;
							if (!(((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 6))&31U)))!=0)) goto LA85_;
							data_4 = 0ULL;
							{
								NI T89_;
								NI32 err_2;
								T89_ = (NI)0;
								T89_ = read(((int) (fdi)), ((void*) ((&data_4))), ((NI) 8));
								if (!!((T89_ == ((NI) 8)))) goto LA90_;
								err_2 = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
								{
									if (!(err_2 == ((NI32) 11))) goto LA94_;
									i += ((NI) 1);
									goto LA19;
								}
								goto LA92_;
								LA94_: ;
								{
									raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(err_2);
								}
								LA92_: ;
							}
							LA90_: ;
							rkey.events |= ((NU32)1)<<((((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 6))%(sizeof(NU32)*8));
						}
						goto LA48_;
						LA85_: ;
						LA48_: ;
					}
					LA46_: ;
					{
						struct epoll_event epv;
						if (!(((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 8))&31U)))!=0)) goto LA99_;
						memset((void*)(&epv), 0, sizeof(epv));
						{
							int T103_;
							NI32 T106_;
							T103_ = (int)0;
							T103_ = epoll_ctl((*s).epollFD, ((int) 2), ((int) (fdi)), (&epv));
							if (!!((T103_ == ((NI32) 0)))) goto LA104_;
							T106_ = (NI32)0;
							T106_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
							raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T106_);
						}
						LA104_: ;
						(*s).count -= ((NI) 1);
						(*pkey).events |= ((NU32)1)<<((((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 9))%(sizeof(NU32)*8));
					}
					LA99_: ;
					results[k] = rkey;
					k += ((NI) 1);
					i += ((NI) 1);
				} LA19: ;
			} LA18: ;
		}
		result = k;
	}
	LA5_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA)(NimStringDesc* message) {
	NimStringDesc* msg;
	tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg* err;
	tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg* e;
	NimStringDesc* T1_;
	msg = copyString(((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_7));
	msg = resizeString(msg, message->Sup.len + 0);
appendString(msg, message);
	e = (tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg*)0;
	e = (tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg*) newObj((&NTI_yREHAUxoe4I2puy9cJ9cMatg_), sizeof(tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg));
	(*e).Sup.Sup.m_type = (&NTI_0onfiGw9bxynoOBJJC01SAg_);
	T1_ = (NimStringDesc*)0;
	T1_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(msg);
	if (T1_) nimGCunrefNoCycle(T1_);
	asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
	err = e;
	raiseException((Exception*)err, "IOSelectorsException");
}

static N_INLINE(NIM_BOOL, contains_Fq69aUQLu9cabGUhLgQogmXgasyncdispatch)(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA* s, NI fd) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	result = !(((*s).fds->data[fd].ident == ((NI) 0)));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA*, getData_RBB0346cVWa12py3delH9aw)(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA* s, NI fd) {
	tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA* result;
	NI fdi;
	result = (tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA*)0;
	fdi = fd;
	{
		if (!((*s).maxFD <= fdi)) goto LA3_;
		raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA(((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_12));
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = contains_Fq69aUQLu9cabGUhLgQogmXgasyncdispatch(s, fdi);
		if (!T7_) goto LA8_;
		result = (&(*s).fds->data[fdi].data);
	}
	LA8_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, unregister_FDXXvDPySoITcYL9br9c8f6A)(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA* s, NI fd) {
	NI fdi;
	tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ* pkey;
	tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA empty;
	fdi = fd;
	{
		if (!((*s).maxFD <= fdi)) goto LA3_;
		raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA(((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_12));
	}
	LA3_: ;
	pkey = (&(*s).fds->data[fdi]);
	{
		NimStringDesc* T9_;
		NimStringDesc* T10_;
		NimStringDesc* T11_;
		if (!!(!(((*pkey).ident == ((NI) 0))))) goto LA7_;
		T9_ = (NimStringDesc*)0;
		T10_ = (NimStringDesc*)0;
		T10_ = nimIntToStr(fdi);
		T11_ = (NimStringDesc*)0;
		T11_ = nsuFormatSingleElem(((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_13), T10_);
		T9_ = rawNewString(T11_->Sup.len + 23);
appendString(T9_, ((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_11));
appendString(T9_, T11_);
		raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(T9_);
	}
	LA7_: ;
	{
		if (!!(((*pkey).events == 0))) goto LA14_;
		{
			struct epoll_event epv;
			if (!!((((*pkey).events & 3) == 0))) goto LA18_;
			memset((void*)(&epv), 0, sizeof(epv));
			{
				int T22_;
				NI32 T25_;
				T22_ = (int)0;
				T22_ = epoll_ctl((*s).epollFD, ((int) 2), ((int) (fdi)), (&epv));
				if (!!((T22_ == ((NI32) 0)))) goto LA23_;
				T25_ = (NI32)0;
				T25_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
				raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T25_);
			}
			LA23_: ;
			(*s).count -= ((NI) 1);
		}
		goto LA16_;
		LA18_: ;
		{
			if (!(((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 2))&31U)))!=0)) goto LA27_;
			{
				struct epoll_event epv_2;
				if (!!((((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 9))&31U)))!=0))) goto LA31_;
				memset((void*)(&epv_2), 0, sizeof(epv_2));
				{
					int T35_;
					NI32 T38_;
					T35_ = (int)0;
					T35_ = epoll_ctl((*s).epollFD, ((int) 2), ((int) (fdi)), (&epv_2));
					if (!!((T35_ == ((NI32) 0)))) goto LA36_;
					T38_ = (NI32)0;
					T38_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
					raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T38_);
				}
				LA36_: ;
				(*s).count -= ((NI) 1);
			}
			LA31_: ;
			{
				int T41_;
				NI32 T44_;
				T41_ = (int)0;
				T41_ = close(((int) (fdi)));
				if (!!((T41_ == ((NI32) 0)))) goto LA42_;
				T44_ = (NI32)0;
				T44_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
				raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T44_);
			}
			LA42_: ;
		}
		goto LA16_;
		LA27_: ;
		{
			struct epoll_event epv_3;
			sigset_t nmask;
			sigset_t omask;
			int T54_;
			int T55_;
			int T56_;
			if (!(((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 3))&31U)))!=0)) goto LA46_;
			memset((void*)(&epv_3), 0, sizeof(epv_3));
			{
				int T50_;
				NI32 T53_;
				T50_ = (int)0;
				T50_ = epoll_ctl((*s).epollFD, ((int) 2), ((int) (fdi)), (&epv_3));
				if (!!((T50_ == ((NI32) 0)))) goto LA51_;
				T53_ = (NI32)0;
				T53_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
				raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T53_);
			}
			LA51_: ;
			memset((void*)(&nmask), 0, sizeof(nmask));
			memset((void*)(&omask), 0, sizeof(omask));
			T54_ = (int)0;
			T54_ = sigemptyset((&nmask));
			T54_;
			T55_ = (int)0;
			T55_ = sigemptyset((&omask));
			T55_;
			T56_ = (int)0;
			T56_ = sigaddset((&nmask), ((int) ((*s).fds->data[fdi].param)));
			T56_;
			{
				int T59_;
				NI32 T62_;
				T59_ = (int)0;
				T59_ = sigprocmask(((int) 1), (&nmask), (&omask));
				if (!(T59_ == ((NI32) -1))) goto LA60_;
				T62_ = (NI32)0;
				T62_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
				raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T62_);
			}
			LA60_: ;
			(*s).count -= ((NI) 1);
			{
				int T65_;
				NI32 T68_;
				T65_ = (int)0;
				T65_ = close(((int) (fdi)));
				if (!!((T65_ == ((NI32) 0)))) goto LA66_;
				T68_ = (NI32)0;
				T68_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
				raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T68_);
			}
			LA66_: ;
		}
		goto LA16_;
		LA46_: ;
		{
			if (!(((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 4))&31U)))!=0)) goto LA70_;
			{
				struct epoll_event epv_4;
				sigset_t nmask_2;
				sigset_t omask_2;
				int T82_;
				int T83_;
				int T84_;
				if (!!((((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 9))&31U)))!=0))) goto LA74_;
				memset((void*)(&epv_4), 0, sizeof(epv_4));
				{
					int T78_;
					NI32 T81_;
					T78_ = (int)0;
					T78_ = epoll_ctl((*s).epollFD, ((int) 2), ((int) (fdi)), (&epv_4));
					if (!!((T78_ == ((NI32) 0)))) goto LA79_;
					T81_ = (NI32)0;
					T81_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
					raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T81_);
				}
				LA79_: ;
				memset((void*)(&nmask_2), 0, sizeof(nmask_2));
				memset((void*)(&omask_2), 0, sizeof(omask_2));
				T82_ = (int)0;
				T82_ = sigemptyset((&nmask_2));
				T82_;
				T83_ = (int)0;
				T83_ = sigemptyset((&omask_2));
				T83_;
				T84_ = (int)0;
				T84_ = sigaddset((&nmask_2), ((int) 17));
				T84_;
				{
					int T87_;
					NI32 T90_;
					T87_ = (int)0;
					T87_ = sigprocmask(((int) 1), (&nmask_2), (&omask_2));
					if (!(T87_ == ((NI32) -1))) goto LA88_;
					T90_ = (NI32)0;
					T90_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
					raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T90_);
				}
				LA88_: ;
				(*s).count -= ((NI) 1);
			}
			LA74_: ;
			{
				int T93_;
				NI32 T96_;
				T93_ = (int)0;
				T93_ = close(((int) (fdi)));
				if (!!((T93_ == ((NI32) 0)))) goto LA94_;
				T96_ = (NI32)0;
				T96_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
				raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T96_);
			}
			LA94_: ;
		}
		goto LA16_;
		LA70_: ;
		LA16_: ;
	}
	LA14_: ;
	memset((void*)(&empty), 0, sizeof(empty));
	(*pkey).ident = ((NI) 0);
	(*pkey).events = 0;
	genericSeqAssign((&(*pkey).data.readList), empty.readList, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
	genericSeqAssign((&(*pkey).data.writeList), empty.writeList, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
}

N_LIB_PRIVATE N_NIMCALL(void, updateHandle_oJVvb1kZTt9aacXskkHxkLQ)(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA* s, int fd, tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg events) {
	tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg maskEvents;
	NI fdi;
	tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ* pkey;
	maskEvents = 508;
	fdi = ((NI) (fd));
	{
		if (!((*s).maxFD <= fdi)) goto LA3_;
		raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA(((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_12));
	}
	LA3_: ;
	pkey = (&(*s).fds->data[fdi]);
	{
		NimStringDesc* T9_;
		NimStringDesc* T10_;
		NimStringDesc* T11_;
		if (!!(!(((*pkey).ident == ((NI) 0))))) goto LA7_;
		T9_ = (NimStringDesc*)0;
		T10_ = (NimStringDesc*)0;
		T10_ = nimIntToStr(fdi);
		T11_ = (NimStringDesc*)0;
		T11_ = nsuFormatSingleElem(((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_13), T10_);
		T9_ = rawNewString(T11_->Sup.len + 23);
appendString(T9_, ((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_11));
appendString(T9_, T11_);
		raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(T9_);
	}
	LA7_: ;
	{
		if (!!((((*pkey).events & maskEvents) == 0))) goto LA14_;
		raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_14));
	}
	LA14_: ;
	{
		struct epoll_event epv;
		if (!!(((*pkey).events == events))) goto LA18_;
		memset((void*)(&epv), 0, sizeof(epv));
		epv.events = ((NU32) 8192);
		epv.data.u64 = ((NU64) (((NU) (fdi))));
		{
			if (!((events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 0))&31U)))!=0)) goto LA22_;
			epv.events = (NU32)(epv.events | ((NI) 1));
		}
		LA22_: ;
		{
			if (!((events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 1))&31U)))!=0)) goto LA26_;
			epv.events = (NU32)(epv.events | ((NI) 4));
		}
		LA26_: ;
		{
			if (!((*pkey).events == 0)) goto LA30_;
			{
				int T34_;
				NI32 T37_;
				T34_ = (int)0;
				T34_ = epoll_ctl((*s).epollFD, ((int) 1), ((int) (fdi)), (&epv));
				if (!!((T34_ == ((NI32) 0)))) goto LA35_;
				T37_ = (NI32)0;
				T37_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
				raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T37_);
			}
			LA35_: ;
			(*s).count += ((NI) 1);
		}
		goto LA28_;
		LA30_: ;
		{
			{
				if (!!((events == 0))) goto LA41_;
				{
					int T45_;
					NI32 T48_;
					T45_ = (int)0;
					T45_ = epoll_ctl((*s).epollFD, ((int) 3), ((int) (fdi)), (&epv));
					if (!!((T45_ == ((NI32) 0)))) goto LA46_;
					T48_ = (NI32)0;
					T48_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
					raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T48_);
				}
				LA46_: ;
			}
			goto LA39_;
			LA41_: ;
			{
				{
					int T52_;
					NI32 T55_;
					T52_ = (int)0;
					T52_ = epoll_ctl((*s).epollFD, ((int) 2), ((int) (fdi)), (&epv));
					if (!!((T52_ == ((NI32) 0)))) goto LA53_;
					T55_ = (NI32)0;
					T55_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
					raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T55_);
				}
				LA53_: ;
				(*s).count -= ((NI) 1);
			}
			LA39_: ;
		}
		LA28_: ;
		(*pkey).events = events;
	}
	LA18_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, registerHandle_GgwOhhggxqPkAQmnnBmXJA)(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA* s, int fd, tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg events, tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA data) {
	NI fdi;
	tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ* skey;
	fdi = ((NI) (fd));
	{
		if (!((*s).maxFD <= fdi)) goto LA3_;
		raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA(((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_12));
	}
	LA3_: ;
	{
		NimStringDesc* T9_;
		NimStringDesc* T10_;
		NimStringDesc* T11_;
		if (!!(((*s).fds->data[fdi].ident == ((NI) 0)))) goto LA7_;
		T9_ = (NimStringDesc*)0;
		T10_ = (NimStringDesc*)0;
		T10_ = nimIntToStr(fdi);
		T11_ = (NimStringDesc*)0;
		T11_ = nsuFormatSingleElem(((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_16), T10_);
		T9_ = rawNewString(T11_->Sup.len + 22);
appendString(T9_, ((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_15));
appendString(T9_, T11_);
		raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(T9_);
	}
	LA7_: ;
	skey = (&(*s).fds->data[fdi]);
	(*skey).ident = fdi;
	(*skey).events = events;
	(*skey).param = ((NI) 0);
	genericSeqAssign((&(*skey).data.readList), data.readList, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
	genericSeqAssign((&(*skey).data.writeList), data.writeList, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
	{
		struct epoll_event epv;
		if (!!((events == 0))) goto LA14_;
		memset((void*)(&epv), 0, sizeof(epv));
		epv.events = ((NU32) 8192);
		epv.data.u64 = ((NU64) (((NU) (fdi))));
		{
			if (!((events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 0))&31U)))!=0)) goto LA18_;
			epv.events = (NU32)(epv.events | ((NI) 1));
		}
		LA18_: ;
		{
			if (!((events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 1))&31U)))!=0)) goto LA22_;
			epv.events = (NU32)(epv.events | ((NI) 4));
		}
		LA22_: ;
		{
			int T26_;
			NI32 T29_;
			T26_ = (int)0;
			T26_ = epoll_ctl((*s).epollFD, ((int) 1), ((int) (fdi)), (&epv));
			if (!!((T26_ == ((NI32) 0)))) goto LA27_;
			T29_ = (NI32)0;
			T29_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
			raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T29_);
		}
		LA27_: ;
		(*s).count += ((NI) 1);
	}
	LA14_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, unregister_lnP9aLHiiCaMlycdTh4sSSg)(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA* s, int fd) {
	NI fdi;
	tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ* pkey;
	tyObject_AsyncData_hOYUN4IOpj9adMwn6W7S2VA empty;
	fdi = ((NI) (fd));
	{
		if (!((*s).maxFD <= fdi)) goto LA3_;
		raiseIOSelectorsError_o9b1ajHBhCZ9cfHDVe9aM1OwA(((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_12));
	}
	LA3_: ;
	pkey = (&(*s).fds->data[fdi]);
	{
		NimStringDesc* T9_;
		NimStringDesc* T10_;
		NimStringDesc* T11_;
		if (!!(!(((*pkey).ident == ((NI) 0))))) goto LA7_;
		T9_ = (NimStringDesc*)0;
		T10_ = (NimStringDesc*)0;
		T10_ = nimIntToStr(fdi);
		T11_ = (NimStringDesc*)0;
		T11_ = nsuFormatSingleElem(((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_13), T10_);
		T9_ = rawNewString(T11_->Sup.len + 23);
appendString(T9_, ((NimStringDesc*) &TM_ln5vuDpFyDrAqQbYD2g52Q_11));
appendString(T9_, T11_);
		raiseAssert_PpfSiTIeNpMAb9a5o6SglJw_2(T9_);
	}
	LA7_: ;
	{
		if (!!(((*pkey).events == 0))) goto LA14_;
		{
			struct epoll_event epv;
			if (!!((((*pkey).events & 3) == 0))) goto LA18_;
			memset((void*)(&epv), 0, sizeof(epv));
			{
				int T22_;
				NI32 T25_;
				T22_ = (int)0;
				T22_ = epoll_ctl((*s).epollFD, ((int) 2), ((int) (fdi)), (&epv));
				if (!!((T22_ == ((NI32) 0)))) goto LA23_;
				T25_ = (NI32)0;
				T25_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
				raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T25_);
			}
			LA23_: ;
			(*s).count -= ((NI) 1);
		}
		goto LA16_;
		LA18_: ;
		{
			if (!(((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 2))&31U)))!=0)) goto LA27_;
			{
				struct epoll_event epv_2;
				if (!!((((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 9))&31U)))!=0))) goto LA31_;
				memset((void*)(&epv_2), 0, sizeof(epv_2));
				{
					int T35_;
					NI32 T38_;
					T35_ = (int)0;
					T35_ = epoll_ctl((*s).epollFD, ((int) 2), ((int) (fdi)), (&epv_2));
					if (!!((T35_ == ((NI32) 0)))) goto LA36_;
					T38_ = (NI32)0;
					T38_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
					raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T38_);
				}
				LA36_: ;
				(*s).count -= ((NI) 1);
			}
			LA31_: ;
			{
				int T41_;
				NI32 T44_;
				T41_ = (int)0;
				T41_ = close(((int) (fdi)));
				if (!!((T41_ == ((NI32) 0)))) goto LA42_;
				T44_ = (NI32)0;
				T44_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
				raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T44_);
			}
			LA42_: ;
		}
		goto LA16_;
		LA27_: ;
		{
			struct epoll_event epv_3;
			sigset_t nmask;
			sigset_t omask;
			int T54_;
			int T55_;
			int T56_;
			if (!(((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 3))&31U)))!=0)) goto LA46_;
			memset((void*)(&epv_3), 0, sizeof(epv_3));
			{
				int T50_;
				NI32 T53_;
				T50_ = (int)0;
				T50_ = epoll_ctl((*s).epollFD, ((int) 2), ((int) (fdi)), (&epv_3));
				if (!!((T50_ == ((NI32) 0)))) goto LA51_;
				T53_ = (NI32)0;
				T53_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
				raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T53_);
			}
			LA51_: ;
			memset((void*)(&nmask), 0, sizeof(nmask));
			memset((void*)(&omask), 0, sizeof(omask));
			T54_ = (int)0;
			T54_ = sigemptyset((&nmask));
			T54_;
			T55_ = (int)0;
			T55_ = sigemptyset((&omask));
			T55_;
			T56_ = (int)0;
			T56_ = sigaddset((&nmask), ((int) ((*s).fds->data[fdi].param)));
			T56_;
			{
				int T59_;
				NI32 T62_;
				T59_ = (int)0;
				T59_ = sigprocmask(((int) 1), (&nmask), (&omask));
				if (!(T59_ == ((NI32) -1))) goto LA60_;
				T62_ = (NI32)0;
				T62_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
				raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T62_);
			}
			LA60_: ;
			(*s).count -= ((NI) 1);
			{
				int T65_;
				NI32 T68_;
				T65_ = (int)0;
				T65_ = close(((int) (fdi)));
				if (!!((T65_ == ((NI32) 0)))) goto LA66_;
				T68_ = (NI32)0;
				T68_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
				raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T68_);
			}
			LA66_: ;
		}
		goto LA16_;
		LA46_: ;
		{
			if (!(((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 4))&31U)))!=0)) goto LA70_;
			{
				struct epoll_event epv_4;
				sigset_t nmask_2;
				sigset_t omask_2;
				int T82_;
				int T83_;
				int T84_;
				if (!!((((*pkey).events &(1U<<((NU)(((tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg) 9))&31U)))!=0))) goto LA74_;
				memset((void*)(&epv_4), 0, sizeof(epv_4));
				{
					int T78_;
					NI32 T81_;
					T78_ = (int)0;
					T78_ = epoll_ctl((*s).epollFD, ((int) 2), ((int) (fdi)), (&epv_4));
					if (!!((T78_ == ((NI32) 0)))) goto LA79_;
					T81_ = (NI32)0;
					T81_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
					raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T81_);
				}
				LA79_: ;
				memset((void*)(&nmask_2), 0, sizeof(nmask_2));
				memset((void*)(&omask_2), 0, sizeof(omask_2));
				T82_ = (int)0;
				T82_ = sigemptyset((&nmask_2));
				T82_;
				T83_ = (int)0;
				T83_ = sigemptyset((&omask_2));
				T83_;
				T84_ = (int)0;
				T84_ = sigaddset((&nmask_2), ((int) 17));
				T84_;
				{
					int T87_;
					NI32 T90_;
					T87_ = (int)0;
					T87_ = sigprocmask(((int) 1), (&nmask_2), (&omask_2));
					if (!(T87_ == ((NI32) -1))) goto LA88_;
					T90_ = (NI32)0;
					T90_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
					raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T90_);
				}
				LA88_: ;
				(*s).count -= ((NI) 1);
			}
			LA74_: ;
			{
				int T93_;
				NI32 T96_;
				T93_ = (int)0;
				T93_ = close(((int) (fdi)));
				if (!!((T93_ == ((NI32) 0)))) goto LA94_;
				T96_ = (NI32)0;
				T96_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
				raiseIOSelectorsError_PDJjb10jFW9ce9bI0d9bdexrQ(T96_);
			}
			LA94_: ;
		}
		goto LA16_;
		LA70_: ;
		LA16_: ;
	}
	LA14_: ;
	memset((void*)(&empty), 0, sizeof(empty));
	(*pkey).ident = ((NI) 0);
	(*pkey).events = 0;
	genericSeqAssign((&(*pkey).data.readList), empty.readList, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
	genericSeqAssign((&(*pkey).data.writeList), empty.writeList, (&NTI_lBAKjtL5n9bzoWNSpC1Vu3A_));
}
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit000)(void) {
static TNimNode* TM_ln5vuDpFyDrAqQbYD2g52Q_2[4];
static TNimNode* TM_ln5vuDpFyDrAqQbYD2g52Q_3[4];
static TNimNode* TM_ln5vuDpFyDrAqQbYD2g52Q_4[17];
NI TM_ln5vuDpFyDrAqQbYD2g52Q_6;
static char* NIM_CONST TM_ln5vuDpFyDrAqQbYD2g52Q_5[17] = {
"Read", 
"Write", 
"Timer", 
"Signal", 
"Process", 
"Vnode", 
"User", 
"Error", 
"Oneshot", 
"Finished", 
"VnodeWrite", 
"VnodeDelete", 
"VnodeExtend", 
"VnodeAttrib", 
"VnodeLink", 
"VnodeRename", 
"VnodeRevoke"};
static TNimNode TM_ln5vuDpFyDrAqQbYD2g52Q_0[30];
NTI_VF2QWbk9cEn13YFg9btPwWLA_.size = sizeof(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA);
NTI_VF2QWbk9cEn13YFg9btPwWLA_.kind = 18;
NTI_VF2QWbk9cEn13YFg9btPwWLA_.base = 0;
TM_ln5vuDpFyDrAqQbYD2g52Q_2[0] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[1];
TM_ln5vuDpFyDrAqQbYD2g52Q_0[1].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[1].offset = offsetof(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA, epollFD);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[1].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[1].name = "epollFD";
TM_ln5vuDpFyDrAqQbYD2g52Q_2[1] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[2];
TM_ln5vuDpFyDrAqQbYD2g52Q_0[2].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[2].offset = offsetof(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA, maxFD);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[2].name = "maxFD";
TM_ln5vuDpFyDrAqQbYD2g52Q_2[2] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[3];
NTI_6oh6PoZxxmRrkez9bmwfPdQ_.size = sizeof(tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ);
NTI_6oh6PoZxxmRrkez9bmwfPdQ_.kind = 18;
NTI_6oh6PoZxxmRrkez9bmwfPdQ_.base = 0;
TM_ln5vuDpFyDrAqQbYD2g52Q_3[0] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[5];
TM_ln5vuDpFyDrAqQbYD2g52Q_0[5].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[5].offset = offsetof(tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ, ident);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[5].name = "ident";
TM_ln5vuDpFyDrAqQbYD2g52Q_3[1] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[6];
NTI_nI40bZzTyYVrl763dZ9aHDg_.size = sizeof(tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg);
NTI_nI40bZzTyYVrl763dZ9aHDg_.kind = 14;
NTI_nI40bZzTyYVrl763dZ9aHDg_.base = 0;
NTI_nI40bZzTyYVrl763dZ9aHDg_.flags = 3;
for (TM_ln5vuDpFyDrAqQbYD2g52Q_6 = 0; TM_ln5vuDpFyDrAqQbYD2g52Q_6 < 17; TM_ln5vuDpFyDrAqQbYD2g52Q_6++) {
TM_ln5vuDpFyDrAqQbYD2g52Q_0[TM_ln5vuDpFyDrAqQbYD2g52Q_6+7].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[TM_ln5vuDpFyDrAqQbYD2g52Q_6+7].offset = TM_ln5vuDpFyDrAqQbYD2g52Q_6;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[TM_ln5vuDpFyDrAqQbYD2g52Q_6+7].name = TM_ln5vuDpFyDrAqQbYD2g52Q_5[TM_ln5vuDpFyDrAqQbYD2g52Q_6];
TM_ln5vuDpFyDrAqQbYD2g52Q_4[TM_ln5vuDpFyDrAqQbYD2g52Q_6] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[TM_ln5vuDpFyDrAqQbYD2g52Q_6+7];
}
TM_ln5vuDpFyDrAqQbYD2g52Q_0[24].len = 17; TM_ln5vuDpFyDrAqQbYD2g52Q_0[24].kind = 2; TM_ln5vuDpFyDrAqQbYD2g52Q_0[24].sons = &TM_ln5vuDpFyDrAqQbYD2g52Q_4[0];
NTI_nI40bZzTyYVrl763dZ9aHDg_.node = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[24];
NTI_YIRsZrDT89buh37M5yeUgng_.size = sizeof(tySet_tyEnum_Event_nI40bZzTyYVrl763dZ9aHDg);
NTI_YIRsZrDT89buh37M5yeUgng_.kind = 19;
NTI_YIRsZrDT89buh37M5yeUgng_.base = (&NTI_nI40bZzTyYVrl763dZ9aHDg_);
NTI_YIRsZrDT89buh37M5yeUgng_.flags = 3;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[25].len = 0; TM_ln5vuDpFyDrAqQbYD2g52Q_0[25].kind = 0;
NTI_YIRsZrDT89buh37M5yeUgng_.node = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[25];
TM_ln5vuDpFyDrAqQbYD2g52Q_0[6].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[6].offset = offsetof(tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ, events);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[6].typ = (&NTI_YIRsZrDT89buh37M5yeUgng_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[6].name = "events";
TM_ln5vuDpFyDrAqQbYD2g52Q_3[2] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[26];
TM_ln5vuDpFyDrAqQbYD2g52Q_0[26].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[26].offset = offsetof(tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ, param);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[26].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[26].name = "param";
TM_ln5vuDpFyDrAqQbYD2g52Q_3[3] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[27];
TM_ln5vuDpFyDrAqQbYD2g52Q_0[27].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[27].offset = offsetof(tyObject_SelectorKey_6oh6PoZxxmRrkez9bmwfPdQ, data);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[27].typ = (&NTI_hOYUN4IOpj9adMwn6W7S2VA_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[27].name = "data";
TM_ln5vuDpFyDrAqQbYD2g52Q_0[4].len = 4; TM_ln5vuDpFyDrAqQbYD2g52Q_0[4].kind = 2; TM_ln5vuDpFyDrAqQbYD2g52Q_0[4].sons = &TM_ln5vuDpFyDrAqQbYD2g52Q_3[0];
NTI_6oh6PoZxxmRrkez9bmwfPdQ_.node = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[4];
NTI_lKsVWjYqlRD7eN7MeIt2PQ_.size = sizeof(tySequence_lKsVWjYqlRD7eN7MeIt2PQ*);
NTI_lKsVWjYqlRD7eN7MeIt2PQ_.kind = 24;
NTI_lKsVWjYqlRD7eN7MeIt2PQ_.base = (&NTI_6oh6PoZxxmRrkez9bmwfPdQ_);
NTI_lKsVWjYqlRD7eN7MeIt2PQ_.marker = Marker_tySequence_lKsVWjYqlRD7eN7MeIt2PQ;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[3].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[3].offset = offsetof(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA, fds);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[3].typ = (&NTI_lKsVWjYqlRD7eN7MeIt2PQ_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[3].name = "fds";
TM_ln5vuDpFyDrAqQbYD2g52Q_2[3] = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[28];
TM_ln5vuDpFyDrAqQbYD2g52Q_0[28].kind = 1;
TM_ln5vuDpFyDrAqQbYD2g52Q_0[28].offset = offsetof(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA, count);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[28].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[28].name = "count";
TM_ln5vuDpFyDrAqQbYD2g52Q_0[0].len = 4; TM_ln5vuDpFyDrAqQbYD2g52Q_0[0].kind = 2; TM_ln5vuDpFyDrAqQbYD2g52Q_0[0].sons = &TM_ln5vuDpFyDrAqQbYD2g52Q_2[0];
NTI_VF2QWbk9cEn13YFg9btPwWLA_.node = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[0];
NTI_eV1HoGAGYVaJgQ5BCEf67g_.size = sizeof(tyObject_SelectorImpl_VF2QWbk9cEn13YFg9btPwWLA*);
NTI_eV1HoGAGYVaJgQ5BCEf67g_.kind = 22;
NTI_eV1HoGAGYVaJgQ5BCEf67g_.base = (&NTI_VF2QWbk9cEn13YFg9btPwWLA_);
NTI_eV1HoGAGYVaJgQ5BCEf67g_.marker = Marker_tyRef_eV1HoGAGYVaJgQ5BCEf67g;
NTI_0onfiGw9bxynoOBJJC01SAg_.size = sizeof(tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg);
NTI_0onfiGw9bxynoOBJJC01SAg_.kind = 17;
NTI_0onfiGw9bxynoOBJJC01SAg_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_ln5vuDpFyDrAqQbYD2g52Q_0[29].len = 0; TM_ln5vuDpFyDrAqQbYD2g52Q_0[29].kind = 2;
NTI_0onfiGw9bxynoOBJJC01SAg_.node = &TM_ln5vuDpFyDrAqQbYD2g52Q_0[29];
NTI_yREHAUxoe4I2puy9cJ9cMatg_.size = sizeof(tyObject_IOSelectorsException_0onfiGw9bxynoOBJJC01SAg*);
NTI_yREHAUxoe4I2puy9cJ9cMatg_.kind = 22;
NTI_yREHAUxoe4I2puy9cJ9cMatg_.base = (&NTI_0onfiGw9bxynoOBJJC01SAg_);
NTI_yREHAUxoe4I2puy9cJ9cMatg_.marker = Marker_tyRef_yREHAUxoe4I2puy9cJ9cMatg;
}

