/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c -w -O3 -fno-strict-aliasing  -I/home/kuro/.choosenim/toolchains/nim-0.18.0/lib -o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_nativesockets.o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_nativesockets.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/socket.h>
#include <fcntl.h>
#include <netdb.h>
#include <string.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <unistd.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NIM_CHAR tyArray_NSMq3FMCIrS8gSbyinBZ8w[14];
typedef NU8 tyArray_cdsir9aPB24hAk6k77P9b9bCA[8];
typedef NIM_CHAR tyArray_Wfh9bjgBQ4UqJsyISUuDSuA[16];
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg {
  Exception Sup;
};
struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ {
  tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(int, createNativeSocket_BcG9aGQhTam9ajUKte8LeMdQ_2)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol);
N_LIB_PRIVATE N_NIMCALL(short, toInt_OxnVJkB3zYuSbbBvLQDSVA)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain);
N_LIB_PRIVATE N_NIMCALL(int, toInt_8FqW9bXNjjJADB8XlKnpNLg)(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw typ);
N_LIB_PRIVATE N_NIMCALL(int, toInt_9cDpnbeIxivYaLcJBJkQ2nQ)(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg p);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError_tNPXXFl9cb3BG0pJKzUn9bew)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__rzAI8EMyNBAQwGODeohhAA)(NU64 x);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NIM_BOOL, eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgospaths)(NCSTRING x, NCSTRING y);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
int osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w;
sa_family_t nativeAfInet_rQwsjQjVqXvdaL9aZofzWwg;
sa_family_t nativeAfInet6_Da6PongZL9aJxBrf7qeBmfA;
TNimType NTI_Q79bEtFARvq0ekDNtvj3Vqg_;
TNimType NTI_NQT1bItGG2X9byGdrWX7ujw_;
TNimType NTI_dqJ1OqRGclxIMMdSLRzzXg_;
extern TNimType NTI_HX2M9cQhE3jaovp9aYJDdslA_;
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_11, "", 0);
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_12, "Unknown socket family in getAddrString", 38);

N_LIB_PRIVATE N_NIMCALL(short, toInt_OxnVJkB3zYuSbbBvLQDSVA)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain) {
	short result;
	result = (short)0;
	switch (domain) {
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 0):
	{
		result = ((short) 0);
	}
	break;
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 1):
	{
		result = ((short) 1);
	}
	break;
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2):
	{
		result = ((short) 2);
	}
	break;
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23):
	{
		result = ((short) 10);
	}
	break;
	}
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, toInt_8FqW9bXNjjJADB8XlKnpNLg)(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw typ) {
	int result;
	result = (int)0;
	switch (typ) {
	case ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 1):
	{
		result = ((int) 1);
	}
	break;
	case ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 2):
	{
		result = ((int) 2);
	}
	break;
	case ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 5):
	{
		result = ((int) 5);
	}
	break;
	case ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 3):
	{
		result = ((int) 3);
	}
	break;
	}
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, toInt_9cDpnbeIxivYaLcJBJkQ2nQ)(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg p) {
	int result;
	result = (int)0;
	switch (p) {
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 6):
	{
		result = ((int) 6);
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 17):
	{
		result = ((int) 17);
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 18):
	{
		result = ((int) 0);
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 19):
	{
		result = ((int) 41);
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 20):
	{
		result = ((int) 255);
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 21):
	{
		result = ((int) 1);
	}
	break;
	}
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, createNativeSocket_BcG9aGQhTam9ajUKte8LeMdQ_2)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol) {
	int result;
	short T1_;
	int T2_;
	int T3_;
	result = (int)0;
	T1_ = (short)0;
	T1_ = toInt_OxnVJkB3zYuSbbBvLQDSVA(domain);
	T2_ = (int)0;
	T2_ = toInt_8FqW9bXNjjJADB8XlKnpNLg(sockType);
	T3_ = (int)0;
	T3_ = toInt_9cDpnbeIxivYaLcJBJkQ2nQ(protocol);
	result = socket(((int) (T1_)), T2_, T3_);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, newNativeSocket_BcG9aGQhTam9ajUKte8LeMdQ)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol) {
	int result;
	result = (int)0;
	result = createNativeSocket_BcG9aGQhTam9ajUKte8LeMdQ_2(domain, sockType, protocol);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, setBlocking_RBApwF6paZ4dy39bsxU85TA)(int s, NIM_BOOL blocking) {
	NI x;
	int T1_;
	T1_ = (int)0;
	T1_ = fcntl(s, ((int) 3), ((NI) 0));
	x = ((NI) (T1_));
	{
		NI32 T6_;
		if (!(x == ((NI) -1))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_11));
	}
	goto LA2_;
	LA4_: ;
	{
		NI mode;
		{
			if (!blocking) goto LA10_;
			mode = (NI)(x & ((NI) -2049));
		}
		goto LA8_;
		LA10_: ;
		{
			mode = (NI)(x | ((NI) 2048));
		}
		LA8_: ;
		{
			int T15_;
			NI32 T18_;
			T15_ = (int)0;
			T15_ = fcntl(s, ((int) 4), mode);
			if (!(T15_ == ((NI32) -1))) goto LA16_;
			T18_ = (NI32)0;
			T18_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T18_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_11));
		}
		LA16_: ;
	}
	LA2_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, setSockOptInt_AD4OLBf5FHlJkAgq7B9aY5A)(int socket, NI level, NI optname, NI optval) {
	int value;
	value = ((int) (optval));
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = setsockopt(socket, ((int) (level)), ((int) (optname)), ((void*) ((&value))), ((socklen_t) 4));
		if (!(T3_ < ((NI32) 0))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_11));
	}
	LA4_: ;
}

N_LIB_PRIVATE N_NIMCALL(struct addrinfo*, getAddrInfo_fNPnGAYqSzdc2OjHEcTTAw)(NimStringDesc* address, NU16 port, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol) {
	struct addrinfo* result;
	struct addrinfo hints;
	short T1_;
	int gaiResult;
	NimStringDesc* T6_;
	result = (struct addrinfo*)0;
	memset((void*)(&hints), 0, sizeof(hints));
	result = NIM_NIL;
	T1_ = (short)0;
	T1_ = toInt_OxnVJkB3zYuSbbBvLQDSVA(domain);
	hints.ai_family = ((int) (T1_));
	hints.ai_socktype = toInt_8FqW9bXNjjJADB8XlKnpNLg(sockType);
	hints.ai_protocol = toInt_9cDpnbeIxivYaLcJBJkQ2nQ(protocol);
	{
		if (!(domain == ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23))) goto LA4_;
		hints.ai_flags = ((int) 8);
	}
	LA4_: ;
	T6_ = (NimStringDesc*)0;
	T6_ = dollar__rzAI8EMyNBAQwGODeohhAA(port);
	gaiResult = getaddrinfo(address->data, T6_->data, (&hints), &result);
	{
		NI32 T11_;
		NCSTRING T12_;
		NimStringDesc* T13_;
		if (!!((gaiResult == ((NI32) 0)))) goto LA9_;
		T11_ = (NI32)0;
		T11_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		T12_ = (NCSTRING)0;
		T12_ = (char *)gai_strerror(gaiResult);
		T13_ = (NimStringDesc*)0;
		T13_ = cstrToNimstr(T12_);
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T11_, T13_);
	}
	LA9_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, bindAddr_zpvqU0KQkzbkoKaehnMX2A)(int socket, struct sockaddr* name, socklen_t namelen) {
	int result;
	result = (int)0;
	result = bind(socket, name, namelen);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, listen_BNAD35QpM7R1C7EJRtAZ3Q)(int socket, int backlog) {
	int result;
	result = (int)0;
	result = listen(socket, backlog);
	return result;
}

static N_INLINE(NIM_BOOL, eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgospaths)(NCSTRING x, NCSTRING y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		if (!(((void*) (x)) == ((void*) (y)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T6_;
		T6_ = (NIM_BOOL)0;
		T6_ = (x == 0);
		if (T6_) goto LA7_;
		T6_ = (y == 0);
		LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
	LA8_: ;
	{
		int T11_;
		T11_ = (int)0;
		T11_ = strcmp(x, y);
		result = (T11_ == ((NI32) 0));
	}
	LA1_: ;
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getAddrString_wIS6MR5PrZV5s3d85jE2nw)(struct sockaddr* sockAddr) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	{
		NCSTRING T5_;
		if (!((*sockAddr).sa_family == nativeAfInet_rQwsjQjVqXvdaL9aZofzWwg)) goto LA3_;
		T5_ = (NCSTRING)0;
		T5_ = inet_ntoa((*((struct sockaddr_in*) (sockAddr))).sin_addr);
		result = cstrToNimstr(T5_);
	}
	goto LA1_;
	LA3_: ;
	{
		int addrLen;
		struct in6_addr* addr6;
		if (!((*sockAddr).sa_family == nativeAfInet6_Da6PongZL9aJxBrf7qeBmfA)) goto LA7_;
		addrLen = ((int) 46);
		result = mnewString(((NI) (addrLen)));
		addr6 = (&(*((struct sockaddr_in6*) (sockAddr))).sin6_addr);
		{
			NCSTRING T11_;
			NIM_BOOL T12_;
			NI32 T15_;
			T11_ = (NCSTRING)0;
			T11_ = (char *)inet_ntop(((int) 10), ((void*) (addr6)), ((NCSTRING) ((&result->data[((NI) 0)]))), ((NI32) ((result ? result->Sup.len : 0))));
			T12_ = (NIM_BOOL)0;
			T12_ = eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgospaths(T11_, NIM_NIL);
			if (!T12_) goto LA13_;
			T15_ = (NI32)0;
			T15_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T15_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_11));
		}
		LA13_: ;
		{
			int T18_;
			T18_ = (int)0;
			T18_ = IN6_IS_ADDR_V4MAPPED(addr6);
			if (!!((T18_ == ((NI32) 0)))) goto LA19_;
			result = copyStr(result, ((NI) 7));
		}
		LA19_: ;
		result = setLengthStr(result, ((NI) ((result->data ? strlen(result->data) : 0))));
	}
	goto LA1_;
	LA7_: ;
	{
		tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ* e;
		NimStringDesc* T22_;
		e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*) newObj((&NTI_HX2M9cQhE3jaovp9aYJDdslA_), sizeof(tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ));
		(*e).Sup.Sup.Sup.m_type = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
		T22_ = (NimStringDesc*)0;
		T22_ = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_12));
		if (T22_) nimGCunrefNoCycle(T22_);
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "IOError");
	}
	LA1_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, close_ODRNWwddsp7NVetdw9cXCVg)(int socket) {
	int T1_;
	T1_ = (int)0;
	T1_ = close(socket);
	T1_;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void) {
	osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w = ((int) -1);
	nativeAfInet_rQwsjQjVqXvdaL9aZofzWwg = ((sa_family_t) 2);
	nativeAfInet6_Da6PongZL9aJxBrf7qeBmfA = ((sa_family_t) 10);
}

NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void) {
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2[4];
NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4;
static char* NIM_CONST TM_f9bP3LqjpgpB9cXL8Nnak7tQ_3[4] = {
"AF_UNSPEC", 
"AF_UNIX", 
"AF_INET", 
"AF_INET6"};
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_5[4];
NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7;
static char* NIM_CONST TM_f9bP3LqjpgpB9cXL8Nnak7tQ_6[4] = {
"SOCK_STREAM", 
"SOCK_DGRAM", 
"SOCK_RAW", 
"SOCK_SEQPACKET"};
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8[6];
NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10;
static char* NIM_CONST TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9[6] = {
"IPPROTO_TCP", 
"IPPROTO_UDP", 
"IPPROTO_IP", 
"IPPROTO_IPV6", 
"IPPROTO_RAW", 
"IPPROTO_ICMP"};
static TNimNode TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[17];
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.size = sizeof(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg);
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.kind = 14;
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.base = 0;
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.flags = 3;
for (TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4 = 0; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4 < 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4++) {
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4+0].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4+0].offset = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4+0].name = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_3[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4+0];
}
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[0].offset = 0;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[1].offset = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[2].offset = 2;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3].offset = 23;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].len = 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2[0];
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4];
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.flags = 1<<2;
NTI_NQT1bItGG2X9byGdrWX7ujw_.size = sizeof(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw);
NTI_NQT1bItGG2X9byGdrWX7ujw_.kind = 14;
NTI_NQT1bItGG2X9byGdrWX7ujw_.base = 0;
NTI_NQT1bItGG2X9byGdrWX7ujw_.flags = 3;
for (TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7 = 0; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7 < 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7++) {
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7+5].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7+5].offset = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7+5].name = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_6[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_5[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7+5];
}
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[5].offset = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[6].offset = 2;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[7].offset = 3;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8].offset = 5;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9].len = 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_5[0];
NTI_NQT1bItGG2X9byGdrWX7ujw_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9];
NTI_NQT1bItGG2X9byGdrWX7ujw_.flags = 1<<2;
NTI_dqJ1OqRGclxIMMdSLRzzXg_.size = sizeof(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg);
NTI_dqJ1OqRGclxIMMdSLRzzXg_.kind = 14;
NTI_dqJ1OqRGclxIMMdSLRzzXg_.base = 0;
NTI_dqJ1OqRGclxIMMdSLRzzXg_.flags = 3;
for (TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10 = 0; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10 < 6; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10++) {
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10+10].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10+10].offset = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10+10].name = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10+10];
}
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[10].offset = 6;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[11].offset = 17;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[12].offset = 18;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[13].offset = 19;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[14].offset = 20;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15].offset = 21;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16].len = 6; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8[0];
NTI_dqJ1OqRGclxIMMdSLRzzXg_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16];
NTI_dqJ1OqRGclxIMMdSLRzzXg_.flags = 1<<2;
}

