/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c -w -O3 -fno-strict-aliasing  -I/home/kuro/.choosenim/toolchains/nim-0.18.0/lib -o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_parseutils.o /home/kuro/Projects/PTUT/baldmanSagen/config/nimcache/stdlib_parseutils.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_CHAR, toLower_gKPHIHXd4J0BNtguLE8NFAparseutils)(NIM_CHAR c);

static N_INLINE(NIM_CHAR, toLower_gKPHIHXd4J0BNtguLE8NFAparseutils)(NIM_CHAR c) {
	NIM_CHAR result;
	result = (NIM_CHAR)0;
	{
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3_;
		result = ((NIM_CHAR) (((NI) ((NI)((NI)(((NU8)(c)) - ((NI) 65)) + ((NI) 97))))));
	}
	goto LA1_;
	LA3_: ;
	{
		result = c;
	}
	LA1_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, skipIgnoreCase_VAyQjUeyh3FpMmhHGpH3aQ)(NimStringDesc* s, NimStringDesc* token, NI start) {
	NI result;
	result = (NI)0;
	{
		while (1) {
			NIM_BOOL T3_;
			NIM_CHAR T5_;
			NIM_CHAR T6_;
			T3_ = (NIM_BOOL)0;
			T3_ = (result < (token ? token->Sup.len : 0));
			if (!(T3_)) goto LA4_;
			T5_ = (NIM_CHAR)0;
			T5_ = toLower_gKPHIHXd4J0BNtguLE8NFAparseutils(s->data[(NI)(result + start)]);
			T6_ = (NIM_CHAR)0;
			T6_ = toLower_gKPHIHXd4J0BNtguLE8NFAparseutils(token->data[result]);
			T3_ = ((NU8)(T5_) == (NU8)(T6_));
			LA4_: ;
			if (!T3_) goto LA2;
			result += ((NI) 1);
		} LA2: ;
	}
	{
		if (!!((result == (token ? token->Sup.len : 0)))) goto LA9_;
		result = ((NI) 0);
	}
	LA9_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, parseSaturatedNatural_heAOnV8CAiOgwhPKbfpRgA)(NimStringDesc* s, NI* b, NI start) {
	NI result;
	NI i;
	result = (NI)0;
	i = start;
	{
		if (!((NU8)(s->data[i]) == (NU8)(43))) goto LA3_;
		i += ((NI) 1);
	}
	LA3_: ;
	{
		if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA7_;
		(*b) = ((NI) 0);
		{
			while (1) {
				NI c;
				if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA10;
				c = (NI)(((NU8)(s->data[i])) - ((NI) 48));
				{
					if (!((*b) <= (NI)((NI)(((NI) IL64(9223372036854775807)) - c) / ((NI) 10)))) goto LA13_;
					(*b) = (NI)((NI)((*b) * ((NI) 10)) + c);
				}
				goto LA11_;
				LA13_: ;
				{
					(*b) = ((NI) IL64(9223372036854775807));
				}
				LA11_: ;
				i += ((NI) 1);
				{
					while (1) {
						if (!((NU8)(s->data[i]) == (NU8)(95))) goto LA17;
						i += ((NI) 1);
					} LA17: ;
				}
			} LA10: ;
		}
		result = (NI)(i - start);
	}
	LA7_: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void) {
}

